import type { TSchema } from "@sinclair/typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  AgentWaitResultSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsInstallParamsSchema,
  SkillsInstallResultSchema,
  SkillsStatusParamsSchema,
  SkillsStatusResultSchema,
  SkillsUpdateParamsSchema,
  SkillsUpdateResultSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
  ToolsEffectiveEntrySchema,
  ToolsEffectiveGroupSchema,
  ToolsEffectiveParamsSchema,
  ToolsEffectiveResultSchema,
} from "./agents-models-skills.js";
import {
  ChannelsLogoutParamsSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  TalkSpeakParamsSchema,
  TalkSpeakResultSchema,
  TalkModeResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  ChannelsLogoutResultSchema,
  DoctorMemoryStatusResultSchema,
  HealthResultSchema,
  ModelsCatalogProvidersResultSchema,
  StatusResultSchema,
} from "./control-plane-results.js";
import {
  CronAddParamsSchema,
  CronAddResultSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronListResultSchema,
  CronRemoveParamsSchema,
  CronRemoveResultSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunResultSchema,
  CronRunsParamsSchema,
  CronRunsResultSchema,
  CronStatusParamsSchema,
  CronStatusResultSchema,
  CronUpdateParamsSchema,
  CronUpdateResultSchema,
} from "./cron.js";
import {
  DeckAgentsDetailResultSchema,
  DeckAgentsEventStreamsGetResultSchema,
  DeckAgentsEventStreamsSetResultSchema,
  DeckAgentsSkillsGetResultSchema,
  DeckAgentsSkillsSetResultSchema,
  DeckAgentsSubagentsGetResultSchema,
  DeckAgentsSubagentsSetResultSchema,
  DeckAgentsSystemPromptPreviewResultSchema,
  DeckAgentsToolPolicyPreviewResultSchema,
  DeckAuthOverviewResultSchema,
  DeckAuthProbeResultSchema,
  DeckIdentityLinkResultSchema,
  DeckIdentityListResultSchema,
  DeckIdentityUnlinkResultSchema,
  DeckRoutingAddResultSchema,
  DeckRoutingListResultSchema,
  DeckRoutingRemoveResultSchema,
  DeckRoutingSimulateResultSchema,
  DeckRoutingValidateResultSchema,
  DeckSubagentsKillResultSchema,
  DeckSubagentsLineageResultSchema,
  DeckSubagentsListResultSchema,
  DeckSubagentsSteerResultSchema,
  DeckThreadsListResultSchema,
} from "./deck.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairApproveResultSchema,
  DevicePairListParamsSchema,
  DevicePairListResultSchema,
  DevicePairRejectParamsSchema,
  DevicePairRejectResultSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRemoveResultSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRevokeResultSchema,
  DeviceTokenRotateParamsSchema,
  DeviceTokenRotateResultSchema,
} from "./devices.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalRequestResultSchema,
  ExecApprovalResolveParamsSchema,
  ExecApprovalResolveResultSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  ChatAbortParamsSchema,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodePendingDrainParamsSchema,
  NodePendingDrainResultSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResultSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePendingAckParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  SecretsReloadParamsSchema,
  SecretsResolveAssignmentSchema,
  SecretsResolveParamsSchema,
  SecretsResolveResultSchema,
} from "./secrets.js";
import {
  SessionsAbortParamsSchema,
  SessionsClearParamsSchema,
  SessionsCompactParamsSchema,
  SessionsCreateParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsListParamsSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsSendParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  SessionMessageEventPayloadSchema,
  SessionsChangedEventPayloadSchema,
  SessionSnapshotFieldsSchema,
  SessionToolEventDataSchema,
  SessionToolEventPayloadSchema,
  TranscriptBlockSchema,
  TranscriptFileBlockSchema,
  TranscriptImageBlockSchema,
  TranscriptMessageSchema,
  TranscriptRoleSchema,
  TranscriptTextBlockSchema,
  TranscriptThinkingBlockSchema,
  TranscriptToolUseBlockSchema,
} from "./transcript.js";
import {
  CostUsageTotalsSchema,
  SessionCostSummarySchema,
  SessionDailyLatencySchema,
  SessionDailyMessageCountsSchema,
  SessionDailyModelUsageSchema,
  SessionDailyUsageSchema,
  SessionLatencyStatsSchema,
  SessionLogEntrySchema,
  SessionMessageCountsSchema,
  SessionModelUsageSchema,
  SessionSystemPromptReportSchema,
  SessionToolUsageSchema,
  SessionUsageTimePointSchema,
  SessionUsageEntrySchema,
  SessionsUsageAggregatesSchema,
  SessionsUsageLogsParamsSchema,
  SessionsUsageLogsResultSchema,
  SessionsUsageResultSchema,
  SessionsUsageTimeseriesParamsSchema,
  SessionsUsageTimeseriesResultSchema,
  UsageCostResultSchema,
  UsageStatusResultSchema,
} from "./usage-result-schemas.js";
import {
  WizardCancelParamsSchema,
  WizardCancelResultSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";

export const ProtocolSchemas = {
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  AgentEvent: AgentEventSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  AgentWaitResult: AgentWaitResultSchema,
  WakeParams: WakeParamsSchema,
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodePendingAckParams: NodePendingAckParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodePendingDrainParams: NodePendingDrainParamsSchema,
  NodePendingDrainResult: NodePendingDrainResultSchema,
  NodePendingEnqueueParams: NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResult: NodePendingEnqueueResultSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  SecretsReloadParams: SecretsReloadParamsSchema,
  SecretsResolveParams: SecretsResolveParamsSchema,
  SecretsResolveAssignment: SecretsResolveAssignmentSchema,
  SecretsResolveResult: SecretsResolveResultSchema,
  SessionsListParams: SessionsListParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsCreateParams: SessionsCreateParamsSchema,
  SessionsSendParams: SessionsSendParamsSchema,
  SessionsMessagesSubscribeParams: SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParams: SessionsMessagesUnsubscribeParamsSchema,
  SessionsAbortParams: SessionsAbortParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsClearParams: SessionsClearParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,
  CostUsageTotals: CostUsageTotalsSchema,
  SessionDailyUsage: SessionDailyUsageSchema,
  SessionDailyMessageCounts: SessionDailyMessageCountsSchema,
  SessionLatencyStats: SessionLatencyStatsSchema,
  SessionDailyLatency: SessionDailyLatencySchema,
  SessionDailyModelUsage: SessionDailyModelUsageSchema,
  SessionLogEntry: SessionLogEntrySchema,
  SessionMessageCounts: SessionMessageCountsSchema,
  SessionToolUsage: SessionToolUsageSchema,
  SessionModelUsage: SessionModelUsageSchema,
  SessionCostSummary: SessionCostSummarySchema,
  SessionSystemPromptReport: SessionSystemPromptReportSchema,
  SessionUsageTimePoint: SessionUsageTimePointSchema,
  SessionUsageEntry: SessionUsageEntrySchema,
  SessionsUsageAggregates: SessionsUsageAggregatesSchema,
  SessionsUsageLogsParams: SessionsUsageLogsParamsSchema,
  SessionsUsageLogsResult: SessionsUsageLogsResultSchema,
  SessionsUsageResult: SessionsUsageResultSchema,
  SessionsUsageTimeseriesParams: SessionsUsageTimeseriesParamsSchema,
  SessionsUsageTimeseriesResult: SessionsUsageTimeseriesResultSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: ConfigSchemaLookupResultSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,
  WizardCancelResult: WizardCancelResultSchema,
  TalkModeParams: TalkModeParamsSchema,
  TalkModeResult: TalkModeResultSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  TalkSpeakParams: TalkSpeakParamsSchema,
  TalkSpeakResult: TalkSpeakResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  SkillsStatusResult: SkillsStatusResultSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  ToolsEffectiveParams: ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: ToolsEffectiveGroupSchema,
  ToolsEffectiveResult: ToolsEffectiveResultSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsInstallResult: SkillsInstallResultSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  SkillsUpdateResult: SkillsUpdateResultSchema,
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronListResult: CronListResultSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronStatusResult: CronStatusResultSchema,
  CronAddParams: CronAddParamsSchema,
  CronAddResult: CronAddResultSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronUpdateResult: CronUpdateResultSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRemoveResult: CronRemoveResultSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunResult: CronRunResultSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunsResult: CronRunsResultSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  TranscriptRole: TranscriptRoleSchema,
  TranscriptTextBlock: TranscriptTextBlockSchema,
  TranscriptThinkingBlock: TranscriptThinkingBlockSchema,
  TranscriptToolUseBlock: TranscriptToolUseBlockSchema,
  TranscriptImageBlock: TranscriptImageBlockSchema,
  TranscriptFileBlock: TranscriptFileBlockSchema,
  TranscriptBlock: TranscriptBlockSchema,
  TranscriptMessage: TranscriptMessageSchema,
  SessionSnapshotFields: SessionSnapshotFieldsSchema,
  SessionMessageEventPayload: SessionMessageEventPayloadSchema,
  SessionToolEventData: SessionToolEventDataSchema,
  SessionToolEventPayload: SessionToolEventPayloadSchema,
  SessionsChangedEventPayload: SessionsChangedEventPayloadSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalRequestResult: ExecApprovalRequestResultSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  ExecApprovalResolveResult: ExecApprovalResolveResultSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairListResult: DevicePairListResultSchema,
  DevicePairApproveResult: DevicePairApproveResultSchema,
  DevicePairRejectResult: DevicePairRejectResultSchema,
  DevicePairRemoveResult: DevicePairRemoveResultSchema,
  DeviceTokenRotateResult: DeviceTokenRotateResultSchema,
  DeviceTokenRevokeResult: DeviceTokenRevokeResultSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatEvent: ChatEventSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
  // deck.* result schemas
  DeckRoutingListResult: DeckRoutingListResultSchema,
  DeckRoutingAddResult: DeckRoutingAddResultSchema,
  DeckRoutingRemoveResult: DeckRoutingRemoveResultSchema,
  DeckRoutingValidateResult: DeckRoutingValidateResultSchema,
  DeckRoutingSimulateResult: DeckRoutingSimulateResultSchema,
  DeckAgentsDetailResult: DeckAgentsDetailResultSchema,
  DeckAgentsSkillsGetResult: DeckAgentsSkillsGetResultSchema,
  DeckAgentsSkillsSetResult: DeckAgentsSkillsSetResultSchema,
  DeckAgentsSubagentsGetResult: DeckAgentsSubagentsGetResultSchema,
  DeckAgentsSubagentsSetResult: DeckAgentsSubagentsSetResultSchema,
  DeckAgentsEventStreamsGetResult: DeckAgentsEventStreamsGetResultSchema,
  DeckAgentsEventStreamsSetResult: DeckAgentsEventStreamsSetResultSchema,
  DeckAgentsToolPolicyPreviewResult: DeckAgentsToolPolicyPreviewResultSchema,
  DeckAgentsSystemPromptPreviewResult: DeckAgentsSystemPromptPreviewResultSchema,
  DeckSubagentsListResult: DeckSubagentsListResultSchema,
  DeckSubagentsKillResult: DeckSubagentsKillResultSchema,
  DeckSubagentsLineageResult: DeckSubagentsLineageResultSchema,
  DeckSubagentsSteerResult: DeckSubagentsSteerResultSchema,
  DeckIdentityListResult: DeckIdentityListResultSchema,
  DeckIdentityLinkResult: DeckIdentityLinkResultSchema,
  DeckIdentityUnlinkResult: DeckIdentityUnlinkResultSchema,
  DeckThreadsListResult: DeckThreadsListResultSchema,
  DeckAuthOverviewResult: DeckAuthOverviewResultSchema,
  DeckAuthProbeResult: DeckAuthProbeResultSchema,
  // control-plane result schemas
  HealthResult: HealthResultSchema,
  StatusResult: StatusResultSchema,
  DoctorMemoryStatusResult: DoctorMemoryStatusResultSchema,
  UsageStatusResult: UsageStatusResultSchema,
  UsageCostResult: UsageCostResultSchema,
  ModelsCatalogProvidersResult: ModelsCatalogProvidersResultSchema,
  ChannelsLogoutResult: ChannelsLogoutResultSchema,
} satisfies Record<string, TSchema>;

export const PROTOCOL_VERSION = 3 as const;
