import type { TSchema } from "@sinclair/typebox";
import { SkillsInstallResultSchema } from "./agents-models-skills-extensions.js";
import {
  DeckAgentsDetailResultSchema,
  DeckAgentsEventStreamsGetResultSchema,
  DeckAgentsEventStreamsSetResultSchema,
  DeckAgentsSkillsGetResultSchema,
  DeckAgentsSkillsSetResultSchema,
  DeckAgentsSubagentsGetResultSchema,
  DeckAgentsSubagentsSetResultSchema,
  DeckAgentsSystemPromptPreviewResultSchema,
  DeckAgentsToolPolicyPreviewResultSchema,
  DeckAuthOverviewResultSchema,
  DeckAuthProbeResultSchema,
  DeckIdentityLinkResultSchema,
  DeckIdentityListResultSchema,
  DeckIdentityUnlinkResultSchema,
  DeckRoutingAddResultSchema,
  DeckRoutingListResultSchema,
  DeckRoutingRemoveResultSchema,
  DeckRoutingSimulateResultSchema,
  DeckRoutingValidateResultSchema,
  DeckSubagentsKillResultSchema,
  DeckSubagentsLineageResultSchema,
  DeckSubagentsListResultSchema,
  DeckSubagentsSteerResultSchema,
  DeckThreadsListResultSchema,
} from "./deck.js";
import { GatewayBatchParamsSchema, GatewayBatchResultSchema } from "./gateway-batch.js";
import { SessionsClearParamsSchema } from "./sessions-extensions.js";
import {
  SessionMessageEventPayloadSchema,
  SessionsChangedEventPayloadSchema,
  SessionSnapshotFieldsSchema,
  SessionToolEventDataSchema,
  SessionToolEventPayloadSchema,
  TranscriptBlockSchema,
  TranscriptFileBlockSchema,
  TranscriptImageBlockSchema,
  TranscriptMessageSchema,
  TranscriptRoleSchema,
  TranscriptTextBlockSchema,
  TranscriptThinkingBlockSchema,
  TranscriptToolUseBlockSchema,
} from "./transcript.js";
import {
  CostUsageTotalsSchema,
  SessionCostSummarySchema,
  SessionDailyLatencySchema,
  SessionDailyMessageCountsSchema,
  SessionDailyModelUsageSchema,
  SessionDailyUsageSchema,
  SessionLatencyStatsSchema,
  SessionLogEntrySchema,
  SessionMessageCountsSchema,
  SessionModelUsageSchema,
  SessionSystemPromptReportSchema,
  SessionToolUsageSchema,
  SessionUsageTimePointSchema,
  SessionUsageEntrySchema,
  SessionsUsageAggregatesSchema,
  SessionsUsageLogsParamsSchema,
  SessionsUsageLogsResultSchema,
  SessionsUsageResultSchema,
  SessionsUsageTimeseriesParamsSchema,
  SessionsUsageTimeseriesResultSchema,
} from "./usage-result-schemas.js";

export const ProtocolExtensionSchemas = {
  SessionsClearParams: SessionsClearParamsSchema,
  CostUsageTotals: CostUsageTotalsSchema,
  SessionDailyUsage: SessionDailyUsageSchema,
  SessionDailyMessageCounts: SessionDailyMessageCountsSchema,
  SessionLatencyStats: SessionLatencyStatsSchema,
  SessionDailyLatency: SessionDailyLatencySchema,
  SessionDailyModelUsage: SessionDailyModelUsageSchema,
  SessionLogEntry: SessionLogEntrySchema,
  SessionMessageCounts: SessionMessageCountsSchema,
  SessionToolUsage: SessionToolUsageSchema,
  SessionModelUsage: SessionModelUsageSchema,
  SessionCostSummary: SessionCostSummarySchema,
  SessionSystemPromptReport: SessionSystemPromptReportSchema,
  SessionUsageTimePoint: SessionUsageTimePointSchema,
  SessionUsageEntry: SessionUsageEntrySchema,
  SessionsUsageAggregates: SessionsUsageAggregatesSchema,
  SessionsUsageLogsParams: SessionsUsageLogsParamsSchema,
  SessionsUsageLogsResult: SessionsUsageLogsResultSchema,
  SessionsUsageResult: SessionsUsageResultSchema,
  SessionsUsageTimeseriesParams: SessionsUsageTimeseriesParamsSchema,
  SessionsUsageTimeseriesResult: SessionsUsageTimeseriesResultSchema,
  GatewayBatchParams: GatewayBatchParamsSchema,
  GatewayBatchResult: GatewayBatchResultSchema,
  SkillsInstallResult: SkillsInstallResultSchema,
  TranscriptRole: TranscriptRoleSchema,
  TranscriptTextBlock: TranscriptTextBlockSchema,
  TranscriptThinkingBlock: TranscriptThinkingBlockSchema,
  TranscriptToolUseBlock: TranscriptToolUseBlockSchema,
  TranscriptImageBlock: TranscriptImageBlockSchema,
  TranscriptFileBlock: TranscriptFileBlockSchema,
  TranscriptBlock: TranscriptBlockSchema,
  TranscriptMessage: TranscriptMessageSchema,
  SessionSnapshotFields: SessionSnapshotFieldsSchema,
  SessionMessageEventPayload: SessionMessageEventPayloadSchema,
  SessionToolEventData: SessionToolEventDataSchema,
  SessionToolEventPayload: SessionToolEventPayloadSchema,
  SessionsChangedEventPayload: SessionsChangedEventPayloadSchema,
  DeckRoutingListResult: DeckRoutingListResultSchema,
  DeckRoutingAddResult: DeckRoutingAddResultSchema,
  DeckRoutingRemoveResult: DeckRoutingRemoveResultSchema,
  DeckRoutingValidateResult: DeckRoutingValidateResultSchema,
  DeckRoutingSimulateResult: DeckRoutingSimulateResultSchema,
  DeckAgentsDetailResult: DeckAgentsDetailResultSchema,
  DeckAgentsSkillsGetResult: DeckAgentsSkillsGetResultSchema,
  DeckAgentsSkillsSetResult: DeckAgentsSkillsSetResultSchema,
  DeckAgentsSubagentsGetResult: DeckAgentsSubagentsGetResultSchema,
  DeckAgentsSubagentsSetResult: DeckAgentsSubagentsSetResultSchema,
  DeckAgentsEventStreamsGetResult: DeckAgentsEventStreamsGetResultSchema,
  DeckAgentsEventStreamsSetResult: DeckAgentsEventStreamsSetResultSchema,
  DeckAgentsToolPolicyPreviewResult: DeckAgentsToolPolicyPreviewResultSchema,
  DeckAgentsSystemPromptPreviewResult: DeckAgentsSystemPromptPreviewResultSchema,
  DeckSubagentsListResult: DeckSubagentsListResultSchema,
  DeckSubagentsKillResult: DeckSubagentsKillResultSchema,
  DeckSubagentsLineageResult: DeckSubagentsLineageResultSchema,
  DeckSubagentsSteerResult: DeckSubagentsSteerResultSchema,
  DeckIdentityListResult: DeckIdentityListResultSchema,
  DeckIdentityLinkResult: DeckIdentityLinkResultSchema,
  DeckIdentityUnlinkResult: DeckIdentityUnlinkResultSchema,
  DeckThreadsListResult: DeckThreadsListResultSchema,
  DeckAuthOverviewResult: DeckAuthOverviewResultSchema,
  DeckAuthProbeResult: DeckAuthProbeResultSchema,
} satisfies Record<string, TSchema>;
