// AUTO-GENERATED FROM contracts/source/deck-api.contract.ts
// Do not edit this file directly.

package deckapi

type DeckGoSettings struct {
	AccessToken string `json:"accessToken,omitempty"`
	GatewayUrl string `json:"gatewayUrl,omitempty"`
	GatewayToken string `json:"gatewayToken,omitempty"`
}

type DeckGoSettingsResponse struct {
	Ok bool `json:"ok"`
	Settings DeckGoSettings `json:"settings"`
	Path string `json:"path"`
}

type DeckGoSettingsSaveResponse struct {
	Ok bool `json:"ok"`
	Settings DeckGoSettings `json:"settings"`
}

type DeckGoBootstrapSettingsStatus struct {
	Path string `json:"path"`
	AccessTokenConfigured bool `json:"accessTokenConfigured"`
	GatewayUrlConfigured bool `json:"gatewayUrlConfigured"`
	GatewayTokenConfigured bool `json:"gatewayTokenConfigured"`
}

type DeckGoBootstrapGatewayStatus struct {
	Connected bool `json:"connected"`
	Error string `json:"error,omitempty"`
	Describe any `json:"describe,omitempty"`
}

type DeckGoBootstrapStatusResponse struct {
	Ok bool `json:"ok"`
	Settings DeckGoBootstrapSettingsStatus `json:"settings"`
	Gateway DeckGoBootstrapGatewayStatus `json:"gateway"`
}

type DeckGoConfigSchemaLookupRequest struct {
	Path string `json:"path"`
}

type DeckGoChatSessionCreateRequest struct {
	AgentId string `json:"agentId,omitempty"`
	Message string `json:"message,omitempty"`
	Model string `json:"model,omitempty"`
	Label string `json:"label,omitempty"`
	ParentSessionKey string `json:"parentSessionKey,omitempty"`
}

type DeckGoChatSendRequest struct {
	SessionKey string `json:"sessionKey"`
	Message string `json:"message,omitempty"`
	Thinking string `json:"thinking,omitempty"`
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	Attachments []map[string]any `json:"attachments,omitempty"`
}

type DeckGoChatAbortRequest struct {
	SessionKey string `json:"sessionKey"`
	RunId string `json:"runId,omitempty"`
}

type DeckGoSessionEventsRequest struct {
	SessionKey string `json:"sessionKey"`
	Action string `json:"action"`
}

type DeckGoChatSnapshotResponse struct {
	Messages []map[string]any `json:"messages"`
	Meta map[string]any `json:"meta"`
	ActiveApproval map[string]any `json:"activeApproval"`
	A2uiState any `json:"a2uiState"`
}

type DeckGoChatHistoryResponse struct {
	Messages []map[string]any `json:"messages"`
}

type DeckGoChannelsStatusResponse struct {
	Ts float64 `json:"ts,omitempty"`
	ChannelOrder []string `json:"channelOrder,omitempty"`
	Channels map[string]any `json:"channels,omitempty"`
	ChannelAccounts map[string]any `json:"channelAccounts,omitempty"`
	ChannelDefaultAccountId map[string]string `json:"channelDefaultAccountId,omitempty"`
	ChannelLabels map[string]string `json:"channelLabels,omitempty"`
}

type DeckGoPluginInventoryEntry struct {
	Id string `json:"id"`
	Name string `json:"name,omitempty"`
	Status string `json:"status,omitempty"`
	Origin string `json:"origin,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
}

type DeckGoPluginsListResponse struct {
	Scope string `json:"scope,omitempty"`
	Plugins []DeckGoPluginInventoryEntry `json:"plugins,omitempty"`
}

type DeckGoSessionsListResponse struct {
	Sessions []map[string]any `json:"sessions,omitempty"`
}

type DeckGoServerEvent struct {
	Id string `json:"id,omitempty"`
	Event string `json:"event,omitempty"`
	Data string `json:"data,omitempty"`
}

type DeckGoLogStreamEvent struct {
	Id string `json:"id,omitempty"`
	Event string `json:"event,omitempty"`
	Data string `json:"data,omitempty"`
}

type DeckGoSessionsPreviewResponse struct {
	Ts float64 `json:"ts,omitempty"`
	Previews []map[string]any `json:"previews,omitempty"`
}
