// AUTO-GENERATED FROM contracts/source/deck-api.contract.ts
// Do not edit this file directly.

package deckapi

type DeckGoManagedGatewaySettings struct {
	Mode string `json:"mode,omitempty"`
	Command string `json:"command,omitempty"`
	Args []string `json:"args,omitempty"`
	WorkingDir string `json:"workingDir,omitempty"`
	BindHost string `json:"bindHost,omitempty"`
	BindPort float64 `json:"bindPort,omitempty"`
	GatewayToken string `json:"gatewayToken,omitempty"`
	AutoStart bool `json:"autoStart,omitempty"`
	Env map[string]string `json:"env,omitempty"`
}

type DeckGoSettings struct {
	AccessToken string `json:"accessToken,omitempty"`
	ManagedGateway DeckGoManagedGatewaySettings `json:"managedGateway,omitempty"`
}

type DeckGoSettingsResponse struct {
	Ok bool `json:"ok"`
	Settings DeckGoSettings `json:"settings"`
	Path string `json:"path"`
}

type DeckGoSettingsSaveResponse struct {
	Ok bool `json:"ok"`
	Settings DeckGoSettings `json:"settings"`
}

type DeckGoBootstrapSettingsStatus struct {
	Path string `json:"path"`
	AccessTokenConfigured bool `json:"accessTokenConfigured"`
	ManagedGatewayConfigured bool `json:"managedGatewayConfigured"`
	CommandConfigured bool `json:"commandConfigured"`
	GatewayTokenConfigured bool `json:"gatewayTokenConfigured"`
	AutoStart bool `json:"autoStart"`
}

type DeckGoRuntimeGatewayStatus struct {
	Managed bool `json:"managed"`
	Configured bool `json:"configured,omitempty"`
	Status string `json:"status,omitempty"`
	FailurePhase string `json:"failurePhase,omitempty"`
	Pid float64 `json:"pid,omitempty"`
	StartedAt string `json:"startedAt,omitempty"`
	LastExitAt string `json:"lastExitAt,omitempty"`
	LastExitCode float64 `json:"lastExitCode,omitempty"`
	Health string `json:"health,omitempty"`
	GatewayUrl string `json:"gatewayUrl,omitempty"`
	LastError string `json:"lastError,omitempty"`
	AutoStart bool `json:"autoStart,omitempty"`
}

type DeckGoBootstrapGatewayStatus struct {
	Connected bool `json:"connected"`
	Error string `json:"error,omitempty"`
	CapabilitySnapshotAvailable bool `json:"capabilitySnapshotAvailable,omitempty"`
	MethodCount float64 `json:"methodCount,omitempty"`
	EventCount float64 `json:"eventCount,omitempty"`
	SchemaVersion string `json:"schemaVersion,omitempty"`
}

type DeckGoBootstrapStatusResponse struct {
	Ok bool `json:"ok"`
	Settings DeckGoBootstrapSettingsStatus `json:"settings"`
	Runtime DeckGoRuntimeGatewayStatus `json:"runtime"`
	Gateway DeckGoBootstrapGatewayStatus `json:"gateway"`
}

type DeckGoRuntimeGatewayActionResponse struct {
	Ok bool `json:"ok"`
	Runtime DeckGoRuntimeGatewayStatus `json:"runtime"`
}

type DeckGoGatewayBatchCall struct {
	Id string `json:"id"`
	Method string `json:"method"`
	Params any `json:"params,omitempty"`
}

type DeckGoGatewayBatchOptions struct {
	FailFast bool `json:"failFast,omitempty"`
	TimeoutMs float64 `json:"timeoutMs,omitempty"`
}

type DeckGoGatewayBatchRequest struct {
	Calls []DeckGoGatewayBatchCall `json:"calls"`
	Options DeckGoGatewayBatchOptions `json:"options,omitempty"`
}

type DeckGoGatewayBatchError struct {
	Code string `json:"code"`
	Message string `json:"message"`
	Details any `json:"details,omitempty"`
	Retryable bool `json:"retryable,omitempty"`
	RetryAfterMs float64 `json:"retryAfterMs,omitempty"`
}

type DeckGoGatewayBatchResultEntry struct {
	Id string `json:"id"`
	Ok bool `json:"ok"`
	Result any `json:"result,omitempty"`
	Error DeckGoGatewayBatchError `json:"error,omitempty"`
}

type DeckGoGatewayBatchResponse struct {
	RuntimeId string `json:"runtimeId"`
	RequestId string `json:"requestId"`
	Results []DeckGoGatewayBatchResultEntry `json:"results"`
}

type DeckGoConfigSchemaLookupRequest struct {
	Path string `json:"path"`
}

type DeckGoChatSessionCreateRequest struct {
	AgentId string `json:"agentId,omitempty"`
	Message string `json:"message,omitempty"`
	Model string `json:"model,omitempty"`
	Label string `json:"label,omitempty"`
	ParentSessionKey string `json:"parentSessionKey,omitempty"`
}

type DeckGoChatSendRequest struct {
	SessionKey string `json:"sessionKey"`
	Message string `json:"message,omitempty"`
	Thinking string `json:"thinking,omitempty"`
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	Attachments []map[string]any `json:"attachments,omitempty"`
}

type DeckGoChatAbortRequest struct {
	SessionKey string `json:"sessionKey"`
	RunId string `json:"runId,omitempty"`
}

type DeckGoChatSteerRequest struct {
	SessionKey string `json:"sessionKey"`
	Message string `json:"message"`
}

type DeckGoChatSteerResponse struct {
	Ok bool `json:"ok,omitempty"`
	RunId string `json:"runId,omitempty"`
	Status string `json:"status,omitempty"`
	MessageSeq float64 `json:"messageSeq,omitempty"`
	InterruptedActiveRun bool `json:"interruptedActiveRun,omitempty"`
}

type DeckGoSessionCreateResponse struct {
	Ok bool `json:"ok,omitempty"`
	Key string `json:"key,omitempty"`
	SessionId string `json:"sessionId,omitempty"`
	RunId string `json:"runId,omitempty"`
	Status string `json:"status,omitempty"`
	MessageSeq float64 `json:"messageSeq,omitempty"`
	InterruptedActiveRun bool `json:"interruptedActiveRun,omitempty"`
	RunStarted bool `json:"runStarted,omitempty"`
	RunError any `json:"runError,omitempty"`
	Entry map[string]any `json:"entry,omitempty"`
}

type DeckGoSessionSendResponse struct {
	RunId string `json:"runId,omitempty"`
	Status string `json:"status,omitempty"`
	MessageSeq float64 `json:"messageSeq,omitempty"`
	InterruptedActiveRun bool `json:"interruptedActiveRun,omitempty"`
}

type DeckGoSessionAbortResponse struct {
	Ok bool `json:"ok,omitempty"`
	AbortedRunId string `json:"abortedRunId,omitempty"`
	Status string `json:"status,omitempty"`
}

type DeckGoSessionMutationResponse struct {
	Ok bool `json:"ok,omitempty"`
	Key string `json:"key,omitempty"`
	Entry map[string]any `json:"entry,omitempty"`
}

type DeckGoSessionMeta struct {
	Key string `json:"key"`
	AgentId string `json:"agentId,omitempty"`
	Label string `json:"label,omitempty"`
	Title string `json:"title,omitempty"`
	Kind string `json:"kind,omitempty"`
	UpdatedAt float64 `json:"updatedAt,omitempty"`
	LastMessagePreview string `json:"lastMessagePreview,omitempty"`
	CompactionCount float64 `json:"compactionCount,omitempty"`
	Status string `json:"status,omitempty"`
	StartedAt float64 `json:"startedAt,omitempty"`
	EndedAt float64 `json:"endedAt,omitempty"`
	RuntimeMs float64 `json:"runtimeMs,omitempty"`
	Model string `json:"model,omitempty"`
	ModelProvider string `json:"modelProvider,omitempty"`
	ThinkingLevel string `json:"thinkingLevel,omitempty"`
	FastMode bool `json:"fastMode,omitempty"`
	VerboseLevel string `json:"verboseLevel,omitempty"`
	ReasoningLevel string `json:"reasoningLevel,omitempty"`
	ResponseUsage string `json:"responseUsage,omitempty"`
	SendPolicy string `json:"sendPolicy,omitempty"`
	InputTokens float64 `json:"inputTokens,omitempty"`
	OutputTokens float64 `json:"outputTokens,omitempty"`
	TotalTokens float64 `json:"totalTokens,omitempty"`
	TotalTokensFresh bool `json:"totalTokensFresh,omitempty"`
	EstimatedCostUsd float64 `json:"estimatedCostUsd,omitempty"`
	ContextTokens float64 `json:"contextTokens,omitempty"`
	ParentSessionKey string `json:"parentSessionKey,omitempty"`
	ChildSessions []string `json:"childSessions,omitempty"`
	SubagentRole string `json:"subagentRole,omitempty"`
	SubagentControlScope string `json:"subagentControlScope,omitempty"`
	SpawnedWorkspaceDir string `json:"spawnedWorkspaceDir,omitempty"`
}

type DeckGoSessionPreviewOverlay struct {
	Role string `json:"role"`
	Text string `json:"text"`
}

type DeckGoSessionPreviewEntry struct {
	Key string `json:"key"`
	Status string `json:"status,omitempty"`
	Items []DeckGoSessionPreviewOverlay `json:"items,omitempty"`
}

type DeckGoTranscriptBlock struct {
	Type string `json:"type"`
	Text string `json:"text,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Input map[string]any `json:"input,omitempty"`
	ToolUseId string `json:"toolUseId,omitempty"`
	Content any `json:"content,omitempty"`
	IsError bool `json:"isError,omitempty"`
	Data string `json:"data,omitempty"`
	MimeType string `json:"mimeType,omitempty"`
	FileName string `json:"fileName,omitempty"`
	Size float64 `json:"size,omitempty"`
	Kind string `json:"kind,omitempty"`
	Surface string `json:"surface,omitempty"`
	Render string `json:"render,omitempty"`
	Url string `json:"url,omitempty"`
	Title string `json:"title,omitempty"`
	PreferredHeight float64 `json:"preferredHeight,omitempty"`
	Summary map[string]any `json:"summary,omitempty"`
}

type DeckGoTranscriptMessage struct {
	Id string `json:"id"`
	Role string `json:"role"`
	Content []DeckGoTranscriptBlock `json:"content"`
	Timestamp float64 `json:"timestamp,omitempty"`
	Streaming bool `json:"streaming,omitempty"`
	Error string `json:"error,omitempty"`
}

type DeckGoSessionDetailResponse struct {
	Session DeckGoSessionMeta `json:"session,omitempty"`
	Messages []DeckGoTranscriptMessage `json:"messages,omitempty"`
	ActiveApproval map[string]any `json:"activeApproval,omitempty"`
	A2uiState any `json:"a2uiState,omitempty"`
}

type DeckGoSessionMessageStreamEvent struct {
	SessionKey string `json:"sessionKey"`
	Message DeckGoTranscriptMessage `json:"message,omitempty"`
	MessageId string `json:"messageId,omitempty"`
	MessageSeq float64 `json:"messageSeq,omitempty"`
	UpdatedAt float64 `json:"updatedAt,omitempty"`
	Status string `json:"status,omitempty"`
}

type DeckGoSessionToolStreamEvent struct {
	RunId string `json:"runId"`
	Seq float64 `json:"seq"`
	Stream string `json:"stream"`
	Ts float64 `json:"ts"`
	SessionKey string `json:"sessionKey"`
	Data map[string]any `json:"data"`
}

type DeckGoSessionsChangedStreamEvent struct {
	SessionKey string `json:"sessionKey"`
	Phase string `json:"phase,omitempty"`
	Ts float64 `json:"ts"`
	RunId string `json:"runId,omitempty"`
	MessageId string `json:"messageId,omitempty"`
	MessageSeq float64 `json:"messageSeq,omitempty"`
	Reason string `json:"reason,omitempty"`
	Label string `json:"label,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	UpdatedAt float64 `json:"updatedAt,omitempty"`
	Status string `json:"status,omitempty"`
	StartedAt float64 `json:"startedAt,omitempty"`
	EndedAt float64 `json:"endedAt,omitempty"`
	RuntimeMs float64 `json:"runtimeMs,omitempty"`
}

type DeckGoSessionEventsRequest struct {
	SessionKey string `json:"sessionKey"`
	Action string `json:"action"`
}

type DeckGoSessionEventsResponse struct {
	Ok bool `json:"ok"`
	SessionKey string `json:"sessionKey"`
	Action string `json:"action"`
}

type DeckGoChatSnapshotResponse struct {
	Session DeckGoSessionMeta `json:"session,omitempty"`
	Messages []DeckGoTranscriptMessage `json:"messages"`
	ActiveApproval map[string]any `json:"activeApproval"`
	A2uiState any `json:"a2uiState"`
}

type DeckGoChatHistoryResponse struct {
	Messages []DeckGoTranscriptMessage `json:"messages"`
}

type DeckGoChannelUiMeta struct {
	Id string `json:"id"`
	Label string `json:"label"`
	DetailLabel string `json:"detailLabel"`
	SystemImage string `json:"systemImage,omitempty"`
	PluginId string `json:"pluginId,omitempty"`
	PluginOrigin string `json:"pluginOrigin,omitempty"`
	PluginNpmSpec string `json:"pluginNpmSpec,omitempty"`
	PluginLocalPath string `json:"pluginLocalPath,omitempty"`
	PluginDefaultInstallChoice string `json:"pluginDefaultInstallChoice,omitempty"`
	PluginConfigPath string `json:"pluginConfigPath,omitempty"`
}

type DeckGoChannelsStatusResponse struct {
	Ts float64 `json:"ts,omitempty"`
	ChannelOrder []string `json:"channelOrder,omitempty"`
	Channels map[string]any `json:"channels,omitempty"`
	ChannelAccounts map[string]any `json:"channelAccounts,omitempty"`
	ChannelDefaultAccountId map[string]string `json:"channelDefaultAccountId,omitempty"`
	ChannelLabels map[string]string `json:"channelLabels,omitempty"`
	ChannelDetailLabels map[string]string `json:"channelDetailLabels,omitempty"`
	ChannelSystemImages map[string]string `json:"channelSystemImages,omitempty"`
	ChannelMeta []DeckGoChannelUiMeta `json:"channelMeta,omitempty"`
}

type DeckGoPluginInventoryEntry struct {
	Id string `json:"id"`
	Name string `json:"name,omitempty"`
	Version string `json:"version,omitempty"`
	Status string `json:"status,omitempty"`
	Origin string `json:"origin,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	ExplicitlyEnabled bool `json:"explicitlyEnabled,omitempty"`
	Activated bool `json:"activated,omitempty"`
	Imported bool `json:"imported,omitempty"`
	ActivationSource string `json:"activationSource,omitempty"`
	ActivationReason string `json:"activationReason,omitempty"`
	ConfigPath string `json:"configPath,omitempty"`
	CapabilityKinds []string `json:"capabilityKinds,omitempty"`
	ChannelIds []string `json:"channelIds,omitempty"`
	ProviderIds []string `json:"providerIds,omitempty"`
	ToolNames []string `json:"toolNames,omitempty"`
	DeckActionCapabilities DeckGoPluginActionCapabilities `json:"deckActionCapabilities,omitempty"`
	Diagnostics []DeckGoPluginDiagnostic `json:"diagnostics,omitempty"`
}

type DeckGoPluginActionCapabilities struct {
	Login bool `json:"login,omitempty"`
	Probe bool `json:"probe,omitempty"`
	TestMessage bool `json:"testMessage,omitempty"`
	QrCodeAuth bool `json:"qrCodeAuth,omitempty"`
}

type DeckGoPluginDiagnostic struct {
	Level string `json:"level"`
	Message string `json:"message"`
}

type DeckGoPluginsListResponse struct {
	Scope string `json:"scope,omitempty"`
	Plugins []DeckGoPluginInventoryEntry `json:"plugins,omitempty"`
}

type DeckGoSessionsListResponse struct {
	Sessions []DeckGoSessionMeta `json:"sessions,omitempty"`
}

type DeckGoServerEvent struct {
	Id string `json:"id,omitempty"`
	Event string `json:"event,omitempty"`
	Data string `json:"data,omitempty"`
	Json any `json:"json,omitempty"`
}

type DeckGoProjectionGapEvent struct {
	Reason string `json:"reason"`
}

type DeckGoLogStreamEvent struct {
	Id string `json:"id,omitempty"`
	Event string `json:"event,omitempty"`
	Data string `json:"data,omitempty"`
	Json any `json:"json,omitempty"`
}

type DeckGoSessionsPreviewResponse struct {
	Ts float64 `json:"ts,omitempty"`
	Previews []DeckGoSessionPreviewEntry `json:"previews,omitempty"`
}
