// Contract-shaped mock data for plugins prototype.
// Shapes match DeckGo* DTOs in deck-go/contracts/source/deck-api.contract.ts:
//   DeckGoPluginsListResponse, DeckGoPluginInventoryEntry,
//   DeckGoPluginActionCapabilities, DeckGoPluginDiagnostic,
//   DeckGoPluginCapability ("channel" | "all").
//
// Note: the Deck plugins API is read-only inventory — no install/uninstall,
// no marketplace, no signature verification. Anything that goes beyond raw
// inventory (manifest projection, activation timeline, audit) is a BFF
// projection over `plugins.list` outputs and config history. These are
// flagged in api-usage.md as "BFF projection" rather than raw Gateway data.

window.MOCK = {
  // ── DeckGoPluginsListResponse (capability=all, includes channel + tool + agent) ──
  inventoryAll: {
    scope: "workspace",
    plugins: [
      {
        id: "telegram-provider",
        name: "Telegram",
        version: "2.4.1",
        status: "ready",
        origin: "bundled",
        enabled: true,
        explicitlyEnabled: true,
        activated: true,
        imported: false,
        activationSource: "config",
        activationReason: "channel enabled in openclaw.json",
        configPath: "extensions/telegram-provider/config.json",
        capabilityKinds: ["channel", "provider"],
        channelIds: ["telegram"],
        providerIds: ["telegram-provider"],
        toolNames: [],
        deckActionCapabilities: { login: true, probe: true, testMessage: true, qrCodeAuth: false },
        diagnostics: [],
      },
      {
        id: "discord-provider",
        name: "Discord",
        version: "1.8.0",
        status: "degraded",
        origin: "bundled",
        enabled: true,
        explicitlyEnabled: true,
        activated: true,
        imported: false,
        activationSource: "config",
        activationReason: "channel enabled in openclaw.json",
        configPath: "extensions/discord-provider/config.json",
        capabilityKinds: ["channel", "provider"],
        channelIds: ["discord"],
        providerIds: ["discord-provider"],
        toolNames: [],
        deckActionCapabilities: { login: true, probe: true, testMessage: true, qrCodeAuth: false },
        diagnostics: [
          { level: "warn", message: "WebSocket reconnect threshold reached (3 of 10 attempts)" },
          { level: "info", message: "Gateway HELLO frame within tolerance" },
        ],
      },
      {
        id: "wecom-provider",
        name: "WeCom",
        version: "0.9.4",
        status: "ready",
        origin: "bundled",
        enabled: true,
        explicitlyEnabled: true,
        activated: true,
        imported: false,
        activationSource: "config",
        activationReason: "channel enabled in openclaw.json",
        configPath: "extensions/wecom-provider/config.json",
        capabilityKinds: ["channel", "provider", "tool"],
        channelIds: ["wecom"],
        providerIds: ["wecom-provider"],
        toolNames: ["wecom.message.broadcast", "wecom.tenant.lookup"],
        deckActionCapabilities: { login: true, probe: true, testMessage: false, qrCodeAuth: true },
        diagnostics: [],
      },
      {
        id: "slack-provider",
        name: "Slack",
        version: "1.2.0",
        status: "disabled",
        origin: "bundled",
        enabled: false,
        explicitlyEnabled: false,
        activated: false,
        imported: true,
        activationSource: "config",
        activationReason: "channel disabled in openclaw.json (manual override)",
        configPath: "extensions/slack-provider/config.json",
        capabilityKinds: ["channel", "provider"],
        channelIds: ["slack"],
        providerIds: ["slack-provider"],
        toolNames: [],
        deckActionCapabilities: {
          login: true,
          probe: false,
          testMessage: false,
          qrCodeAuth: false,
        },
        diagnostics: [{ level: "info", message: "plugin imported but channel.enabled=false" }],
      },
      {
        id: "signal-provider",
        name: "Signal",
        version: "0.6.0",
        status: "error",
        origin: "extension",
        enabled: true,
        explicitlyEnabled: true,
        activated: false,
        imported: true,
        activationSource: "extension",
        activationReason: "activation aborted: signal-cli runtime missing",
        configPath: "extensions/signal-provider/config.json",
        capabilityKinds: ["channel", "provider"],
        channelIds: ["signal"],
        providerIds: ["signal-provider"],
        toolNames: [],
        deckActionCapabilities: {
          login: false,
          probe: false,
          testMessage: false,
          qrCodeAuth: false,
        },
        diagnostics: [
          { level: "error", message: "signal-cli binary not found at $SIGNAL_CLI_PATH" },
          { level: "warn", message: "fallback to bundled JRE not yet implemented" },
        ],
      },
      {
        id: "github-tools",
        name: "GitHub Tools",
        version: "1.1.7",
        status: "ready",
        origin: "extension",
        enabled: true,
        explicitlyEnabled: true,
        activated: true,
        imported: false,
        activationSource: "extension",
        activationReason: "auto-activated by capability=tool",
        configPath: "extensions/github-tools/config.json",
        capabilityKinds: ["tool"],
        channelIds: [],
        providerIds: [],
        toolNames: [
          "github.issues.search",
          "github.issues.create",
          "github.pulls.list",
          "github.pulls.review",
          "github.repo.tree",
        ],
        deckActionCapabilities: { login: true, probe: true, testMessage: false, qrCodeAuth: false },
        diagnostics: [],
      },
      {
        id: "linear-tools",
        name: "Linear Tools",
        version: "0.4.2",
        status: "ready",
        origin: "extension",
        enabled: true,
        explicitlyEnabled: true,
        activated: true,
        imported: false,
        activationSource: "extension",
        activationReason: "auto-activated by capability=tool",
        configPath: "extensions/linear-tools/config.json",
        capabilityKinds: ["tool"],
        channelIds: [],
        providerIds: [],
        toolNames: ["linear.issue.search", "linear.issue.create", "linear.team.list"],
        deckActionCapabilities: {
          login: true,
          probe: false,
          testMessage: false,
          qrCodeAuth: false,
        },
        diagnostics: [],
      },
      {
        id: "openai-search",
        name: "OpenAI Search",
        version: "0.2.0",
        status: "ready",
        origin: "extension",
        enabled: true,
        explicitlyEnabled: true,
        activated: true,
        imported: false,
        activationSource: "extension",
        activationReason: "auto-activated by capability=tool",
        configPath: "extensions/openai-search/config.json",
        capabilityKinds: ["tool"],
        channelIds: [],
        providerIds: [],
        toolNames: ["web.search", "web.fetch"],
        deckActionCapabilities: {
          login: false,
          probe: true,
          testMessage: false,
          qrCodeAuth: false,
        },
        diagnostics: [],
      },
      {
        id: "filesystem-agent",
        name: "Filesystem Agent",
        version: "1.0.0",
        status: "ready",
        origin: "extension",
        enabled: true,
        explicitlyEnabled: false,
        activated: true,
        imported: false,
        activationSource: "implicit",
        activationReason: "implicit activation: agent.fs is a default capability",
        configPath: "extensions/filesystem-agent/config.json",
        capabilityKinds: ["tool", "agent"],
        channelIds: [],
        providerIds: [],
        toolNames: ["fs.read", "fs.write", "fs.glob", "fs.grep", "fs.diff"],
        deckActionCapabilities: {
          login: false,
          probe: false,
          testMessage: false,
          qrCodeAuth: false,
        },
        diagnostics: [],
      },
      {
        id: "web-runtime",
        name: "Web Runtime",
        version: "0.7.3",
        status: "pending",
        origin: "extension",
        enabled: true,
        explicitlyEnabled: true,
        activated: false,
        imported: true,
        activationSource: "extension",
        activationReason: "awaiting Playwright kernel handshake",
        configPath: "extensions/web-runtime/config.json",
        capabilityKinds: ["tool"],
        channelIds: [],
        providerIds: [],
        toolNames: ["web.navigate", "web.snapshot", "web.click"],
        deckActionCapabilities: {
          login: false,
          probe: true,
          testMessage: false,
          qrCodeAuth: false,
        },
        diagnostics: [
          { level: "info", message: "Playwright server starting on :48091" },
          { level: "warn", message: "Chromium build slower than 2s threshold (4.1s)" },
        ],
      },
      {
        id: "qq-provider",
        name: "QQ",
        version: "0.5.0",
        status: "ready",
        origin: "bundled",
        enabled: true,
        explicitlyEnabled: true,
        activated: false,
        imported: true,
        activationSource: "config",
        activationReason: "no QQ accounts configured",
        configPath: "extensions/qq-provider/config.json",
        capabilityKinds: ["channel", "provider"],
        channelIds: ["qq"],
        providerIds: ["qq-provider"],
        toolNames: [],
        deckActionCapabilities: { login: true, probe: true, testMessage: false, qrCodeAuth: true },
        diagnostics: [{ level: "info", message: "channel pinned in config but no accounts bound" }],
      },
      {
        id: "anthropic-cache",
        name: "Anthropic Prompt Cache",
        version: "0.3.0",
        status: "ready",
        origin: "extension",
        enabled: true,
        explicitlyEnabled: false,
        activated: true,
        imported: false,
        activationSource: "implicit",
        activationReason: "implicit activation: prompt cache is a runtime capability",
        configPath: null,
        capabilityKinds: ["tool"],
        channelIds: [],
        providerIds: [],
        toolNames: ["cache.get", "cache.put"],
        deckActionCapabilities: {
          login: false,
          probe: true,
          testMessage: false,
          qrCodeAuth: false,
        },
        diagnostics: [],
      },
    ],
  },

  // ── DeckGoPluginsListResponse (capability=channel, the default Deck call) ──
  // Subset of inventoryAll where capabilityKinds includes "channel".
  // Frontend usually drives the channel routing screens from this slice.
  inventoryChannel: null, // computed below from inventoryAll

  // ── BFF projection: synthetic manifest preview ────────────────────────
  // The Deck inventory API does not surface raw plugin manifests. BFF
  // projects a manifest from `plugins.list` + `gateway.describe` outputs
  // for the workbench UI. Only the fields below are guaranteed to be
  // backend-derivable; richer fields are heuristics flagged in api-usage.md.
  manifests: {
    "discord-provider": {
      id: "discord-provider",
      name: "Discord",
      version: "1.8.0",
      author: "openclaw",
      origin: "bundled",
      capabilityKinds: ["channel", "provider"],
      channelIds: ["discord"],
      providerIds: ["discord-provider"],
      toolNames: [],
      configSchema: {
        $ref: "extensions/discord-provider/config-schema.json",
        version: "1.0",
      },
      runtime: {
        node: ">=22.14.0",
        bin: "extensions/discord-provider/dist/index.cjs",
      },
      deckActions: { login: true, probe: true, testMessage: true, qrCodeAuth: false },
      permissions: ["network.outbound", "process.spawn:none", "fs.read:config", "secret.read"],
    },
    "github-tools": {
      id: "github-tools",
      name: "GitHub Tools",
      version: "1.1.7",
      author: "openclaw",
      origin: "extension",
      capabilityKinds: ["tool"],
      channelIds: [],
      providerIds: [],
      toolNames: [
        "github.issues.search",
        "github.issues.create",
        "github.pulls.list",
        "github.pulls.review",
        "github.repo.tree",
      ],
      configSchema: {
        $ref: "extensions/github-tools/config-schema.json",
        version: "1.0",
      },
      runtime: {
        node: ">=22.14.0",
        bin: "extensions/github-tools/dist/index.cjs",
      },
      deckActions: { login: true, probe: true, testMessage: false, qrCodeAuth: false },
      permissions: ["network.outbound:api.github.com", "secret.read:GITHUB_TOKEN"],
    },
  },

  // ── BFF projection: activation timeline (audit history per plugin) ────
  // Synthetic per-plugin event series. BFF derives this from config history
  // + `plugins.list` snapshots. Not part of the plugin inventory contract.
  activationTimeline: {
    "discord-provider": [
      {
        ts: 1714680000000 - 5 * 60 * 60 * 1000,
        actor: "system",
        event: "imported",
        note: "loaded from extensions/discord-provider/manifest.json",
      },
      {
        ts: 1714680000000 - 4 * 60 * 60 * 1000,
        actor: "system",
        event: "activated",
        note: "channel enabled in openclaw.json",
      },
      {
        ts: 1714680000000 - 30 * 60 * 1000,
        actor: "system",
        event: "diagnostic",
        note: "warn: WebSocket reconnect threshold reached",
      },
      {
        ts: 1714680000000 - 18 * 60 * 1000,
        actor: "system",
        event: "diagnostic",
        note: "info: Gateway HELLO frame within tolerance",
      },
    ],
    "signal-provider": [
      {
        ts: 1714680000000 - 6 * 60 * 60 * 1000,
        actor: "wangym",
        event: "imported",
        note: "added via openclaw.json plugins.entries",
      },
      {
        ts: 1714680000000 - 6 * 60 * 60 * 1000 + 200,
        actor: "system",
        event: "error",
        note: "activation aborted: signal-cli runtime missing",
      },
      {
        ts: 1714680000000 - 90 * 60 * 1000,
        actor: "wangym",
        event: "config-edit",
        note: "set SIGNAL_CLI_PATH=/usr/local/bin/signal-cli",
      },
      {
        ts: 1714680000000 - 90 * 60 * 1000 + 200,
        actor: "system",
        event: "error",
        note: "still cannot resolve signal-cli runtime",
      },
    ],
    "github-tools": [
      {
        ts: 1714680000000 - 24 * 60 * 60 * 1000,
        actor: "system",
        event: "imported",
        note: "extension auto-discovered",
      },
      {
        ts: 1714680000000 - 24 * 60 * 60 * 1000 + 400,
        actor: "system",
        event: "activated",
        note: "auto-activated by capability=tool",
      },
      {
        ts: 1714680000000 - 12 * 60 * 60 * 1000,
        actor: "wangym",
        event: "config-edit",
        note: "rotated GITHUB_TOKEN",
      },
    ],
  },

  // KPI tiles for the list-view header strip.
  kpis: {
    asOfMs: 1714680000000,
    runtimeId: "deck-runtime-prod-01",
  },
};

// Compute channel-capable subset (matches capability=channel default call).
window.MOCK.inventoryChannel = {
  scope: window.MOCK.inventoryAll.scope,
  plugins: window.MOCK.inventoryAll.plugins.filter(
    (p) => Array.isArray(p.capabilityKinds) && p.capabilityKinds.includes("channel"),
  ),
};
