// Nodes module fixtures.
// All shapes mirror DeckGo* DTOs from deck-go/contracts/source/deck-api.contract.ts:1546-1620.

window.NODES = [
  {
    nodeId: "node-alpha",
    displayName: "Alpha Control Mac",
    platform: "darwin",
    version: "2.1.0",
    coreVersion: "2.1.0",
    uiVersion: "2.1.0",
    deviceFamily: "mac",
    modelIdentifier: "Mac15,9",
    remoteIp: "10.20.0.31",
    caps: ["chat", "system.notify", "shell", "fs.read", "fs.write"],
    commands: ["chat.send", "system.notify", "status.request"],
    pathEnv: "/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin",
    permissions: { shell: true, fs: true, network: true, "fs.write": true },
    connectedAtMs: Date.now() - 5 * 60_000,
    paired: true,
    connected: true,
  },
  {
    nodeId: "node-beta",
    displayName: "Beta Field Node",
    platform: "linux",
    version: "2.1.0",
    coreVersion: "2.0.4",
    uiVersion: "2.1.0",
    deviceFamily: "linux-arm64",
    modelIdentifier: "Raspberry Pi 5",
    remoteIp: "10.20.0.42",
    caps: ["status.request", "location.request"],
    commands: ["status.request"],
    pathEnv: "/usr/local/bin:/usr/bin:/bin",
    permissions: { shell: false, fs: true, network: true },
    connectedAtMs: Date.now() - 6 * 60 * 60_000,
    paired: false,
    connected: false,
  },
  {
    nodeId: "node-ops-tablet",
    displayName: "Ops Tablet",
    platform: "android",
    version: "2.1.0",
    coreVersion: "2.1.0",
    uiVersion: "2.1.0",
    deviceFamily: "android-tablet",
    modelIdentifier: "Pixel Tablet",
    remoteIp: "10.20.0.55",
    caps: ["chat", "system.notify", "location.request"],
    commands: ["chat.send", "system.notify"],
    permissions: { shell: false, fs: false, network: true },
    connectedAtMs: Date.now() - 12 * 60_000,
    paired: true,
    connected: true,
  },
  {
    nodeId: "node-gamma",
    displayName: "Gamma Workstation",
    platform: "windows",
    version: "2.0.9",
    coreVersion: "2.0.9",
    uiVersion: "2.0.9",
    deviceFamily: "windows-x64",
    modelIdentifier: "OptiPlex 7090",
    remoteIp: "10.20.0.77",
    caps: ["chat", "system.notify", "shell"],
    commands: ["chat.send", "system.notify", "status.request"],
    pathEnv: "C:\\Windows\\System32;C:\\Program Files\\OpenClaw",
    permissions: { shell: true, fs: true, network: true },
    connectedAtMs: Date.now() - 2 * 60_000,
    paired: true,
    connected: true,
  },
  {
    nodeId: "node-delta",
    displayName: "Delta Edge Probe",
    platform: "linux",
    version: "2.0.7",
    coreVersion: "2.0.7",
    uiVersion: "2.0.7",
    deviceFamily: "linux-x64",
    modelIdentifier: "Intel NUC 12",
    remoteIp: "10.20.0.91",
    caps: ["status.request"],
    commands: [],
    permissions: { shell: false, fs: false, network: true },
    paired: true,
    connected: false,
  },
];

window.PAIRING_REQUESTS = [
  {
    requestId: "pair-beta-repair",
    nodeId: "node-beta",
    displayName: "Beta Field Node",
    platform: "linux",
    silent: false,
    isRepair: true,
    ts: Date.now() - 4 * 60_000,
  },
  {
    requestId: "pair-orphan-omega",
    nodeId: "node-omega",
    displayName: "Omega Spare Laptop",
    platform: "darwin",
    silent: false,
    isRepair: false,
    ts: Date.now() - 18 * 60_000,
  },
];

// Mock command params templates per command id (drives the JSON textarea seed).
window.COMMAND_TEMPLATES = {
  "chat.send": '{ "channelId": "telegram-ops", "text": "Status check" }',
  "system.notify": '{ "title": "Probe", "message": "Run mock visual probe" }',
  "status.request": '{ "fields": ["uptime", "load", "battery"] }',
};

// Mock action results — used by the right pane after a confirm-gated action.
window.ACTION_FIXTURES = {
  rename: (nodeId, name) => ({
    ok: true,
    nodeId,
    command: "node.rename",
    payload: { displayName: name },
    payloadJSON: JSON.stringify({ displayName: name }),
  }),
  invoke: (nodeId, command, params) => ({
    ok: true,
    nodeId,
    command,
    payload: { ...params, dispatchedAtMs: Date.now() },
    payloadJSON: JSON.stringify({ ...params, dispatchedAtMs: Date.now() }, null, 2),
  }),
  pendingEnqueue: (nodeId, type, priority, wake) => ({
    nodeId,
    revision: 7,
    queued: { type, priority, wake },
    wakeTriggered: !!wake,
  }),
  pairRequest: (input) => ({
    status: "queued",
    request: {
      requestId: `pair-${input.nodeId}-${Date.now()}`,
      nodeId: input.nodeId,
      displayName: input.displayName,
      platform: input.platform,
      silent: !!input.silent,
      isRepair: false,
      ts: Date.now(),
    },
    created: true,
  }),
  pairApprove: (requestId) => ({
    status: "approved",
    request: { requestId },
    created: false,
  }),
  pairReject: (requestId) => ({
    status: "rejected",
    request: { requestId },
    created: false,
  }),
  pairVerify: (nodeId, token) => ({
    status: token.length >= 6 ? "verified" : "invalid",
    request: { nodeId, requestId: `verify-${nodeId}` },
    created: false,
  }),
};
