// Contract-shaped mock data for subagents prototype.
// Shapes match DeckGo* DTOs in deck-go/contracts/source/deck-api.contract.ts:
//   DeckGoSubagentRun, DeckGoSubagentsListResponse,
//   DeckGoSubagentLineageRoot, DeckGoSubagentLineageNode,
//   DeckGoSubagentsLineageResponse, DeckGoSubagentKillResponse,
//   DeckGoSubagentSteerResponse,
//   DeckGoAgentSubagentConfigResponse,
//   DeckGoAgentSubagentPermissionOption,
//   DeckGoAgentSubagentConfigSetResponse.
//
// Subagents domain has two concerns layered together:
//   1. Runs / lifecycle (operational live view) — `subagents.list`, kill, steer
//   2. Permission config (per-agent allow lists) — `agents.subagent-config`
// The panel surfaces both via a list mode toggle (runs | permissions).

const NOW = 1714680000000;

window.MOCK = {
  // ── DeckGoSubagentsListResponse — runs ──────────────────────────────
  runs: {
    total: 14,
    runs: [
      {
        runId: "run_aa3201",
        childSessionKey: "sess_aa3201",
        childAgentId: "executor",
        childAgentName: "Executor",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Implement TabAudit error handling in subagents detail view",
        label: "subagents tab audit",
        model: "claude-sonnet-4-6",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 6 * 60 * 1000,
        startedAt: NOW - 6 * 60 * 1000 + 800,
        endedAt: NOW - 4 * 60 * 1000,
        durationMs: 124000,
        status: "succeeded",
        outcome: { ok: true, filesTouched: ["detail-view.jsx", "styles.css"] },
      },
      {
        runId: "run_bb7401",
        childSessionKey: "sess_bb7401",
        childAgentId: "architect",
        childAgentName: "Architect",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Verify ralph completion against PRD acceptance criteria",
        label: "ralph step 7 verification",
        model: "claude-opus-4-7",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 90 * 1000,
        startedAt: NOW - 90 * 1000 + 600,
        endedAt: undefined,
        durationMs: undefined,
        status: "running",
        outcome: undefined,
      },
      {
        runId: "run_cc9101",
        childSessionKey: "sess_cc9101",
        childAgentId: "explore",
        childAgentName: "Explore",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Find DeckGoSubagent* DTOs in contract source",
        label: "contract DTO grep",
        model: "claude-haiku-4-5-20251001",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 12 * 60 * 1000,
        startedAt: NOW - 12 * 60 * 1000 + 400,
        endedAt: NOW - 11 * 60 * 1000 - 30 * 1000,
        durationMs: 30000,
        status: "succeeded",
        outcome: { ok: true, hits: 14 },
      },
      {
        runId: "run_dd5512",
        childSessionKey: "sess_dd5512",
        childAgentId: "executor",
        childAgentName: "Executor",
        requesterSessionKey: "sess_aa3201",
        requesterAgentId: "executor",
        requesterAgentName: "Executor (sub)",
        task: "Run pnpm tsc --noEmit on dirty files",
        label: "type check sub",
        model: "claude-sonnet-4-6",
        spawnMode: "blocking",
        depth: 2,
        createdAt: NOW - 5 * 60 * 1000,
        startedAt: NOW - 5 * 60 * 1000 + 200,
        endedAt: NOW - 5 * 60 * 1000 + 9 * 1000,
        durationMs: 9000,
        status: "succeeded",
        outcome: { ok: true, errors: 0, warnings: 4 },
      },
      {
        runId: "run_ee2231",
        childSessionKey: "sess_ee2231",
        childAgentId: "critic",
        childAgentName: "Critic",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Review channels prototype v2 for adherence to design system",
        label: "channels review",
        model: "claude-opus-4-7",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 25 * 60 * 1000,
        startedAt: NOW - 25 * 60 * 1000 + 1200,
        endedAt: NOW - 22 * 60 * 1000,
        durationMs: 180000,
        status: "succeeded",
        outcome: { verdict: "APPROVE", issues: 0 },
      },
      {
        runId: "run_ff8801",
        childSessionKey: "sess_ff8801",
        childAgentId: "executor",
        childAgentName: "Executor",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Migrate test fixtures from sql.js to JSON",
        label: "fixtures migration",
        model: "claude-opus-4-7",
        spawnMode: "background",
        depth: 1,
        createdAt: NOW - 50 * 60 * 1000,
        startedAt: NOW - 50 * 60 * 1000 + 600,
        endedAt: NOW - 38 * 60 * 1000,
        durationMs: 720000,
        status: "succeeded",
        outcome: { ok: true, filesTouched: 47 },
      },
      {
        runId: "run_gg1010",
        childSessionKey: "sess_gg1010",
        childAgentId: "verifier",
        childAgentName: "Verifier",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Verify completed sql.js migration against acceptance criteria",
        label: "post-migration verify",
        model: "claude-sonnet-4-6",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 36 * 60 * 1000,
        startedAt: NOW - 36 * 60 * 1000 + 200,
        endedAt: NOW - 35 * 60 * 1000,
        durationMs: 60000,
        status: "succeeded",
        outcome: { verdict: "PASS" },
      },
      {
        runId: "run_hh4422",
        childSessionKey: "sess_hh4422",
        childAgentId: "executor",
        childAgentName: "Executor",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Refactor wecom plugin pending-reply queue with bounded retry",
        label: "wecom retry hardening",
        model: "claude-opus-4-7",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 200 * 60 * 1000,
        startedAt: NOW - 200 * 60 * 1000 + 800,
        endedAt: NOW - 198 * 60 * 1000,
        durationMs: 100000,
        status: "killed",
        outcome: { reason: "user-requested kill" },
      },
      {
        runId: "run_ii7733",
        childSessionKey: "sess_ii7733",
        childAgentId: "scientist",
        childAgentName: "Scientist",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Analyze cache hit rate after prompt cache changes",
        label: "cache hit analysis",
        model: "claude-haiku-4-5-20251001",
        spawnMode: "background",
        depth: 1,
        createdAt: NOW - 75 * 60 * 1000,
        startedAt: NOW - 75 * 60 * 1000 + 300,
        endedAt: NOW - 70 * 60 * 1000,
        durationMs: 300000,
        status: "succeeded",
        outcome: { hitRate: 0.84, sample: 1240 },
      },
      {
        runId: "run_jj9101",
        childSessionKey: "sess_jj9101",
        childAgentId: "executor",
        childAgentName: "Executor",
        requesterSessionKey: "sess_aa3201",
        requesterAgentId: "executor",
        requesterAgentName: "Executor (sub)",
        task: "Update components.md with new prop shapes",
        label: "docs sub",
        model: "claude-sonnet-4-6",
        spawnMode: "blocking",
        depth: 2,
        createdAt: NOW - 4 * 60 * 1000,
        startedAt: NOW - 4 * 60 * 1000 + 200,
        endedAt: NOW - 3 * 60 * 1000 - 40 * 1000,
        durationMs: 20000,
        status: "succeeded",
        outcome: { ok: true },
      },
      {
        runId: "run_kk2222",
        childSessionKey: "sess_kk2222",
        childAgentId: "test-engineer",
        childAgentName: "Test Engineer",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Add e2e Playwright spec for skills install flow",
        label: "skills e2e",
        model: "claude-sonnet-4-6",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 15 * 60 * 1000,
        startedAt: NOW - 15 * 60 * 1000 + 200,
        endedAt: undefined,
        durationMs: undefined,
        status: "running",
        outcome: undefined,
      },
      {
        runId: "run_ll5555",
        childSessionKey: "sess_ll5555",
        childAgentId: "executor",
        childAgentName: "Executor",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Patch Discord HELLO timeout flake in CI",
        label: "discord ci flake",
        model: "claude-opus-4-7",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 9 * 60 * 60 * 1000,
        startedAt: NOW - 9 * 60 * 60 * 1000 + 400,
        endedAt: NOW - 9 * 60 * 60 * 1000 + 14 * 60 * 1000,
        durationMs: 840000,
        status: "failed",
        outcome: { error: "tsc failed: 23 errors" },
      },
      {
        runId: "run_mm6611",
        childSessionKey: "sess_mm6611",
        childAgentId: "writer",
        childAgentName: "Writer",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Draft RELEASE_NOTES for 0.4.2 against the closed PRs",
        label: "release notes",
        model: "claude-haiku-4-5-20251001",
        spawnMode: "background",
        depth: 1,
        createdAt: NOW - 2 * 60 * 60 * 1000,
        startedAt: NOW - 2 * 60 * 60 * 1000 + 200,
        endedAt: NOW - 2 * 60 * 60 * 1000 + 4 * 60 * 1000,
        durationMs: 240000,
        status: "succeeded",
        outcome: { ok: true, drafted: "RELEASE_NOTES_v0.4.2.md" },
      },
      {
        runId: "run_nn7700",
        childSessionKey: "sess_nn7700",
        childAgentId: "tracer",
        childAgentName: "Tracer",
        requesterSessionKey: "sess_main_001",
        requesterAgentId: "main",
        requesterAgentName: "Main",
        task: "Trace cache miss in fetchSkills",
        label: "trace skills cache",
        model: "claude-opus-4-7",
        spawnMode: "blocking",
        depth: 1,
        createdAt: NOW - 8 * 60 * 1000,
        startedAt: NOW - 8 * 60 * 1000 + 200,
        endedAt: undefined,
        durationMs: undefined,
        status: "stalled",
        outcome: undefined,
      },
    ],
  },

  // ── DeckGoSubagentsLineageResponse — keyed by root sessionKey ─────────
  // Captures the parent-child tree rooted at a session.
  lineage: {
    sess_main_001: {
      root: { sessionKey: "sess_main_001", agentId: "main", agentName: "Main" },
      nodes: [
        {
          runId: "run_aa3201",
          sessionKey: "sess_aa3201",
          agentId: "executor",
          agentName: "Executor",
          task: "Implement TabAudit error handling in subagents detail view",
          depth: 1,
          parentRunId: "",
          status: "succeeded",
          durationMs: 124000,
        },
        {
          runId: "run_dd5512",
          sessionKey: "sess_dd5512",
          agentId: "executor",
          agentName: "Executor",
          task: "Run pnpm tsc --noEmit on dirty files",
          depth: 2,
          parentRunId: "run_aa3201",
          status: "succeeded",
          durationMs: 9000,
        },
        {
          runId: "run_jj9101",
          sessionKey: "sess_jj9101",
          agentId: "executor",
          agentName: "Executor",
          task: "Update components.md with new prop shapes",
          depth: 2,
          parentRunId: "run_aa3201",
          status: "succeeded",
          durationMs: 20000,
        },
        {
          runId: "run_bb7401",
          sessionKey: "sess_bb7401",
          agentId: "architect",
          agentName: "Architect",
          task: "Verify ralph completion against PRD acceptance criteria",
          depth: 1,
          parentRunId: "",
          status: "running",
          durationMs: undefined,
        },
        {
          runId: "run_kk2222",
          sessionKey: "sess_kk2222",
          agentId: "test-engineer",
          agentName: "Test Engineer",
          task: "Add e2e Playwright spec for skills install flow",
          depth: 1,
          parentRunId: "",
          status: "running",
          durationMs: undefined,
        },
      ],
    },
  },

  // ── DeckGoAgentSubagentConfigResponse — keyed by parent agentId ───────
  agentConfig: {
    main: {
      agentId: "main",
      allowAgents: ["executor", "explore", "architect", "verifier", "critic", "writer"],
      allowAny: false,
      model: "claude-opus-4-7",
      effectiveMaxSpawnDepth: 4,
      effectiveMaxChildrenPerAgent: 8,
      effectiveThinking: { mode: "enabled", maxBudget: 28000 },
      configHash: "h_main_001",
    },
    executor: {
      agentId: "executor",
      allowAgents: ["executor"],
      allowAny: false,
      model: "claude-sonnet-4-6",
      effectiveMaxSpawnDepth: 2,
      effectiveMaxChildrenPerAgent: 3,
      effectiveThinking: { mode: "auto", maxBudget: 8000 },
      configHash: "h_exec_001",
    },
    architect: {
      agentId: "architect",
      allowAgents: [],
      allowAny: false,
      model: "claude-opus-4-7",
      effectiveMaxSpawnDepth: 0,
      effectiveMaxChildrenPerAgent: 0,
      effectiveThinking: { mode: "enabled", maxBudget: 60000 },
      configHash: "h_arch_001",
    },
  },

  // Universe of agents (used both for permission checkboxes and lineage rendering).
  allAgents: [
    { id: "main", name: "Main" },
    { id: "executor", name: "Executor" },
    { id: "explore", name: "Explore" },
    { id: "architect", name: "Architect" },
    { id: "critic", name: "Critic" },
    { id: "verifier", name: "Verifier" },
    { id: "test-engineer", name: "Test Engineer" },
    { id: "scientist", name: "Scientist" },
    { id: "tracer", name: "Tracer" },
    { id: "writer", name: "Writer" },
    { id: "designer", name: "Designer" },
    { id: "qa-tester", name: "QA Tester" },
  ],

  // ── BFF projection: per-run audit (kill / steer / status transitions) ──
  audit: {
    run_hh4422: [
      {
        ts: NOW - 200 * 60 * 1000,
        actor: "system",
        event: "spawned",
        note: "spawnMode=blocking depth=1",
      },
      {
        ts: NOW - 200 * 60 * 1000 + 800,
        actor: "system",
        event: "started",
        note: "child session sess_hh4422 attached",
      },
      {
        ts: NOW - 199 * 60 * 1000,
        actor: "wangym",
        event: "steer",
        note: "Inject hint: 'use bounded retry, not infinite loop'",
      },
      {
        ts: NOW - 198 * 60 * 1000,
        actor: "wangym",
        event: "kill",
        note: "user-requested kill — child took unexpected path",
      },
      {
        ts: NOW - 198 * 60 * 1000 + 50,
        actor: "system",
        event: "ended",
        note: "status=killed",
      },
    ],
    run_ll5555: [
      {
        ts: NOW - 9 * 60 * 60 * 1000,
        actor: "system",
        event: "spawned",
        note: "spawnMode=blocking depth=1",
      },
      {
        ts: NOW - 9 * 60 * 60 * 1000 + 14 * 60 * 1000,
        actor: "system",
        event: "ended",
        note: "status=failed (tsc errors)",
      },
    ],
    run_bb7401: [
      {
        ts: NOW - 90 * 1000,
        actor: "system",
        event: "spawned",
        note: "spawnMode=blocking depth=1",
      },
      {
        ts: NOW - 90 * 1000 + 600,
        actor: "system",
        event: "started",
        note: "child session sess_bb7401 attached",
      },
    ],
  },

  kpis: {
    asOfMs: NOW,
    runtimeId: "deck-runtime-prod-01",
  },
};
