// Auto-generated by scripts/protocol-gen-ts.ts — DO NOT EDIT

import type { GatewayMethodMap, GatewayMethodName } from "./gateway-protocol.generated";

export type GatewayRequestFn = <M extends GatewayMethodName>(
  method: M,
  params: GatewayMethodMap[M]["params"],
  options?: { timeoutMs?: number },
) => Promise<GatewayMethodMap[M]["result"]>;

export const GENERATED_METHOD_ALLOWLIST: ReadonlySet<string> = new Set([
  "agent.identity.get",
  "agent.wait",
  "agents.create",
  "agents.delete",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "agents.list",
  "agents.update",
  "channels.logout",
  "channels.status",
  "chat.abort",
  "chat.history",
  "chat.send",
  "commands.list",
  "config.apply",
  "config.get",
  "config.patch",
  "config.schema",
  "config.schema.lookup",
  "config.set",
  "cron.add",
  "cron.list",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "cron.status",
  "cron.update",
  "deck.agents.detail",
  "deck.agents.eventStreams.get",
  "deck.agents.eventStreams.set",
  "deck.agents.skills.get",
  "deck.agents.skills.set",
  "deck.agents.subagents.get",
  "deck.agents.subagents.set",
  "deck.agents.systemPrompt.preview",
  "deck.agents.toolPolicy.preview",
  "deck.auth.overview",
  "deck.auth.probe",
  "deck.commands.discover",
  "deck.identity.link",
  "deck.identity.list",
  "deck.identity.unlink",
  "deck.routing.add",
  "deck.routing.list",
  "deck.routing.remove",
  "deck.routing.simulate",
  "deck.routing.validate",
  "deck.subagents.kill",
  "deck.subagents.lineage",
  "deck.subagents.list",
  "deck.subagents.steer",
  "deck.threads.list",
  "device.pair.approve",
  "device.pair.list",
  "device.pair.reject",
  "device.pair.remove",
  "device.token.revoke",
  "device.token.rotate",
  "doctor.memory.backfillDreamDiary",
  "doctor.memory.dedupeDreamDiary",
  "doctor.memory.dreamDiary",
  "doctor.memory.repairDreamingArtifacts",
  "doctor.memory.resetDreamDiary",
  "doctor.memory.resetGroundedShortTerm",
  "doctor.memory.status",
  "exec.approval.request",
  "exec.approval.resolve",
  "exec.approval.waitDecision",
  "exec.approvals.get",
  "exec.approvals.node.get",
  "exec.approvals.node.set",
  "exec.approvals.set",
  "gateway.describe",
  "health",
  "logs.tail",
  "models.catalog.providers",
  "models.configured",
  "models.list",
  "node.describe",
  "node.list",
  "node.pair.approve",
  "node.pair.list",
  "node.pair.reject",
  "node.pair.request",
  "node.pair.verify",
  "node.rename",
  "plugin.approval.list",
  "plugin.approval.request",
  "plugin.approval.resolve",
  "plugin.approval.waitDecision",
  "sessions.abort",
  "sessions.clear",
  "sessions.compact",
  "sessions.compaction.branch",
  "sessions.compaction.get",
  "sessions.compaction.list",
  "sessions.compaction.restore",
  "sessions.create",
  "sessions.delete",
  "sessions.get",
  "sessions.list",
  "sessions.messages.subscribe",
  "sessions.messages.unsubscribe",
  "sessions.patch",
  "sessions.preview",
  "sessions.reset",
  "sessions.send",
  "sessions.steer",
  "sessions.subscribe",
  "sessions.unsubscribe",
  "sessions.usage",
  "sessions.usage.logs",
  "sessions.usage.timeseries",
  "skills.bins",
  "skills.detail",
  "skills.install",
  "skills.search",
  "skills.status",
  "skills.update",
  "status",
  "talk.config",
  "talk.mode",
  "talk.speak",
  "tools.catalog",
  "tools.effective",
  "usage.cost",
  "usage.status",
  "wizard.cancel",
  "wizard.next",
  "wizard.start",
  "wizard.status",
]);

export const GENERATED_EVENT_NAMES: ReadonlySet<string> = new Set([
  "agent",
  "chat",
  "connect.challenge",
  "cron",
  "device.pair.requested",
  "device.pair.resolved",
  "exec.approval.requested",
  "exec.approval.resolved",
  "health",
  "heartbeat",
  "node.invoke.request",
  "node.pair.requested",
  "node.pair.resolved",
  "plugin.approval.requested",
  "plugin.approval.resolved",
  "presence",
  "session.message",
  "session.tool",
  "sessions.changed",
  "shutdown",
  "talk.mode",
  "tick",
  "update.available",
  "voicewake.changed",
]);

export const GENERATED_TYPED_EVENT_NAMES: ReadonlySet<string> = new Set([
  "agent",
  "chat",
  "session.message",
  "session.tool",
  "sessions.changed",
]);

export interface GatewayClient {
  chat: {
    history(
      params: import("./gateway-protocol.generated").ChatHistoryParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ChatHistoryResult>;
    abort(
      params: import("./gateway-protocol.generated").ChatAbortParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ChatAbortResult>;
    send(
      params: import("./gateway-protocol.generated").ChatSendParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ChatSendResult>;
  };
  config: {
    get(
      params: import("./gateway-protocol.generated").ConfigGetParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ConfigGetResult>;
    schema: {
      $call(
        params: import("./gateway-protocol.generated").ConfigSchemaParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ConfigSchemaResult>;
      lookup(
        params: import("./gateway-protocol.generated").ConfigSchemaLookupParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ConfigSchemaLookupResult>;
    };
    apply(
      params: import("./gateway-protocol.generated").ConfigApplyParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ConfigApplyResult>;
    patch(
      params: import("./gateway-protocol.generated").ConfigPatchParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ConfigPatchResult>;
    set(
      params: import("./gateway-protocol.generated").ConfigSetParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ConfigSetResult>;
  };
  doctor: {
    memory: {
      status(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DoctorMemoryStatusResult>;
      dreamDiary(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DoctorMemoryDreamDiaryResult>;
      backfillDreamDiary(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DoctorMemoryBackfillDreamDiaryResult>;
      resetDreamDiary(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DoctorMemoryResetDreamDiaryResult>;
      resetGroundedShortTerm(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DoctorMemoryResetGroundedShortTermResult>;
      repairDreamingArtifacts(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DoctorMemoryRepairDreamingArtifactsResult>;
      dedupeDreamDiary(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DoctorMemoryDedupeDreamDiaryResult>;
    };
  };
  health(
    params: Record<string, unknown>,
    options?: { timeoutMs?: number },
  ): Promise<import("./gateway-protocol.generated").HealthResult>;
  status(
    params: Record<string, unknown>,
    options?: { timeoutMs?: number },
  ): Promise<import("./gateway-protocol.generated").StatusResult>;
  usage: {
    status(
      params: Record<string, unknown>,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").UsageStatusResult>;
    cost(
      params: Record<string, unknown>,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").UsageCostResult>;
  };
  models: {
    catalog: {
      providers(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ModelsCatalogProvidersResult>;
    };
    list(
      params: import("./gateway-protocol.generated").ModelsListParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ModelsListResult>;
    configured(
      params: import("./gateway-protocol.generated").ModelsConfiguredParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ModelsConfiguredResult>;
  };
  skills: {
    status(
      params: import("./gateway-protocol.generated").SkillsStatusParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SkillsStatusResult>;
    bins(
      params: import("./gateway-protocol.generated").SkillsBinsParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SkillsBinsResult>;
    install(
      params: import("./gateway-protocol.generated").SkillsInstallParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SkillsInstallResult>;
    update(
      params: import("./gateway-protocol.generated").SkillsUpdateParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SkillsUpdateResult>;
    search(
      params: import("./gateway-protocol.generated").SkillsSearchParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SkillsSearchResult>;
    detail(
      params: import("./gateway-protocol.generated").SkillsDetailParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SkillsDetailResult>;
  };
  cron: {
    list(
      params: import("./gateway-protocol.generated").CronListParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CronListResult>;
    status(
      params: import("./gateway-protocol.generated").CronStatusParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CronStatusResult>;
    add(
      params: import("./gateway-protocol.generated").CronAddParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CronAddResult>;
    update(
      params: import("./gateway-protocol.generated").CronUpdateParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CronUpdateResult>;
    remove(
      params: import("./gateway-protocol.generated").CronRemoveParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CronRemoveResult>;
    run(
      params: import("./gateway-protocol.generated").CronRunParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CronRunResult>;
    runs(
      params: import("./gateway-protocol.generated").CronRunsParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CronRunsResult>;
  };
  exec: {
    approvals: {
      get(
        params: import("./gateway-protocol.generated").ExecApprovalsGetParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ExecApprovalsGetResult>;
      set(
        params: import("./gateway-protocol.generated").ExecApprovalsSetParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ExecApprovalsSetResult>;
      node: {
        get(
          params: import("./gateway-protocol.generated").ExecApprovalsNodeGetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").ExecApprovalsNodeGetResult>;
        set(
          params: import("./gateway-protocol.generated").ExecApprovalsNodeSetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").ExecApprovalsNodeSetResult>;
      };
    };
    approval: {
      request(
        params: import("./gateway-protocol.generated").ExecApprovalRequestParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ExecApprovalRequestResult>;
      resolve(
        params: import("./gateway-protocol.generated").ExecApprovalResolveParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ExecApprovalResolveResult>;
      waitDecision(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").ExecApprovalWaitDecisionResult>;
    };
  };
  plugin: {
    approval: {
      request(
        params: import("./gateway-protocol.generated").PluginApprovalRequestParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").PluginApprovalRequestResult>;
      waitDecision(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").PluginApprovalWaitDecisionResult>;
      resolve(
        params: import("./gateway-protocol.generated").PluginApprovalResolveParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").PluginApprovalResolveResult>;
    };
  };
  sessions: {
    list(
      params: import("./gateway-protocol.generated").SessionsListParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsListResult>;
    subscribe(
      params: Record<string, unknown>,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsSubscribeResult>;
    unsubscribe(
      params: Record<string, unknown>,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsUnsubscribeResult>;
    messages: {
      subscribe(
        params: import("./gateway-protocol.generated").SessionsMessagesSubscribeParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsMessagesSubscribeResult>;
      unsubscribe(
        params: import("./gateway-protocol.generated").SessionsMessagesUnsubscribeParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsMessagesUnsubscribeResult>;
    };
    preview(
      params: import("./gateway-protocol.generated").SessionsPreviewParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsPreviewResult>;
    get(
      params: import("./gateway-protocol.generated").SessionsGetParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsGetResult>;
    create(
      params: import("./gateway-protocol.generated").SessionsCreateParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsCreateResult>;
    send(
      params: import("./gateway-protocol.generated").SessionsSendParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsSendResult>;
    steer(
      params: import("./gateway-protocol.generated").SessionsSteerParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsSteerResult>;
    abort(
      params: import("./gateway-protocol.generated").SessionsAbortParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsAbortResult>;
    patch(
      params: import("./gateway-protocol.generated").SessionsPatchParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsPatchResult>;
    reset(
      params: import("./gateway-protocol.generated").SessionsResetParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsResetResult>;
    clear(
      params: import("./gateway-protocol.generated").SessionsClearParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsClearResult>;
    delete(
      params: import("./gateway-protocol.generated").SessionsDeleteParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsDeleteResult>;
    compact(
      params: import("./gateway-protocol.generated").SessionsCompactParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").SessionsCompactResult>;
    compaction: {
      list(
        params: import("./gateway-protocol.generated").SessionsCompactionListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsCompactionListResult>;
      get(
        params: import("./gateway-protocol.generated").SessionsCompactionGetParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsCompactionGetResult>;
      branch(
        params: import("./gateway-protocol.generated").SessionsCompactionBranchParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsCompactionBranchResult>;
      restore(
        params: import("./gateway-protocol.generated").SessionsCompactionRestoreParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsCompactionRestoreResult>;
    };
    usage: {
      $call(
        params: import("./gateway-protocol.generated").SessionsUsageParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsUsageResult>;
      timeseries(
        params: import("./gateway-protocol.generated").SessionsUsageTimeseriesParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsUsageTimeseriesResult>;
      logs(
        params: import("./gateway-protocol.generated").SessionsUsageLogsParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").SessionsUsageLogsResult>;
    };
  };
  agent: {
    identity: {
      get(
        params: import("./gateway-protocol.generated").AgentIdentityGetParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").AgentIdentityGetResult>;
    };
    wait(
      params: import("./gateway-protocol.generated").AgentWaitParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").AgentWaitResult>;
  };
  agents: {
    list(
      params: import("./gateway-protocol.generated").AgentsListParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").AgentsListResult>;
    create(
      params: import("./gateway-protocol.generated").AgentsCreateParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").AgentsCreateResult>;
    update(
      params: import("./gateway-protocol.generated").AgentsUpdateParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").AgentsUpdateResult>;
    delete(
      params: import("./gateway-protocol.generated").AgentsDeleteParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").AgentsDeleteResult>;
    files: {
      list(
        params: import("./gateway-protocol.generated").AgentsFilesListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").AgentsFilesListResult>;
      get(
        params: import("./gateway-protocol.generated").AgentsFilesGetParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").AgentsFilesGetResult>;
      set(
        params: import("./gateway-protocol.generated").AgentsFilesSetParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").AgentsFilesSetResult>;
    };
  };
  channels: {
    status(
      params: import("./gateway-protocol.generated").ChannelsStatusParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ChannelsStatusResult>;
    logout(
      params: import("./gateway-protocol.generated").ChannelsLogoutParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ChannelsLogoutResult>;
  };
  commands: {
    list(
      params: import("./gateway-protocol.generated").CommandsListParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").CommandsListResult>;
  };
  logs: {
    tail(
      params: import("./gateway-protocol.generated").LogsTailParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").LogsTailResult>;
  };
  deck: {
    commands: {
      discover(
        params: import("./gateway-protocol.generated").DeckCommandsDiscoverParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckCommandsDiscoverResult>;
    };
    routing: {
      list(
        params: import("./gateway-protocol.generated").DeckRoutingListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckRoutingListResult>;
      add(
        params: import("./gateway-protocol.generated").DeckRoutingAddParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckRoutingAddResult>;
      remove(
        params: import("./gateway-protocol.generated").DeckRoutingRemoveParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckRoutingRemoveResult>;
      validate(
        params: import("./gateway-protocol.generated").DeckRoutingValidateParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckRoutingValidateResult>;
      simulate(
        params: import("./gateway-protocol.generated").DeckRoutingSimulateParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckRoutingSimulateResult>;
    };
    agents: {
      detail(
        params: import("./gateway-protocol.generated").DeckAgentsDetailParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckAgentsDetailResult>;
      skills: {
        get(
          params: import("./gateway-protocol.generated").DeckAgentsSkillsGetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsSkillsGetResult>;
        set(
          params: import("./gateway-protocol.generated").DeckAgentsSkillsSetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsSkillsSetResult>;
      };
      subagents: {
        get(
          params: import("./gateway-protocol.generated").DeckAgentsSubagentsGetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsSubagentsGetResult>;
        set(
          params: import("./gateway-protocol.generated").DeckAgentsSubagentsSetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsSubagentsSetResult>;
      };
      eventStreams: {
        get(
          params: import("./gateway-protocol.generated").DeckAgentsEventStreamsGetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsEventStreamsGetResult>;
        set(
          params: import("./gateway-protocol.generated").DeckAgentsEventStreamsSetParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsEventStreamsSetResult>;
      };
      toolPolicy: {
        preview(
          params: import("./gateway-protocol.generated").DeckAgentsToolPolicyPreviewParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsToolPolicyPreviewResult>;
      };
      systemPrompt: {
        preview(
          params: import("./gateway-protocol.generated").DeckAgentsSystemPromptPreviewParams,
          options?: { timeoutMs?: number },
        ): Promise<import("./gateway-protocol.generated").DeckAgentsSystemPromptPreviewResult>;
      };
    };
    subagents: {
      list(
        params: import("./gateway-protocol.generated").DeckSubagentsListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckSubagentsListResult>;
      kill(
        params: import("./gateway-protocol.generated").DeckSubagentsKillParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckSubagentsKillResult>;
      lineage(
        params: import("./gateway-protocol.generated").DeckSubagentsLineageParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckSubagentsLineageResult>;
      steer(
        params: import("./gateway-protocol.generated").DeckSubagentsSteerParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckSubagentsSteerResult>;
    };
    identity: {
      list(
        params: import("./gateway-protocol.generated").DeckIdentityListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckIdentityListResult>;
      link(
        params: import("./gateway-protocol.generated").DeckIdentityLinkParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckIdentityLinkResult>;
      unlink(
        params: import("./gateway-protocol.generated").DeckIdentityUnlinkParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckIdentityUnlinkResult>;
    };
    threads: {
      list(
        params: import("./gateway-protocol.generated").DeckThreadsListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckThreadsListResult>;
    };
    auth: {
      overview(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckAuthOverviewResult>;
      probe(
        params: Record<string, unknown>,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeckAuthProbeResult>;
    };
  };
  gateway: {
    describe(
      params: import("./gateway-protocol.generated").GatewayDescribeParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").GatewayDescribeResult>;
  };
  talk: {
    config(
      params: import("./gateway-protocol.generated").TalkConfigParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").TalkConfigResult>;
    speak(
      params: import("./gateway-protocol.generated").TalkSpeakParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").TalkSpeakResult>;
    mode(
      params: import("./gateway-protocol.generated").TalkModeParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").TalkModeResult>;
  };
  tools: {
    catalog(
      params: import("./gateway-protocol.generated").ToolsCatalogParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ToolsCatalogResult>;
    effective(
      params: import("./gateway-protocol.generated").ToolsEffectiveParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").ToolsEffectiveResult>;
  };
  wizard: {
    start(
      params: import("./gateway-protocol.generated").WizardStartParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").WizardStartResult>;
    next(
      params: import("./gateway-protocol.generated").WizardNextParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").WizardNextResult>;
    cancel(
      params: import("./gateway-protocol.generated").WizardCancelParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").WizardCancelResult>;
    status(
      params: import("./gateway-protocol.generated").WizardStatusParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").WizardStatusResult>;
  };
  device: {
    pair: {
      list(
        params: import("./gateway-protocol.generated").DevicePairListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DevicePairListResult>;
      approve(
        params: import("./gateway-protocol.generated").DevicePairApproveParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DevicePairApproveResult>;
      reject(
        params: import("./gateway-protocol.generated").DevicePairRejectParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DevicePairRejectResult>;
      remove(
        params: import("./gateway-protocol.generated").DevicePairRemoveParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DevicePairRemoveResult>;
    };
    token: {
      rotate(
        params: import("./gateway-protocol.generated").DeviceTokenRotateParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeviceTokenRotateResult>;
      revoke(
        params: import("./gateway-protocol.generated").DeviceTokenRevokeParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").DeviceTokenRevokeResult>;
    };
  };
  node: {
    list(
      params: import("./gateway-protocol.generated").NodeListParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").NodeListResult>;
    describe(
      params: import("./gateway-protocol.generated").NodeDescribeParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").NodeDescribeResult>;
    pair: {
      list(
        params: import("./gateway-protocol.generated").NodePairListParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").NodePairListResult>;
      request(
        params: import("./gateway-protocol.generated").NodePairRequestParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").NodePairRequestResult>;
      approve(
        params: import("./gateway-protocol.generated").NodePairApproveParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").NodePairApproveResult>;
      reject(
        params: import("./gateway-protocol.generated").NodePairRejectParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").NodePairRejectResult>;
      verify(
        params: import("./gateway-protocol.generated").NodePairVerifyParams,
        options?: { timeoutMs?: number },
      ): Promise<import("./gateway-protocol.generated").NodePairVerifyResult>;
    };
    rename(
      params: import("./gateway-protocol.generated").NodeRenameParams,
      options?: { timeoutMs?: number },
    ): Promise<import("./gateway-protocol.generated").NodeRenameResult>;
  };
}

export function createGatewayClient(request: GatewayRequestFn): GatewayClient {
  const call =
    <M extends GatewayMethodName>(method: M) =>
    (params: GatewayMethodMap[M]["params"], options?: { timeoutMs?: number }) =>
      request(method, params, options);

  return {
    chat: {
      history: call("chat.history"),
      abort: call("chat.abort"),
      send: call("chat.send"),
    },
    config: {
      get: call("config.get"),
      schema: {
        $call: call("config.schema"),
        lookup: call("config.schema.lookup"),
      },
      apply: call("config.apply"),
      patch: call("config.patch"),
      set: call("config.set"),
    },
    doctor: {
      memory: {
        status: call("doctor.memory.status"),
        dreamDiary: call("doctor.memory.dreamDiary"),
        backfillDreamDiary: call("doctor.memory.backfillDreamDiary"),
        resetDreamDiary: call("doctor.memory.resetDreamDiary"),
        resetGroundedShortTerm: call("doctor.memory.resetGroundedShortTerm"),
        repairDreamingArtifacts: call("doctor.memory.repairDreamingArtifacts"),
        dedupeDreamDiary: call("doctor.memory.dedupeDreamDiary"),
      },
    },
    health: call("health"),
    status: call("status"),
    usage: {
      status: call("usage.status"),
      cost: call("usage.cost"),
    },
    models: {
      catalog: {
        providers: call("models.catalog.providers"),
      },
      list: call("models.list"),
      configured: call("models.configured"),
    },
    skills: {
      status: call("skills.status"),
      bins: call("skills.bins"),
      install: call("skills.install"),
      update: call("skills.update"),
      search: call("skills.search"),
      detail: call("skills.detail"),
    },
    cron: {
      list: call("cron.list"),
      status: call("cron.status"),
      add: call("cron.add"),
      update: call("cron.update"),
      remove: call("cron.remove"),
      run: call("cron.run"),
      runs: call("cron.runs"),
    },
    exec: {
      approvals: {
        get: call("exec.approvals.get"),
        set: call("exec.approvals.set"),
        node: {
          get: call("exec.approvals.node.get"),
          set: call("exec.approvals.node.set"),
        },
      },
      approval: {
        request: call("exec.approval.request"),
        resolve: call("exec.approval.resolve"),
        waitDecision: call("exec.approval.waitDecision"),
      },
    },
    plugin: {
      approval: {
        request: call("plugin.approval.request"),
        waitDecision: call("plugin.approval.waitDecision"),
        resolve: call("plugin.approval.resolve"),
      },
    },
    sessions: {
      list: call("sessions.list"),
      subscribe: call("sessions.subscribe"),
      unsubscribe: call("sessions.unsubscribe"),
      messages: {
        subscribe: call("sessions.messages.subscribe"),
        unsubscribe: call("sessions.messages.unsubscribe"),
      },
      preview: call("sessions.preview"),
      get: call("sessions.get"),
      create: call("sessions.create"),
      send: call("sessions.send"),
      steer: call("sessions.steer"),
      abort: call("sessions.abort"),
      patch: call("sessions.patch"),
      reset: call("sessions.reset"),
      clear: call("sessions.clear"),
      delete: call("sessions.delete"),
      compact: call("sessions.compact"),
      compaction: {
        list: call("sessions.compaction.list"),
        get: call("sessions.compaction.get"),
        branch: call("sessions.compaction.branch"),
        restore: call("sessions.compaction.restore"),
      },
      usage: {
        $call: call("sessions.usage"),
        timeseries: call("sessions.usage.timeseries"),
        logs: call("sessions.usage.logs"),
      },
    },
    agent: {
      identity: {
        get: call("agent.identity.get"),
      },
      wait: call("agent.wait"),
    },
    agents: {
      list: call("agents.list"),
      create: call("agents.create"),
      update: call("agents.update"),
      delete: call("agents.delete"),
      files: {
        list: call("agents.files.list"),
        get: call("agents.files.get"),
        set: call("agents.files.set"),
      },
    },
    channels: {
      status: call("channels.status"),
      logout: call("channels.logout"),
    },
    commands: {
      list: call("commands.list"),
    },
    logs: {
      tail: call("logs.tail"),
    },
    deck: {
      commands: {
        discover: call("deck.commands.discover"),
      },
      routing: {
        list: call("deck.routing.list"),
        add: call("deck.routing.add"),
        remove: call("deck.routing.remove"),
        validate: call("deck.routing.validate"),
        simulate: call("deck.routing.simulate"),
      },
      agents: {
        detail: call("deck.agents.detail"),
        skills: {
          get: call("deck.agents.skills.get"),
          set: call("deck.agents.skills.set"),
        },
        subagents: {
          get: call("deck.agents.subagents.get"),
          set: call("deck.agents.subagents.set"),
        },
        eventStreams: {
          get: call("deck.agents.eventStreams.get"),
          set: call("deck.agents.eventStreams.set"),
        },
        toolPolicy: {
          preview: call("deck.agents.toolPolicy.preview"),
        },
        systemPrompt: {
          preview: call("deck.agents.systemPrompt.preview"),
        },
      },
      subagents: {
        list: call("deck.subagents.list"),
        kill: call("deck.subagents.kill"),
        lineage: call("deck.subagents.lineage"),
        steer: call("deck.subagents.steer"),
      },
      identity: {
        list: call("deck.identity.list"),
        link: call("deck.identity.link"),
        unlink: call("deck.identity.unlink"),
      },
      threads: {
        list: call("deck.threads.list"),
      },
      auth: {
        overview: call("deck.auth.overview"),
        probe: call("deck.auth.probe"),
      },
    },
    gateway: {
      describe: call("gateway.describe"),
    },
    talk: {
      config: call("talk.config"),
      speak: call("talk.speak"),
      mode: call("talk.mode"),
    },
    tools: {
      catalog: call("tools.catalog"),
      effective: call("tools.effective"),
    },
    wizard: {
      start: call("wizard.start"),
      next: call("wizard.next"),
      cancel: call("wizard.cancel"),
      status: call("wizard.status"),
    },
    device: {
      pair: {
        list: call("device.pair.list"),
        approve: call("device.pair.approve"),
        reject: call("device.pair.reject"),
        remove: call("device.pair.remove"),
      },
      token: {
        rotate: call("device.token.rotate"),
        revoke: call("device.token.revoke"),
      },
    },
    node: {
      list: call("node.list"),
      describe: call("node.describe"),
      pair: {
        list: call("node.pair.list"),
        request: call("node.pair.request"),
        approve: call("node.pair.approve"),
        reject: call("node.pair.reject"),
        verify: call("node.pair.verify"),
      },
      rename: call("node.rename"),
    },
  };
}
