// Auto-generated by scripts/protocol-gen-ts.ts — DO NOT EDIT

import type { GatewayMethodMap, GatewayMethodName } from "./gateway-protocol.generated";

export type GatewayRequestFn = <M extends GatewayMethodName>(
  method: M,
  params: GatewayMethodMap[M]["params"],
  options?: { timeoutMs?: number },
) => Promise<GatewayMethodMap[M]["result"]>;

export const GENERATED_METHOD_ALLOWLIST: ReadonlySet<string> = new Set([
  "agent",
  "agent.identity.get",
  "agent.wait",
  "agents.create",
  "agents.delete",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "agents.list",
  "agents.update",
  "browser.request",
  "channels.logout",
  "channels.status",
  "chat.abort",
  "chat.history",
  "chat.send",
  "config.apply",
  "config.get",
  "config.patch",
  "config.schema",
  "config.schema.lookup",
  "config.set",
  "cron.add",
  "cron.list",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "cron.status",
  "cron.update",
  "deck.agents.detail",
  "deck.agents.eventStreams.get",
  "deck.agents.eventStreams.set",
  "deck.agents.skills.get",
  "deck.agents.skills.set",
  "deck.agents.subagents.get",
  "deck.agents.subagents.set",
  "deck.agents.systemPrompt.preview",
  "deck.agents.toolPolicy.preview",
  "deck.auth.overview",
  "deck.auth.probe",
  "deck.identity.link",
  "deck.identity.list",
  "deck.identity.unlink",
  "deck.routing.add",
  "deck.routing.list",
  "deck.routing.remove",
  "deck.routing.simulate",
  "deck.routing.validate",
  "deck.subagents.kill",
  "deck.subagents.lineage",
  "deck.subagents.list",
  "deck.subagents.steer",
  "deck.threads.list",
  "device.pair.approve",
  "device.pair.list",
  "device.pair.reject",
  "device.pair.remove",
  "device.token.revoke",
  "device.token.rotate",
  "doctor.memory.status",
  "exec.approval.request",
  "exec.approval.resolve",
  "exec.approval.waitDecision",
  "exec.approvals.get",
  "exec.approvals.node.get",
  "exec.approvals.node.set",
  "exec.approvals.set",
  "gateway.identity.get",
  "health",
  "last-heartbeat",
  "logs.tail",
  "models.catalog.providers",
  "models.configured",
  "models.list",
  "node.canvas.capability.refresh",
  "node.describe",
  "node.event",
  "node.invoke",
  "node.invoke.result",
  "node.list",
  "node.pair.approve",
  "node.pair.list",
  "node.pair.reject",
  "node.pair.request",
  "node.pair.verify",
  "node.pending.ack",
  "node.pending.drain",
  "node.pending.enqueue",
  "node.pending.pull",
  "node.rename",
  "secrets.reload",
  "secrets.resolve",
  "send",
  "sessions.abort",
  "sessions.compact",
  "sessions.create",
  "sessions.delete",
  "sessions.list",
  "sessions.messages.subscribe",
  "sessions.messages.unsubscribe",
  "sessions.patch",
  "sessions.preview",
  "sessions.reset",
  "sessions.send",
  "sessions.subscribe",
  "sessions.unsubscribe",
  "set-heartbeats",
  "skills.bins",
  "skills.install",
  "skills.status",
  "skills.update",
  "status",
  "system-event",
  "system-presence",
  "talk.config",
  "talk.mode",
  "talk.speak",
  "tools.catalog",
  "tts.convert",
  "tts.disable",
  "tts.enable",
  "tts.providers",
  "tts.setProvider",
  "tts.status",
  "update.run",
  "usage.cost",
  "usage.status",
  "voicewake.get",
  "voicewake.set",
  "wake",
  "wizard.cancel",
  "wizard.next",
  "wizard.start",
  "wizard.status",
]);

export const GENERATED_EVENT_NAMES: ReadonlySet<string> = new Set([
  "agent",
  "chat",
  "connect.challenge",
  "cron",
  "device.pair.requested",
  "device.pair.resolved",
  "exec.approval.requested",
  "exec.approval.resolved",
  "health",
  "heartbeat",
  "node.invoke.request",
  "node.pair.requested",
  "node.pair.resolved",
  "presence",
  "session.message",
  "session.tool",
  "sessions.changed",
  "shutdown",
  "talk.mode",
  "tick",
  "update.available",
  "voicewake.changed",
]);

export interface GatewayClient {
  deck: {
    routing: {
      list(params: import("./gateway-protocol.generated").DeckRoutingListParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckRoutingListResult>;
      add(params: import("./gateway-protocol.generated").DeckRoutingAddParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckRoutingAddResult>;
      remove(params: import("./gateway-protocol.generated").DeckRoutingRemoveParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckRoutingRemoveResult>;
      validate(params: import("./gateway-protocol.generated").DeckRoutingValidateParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckRoutingValidateResult>;
      simulate(params: import("./gateway-protocol.generated").DeckRoutingSimulateParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckRoutingSimulateResult>;
    };
    agents: {
      detail(params: import("./gateway-protocol.generated").DeckAgentsDetailParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsDetailResult>;
      skills: {
        get(params: import("./gateway-protocol.generated").DeckAgentsSkillsGetParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsSkillsGetResult>;
        set(params: import("./gateway-protocol.generated").DeckAgentsSkillsSetParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsSkillsSetResult>;
      };
      subagents: {
        get(params: import("./gateway-protocol.generated").DeckAgentsSubagentsGetParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsSubagentsGetResult>;
        set(params: import("./gateway-protocol.generated").DeckAgentsSubagentsSetParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsSubagentsSetResult>;
      };
      eventStreams: {
        get(params: import("./gateway-protocol.generated").DeckAgentsEventStreamsGetParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsEventStreamsGetResult>;
        set(params: import("./gateway-protocol.generated").DeckAgentsEventStreamsSetParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsEventStreamsSetResult>;
      };
      toolPolicy: {
        preview(params: import("./gateway-protocol.generated").DeckAgentsToolPolicyPreviewParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsToolPolicyPreviewResult>;
      };
      systemPrompt: {
        preview(params: import("./gateway-protocol.generated").DeckAgentsSystemPromptPreviewParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckAgentsSystemPromptPreviewResult>;
      };
    };
    subagents: {
      list(params: import("./gateway-protocol.generated").DeckSubagentsListParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckSubagentsListResult>;
      kill(params: import("./gateway-protocol.generated").DeckSubagentsKillParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckSubagentsKillResult>;
      lineage(params: import("./gateway-protocol.generated").DeckSubagentsLineageParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckSubagentsLineageResult>;
      steer(params: import("./gateway-protocol.generated").DeckSubagentsSteerParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckSubagentsSteerResult>;
    };
    identity: {
      list(params: import("./gateway-protocol.generated").DeckIdentityListParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckIdentityListResult>;
      link(params: import("./gateway-protocol.generated").DeckIdentityLinkParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckIdentityLinkResult>;
      unlink(params: import("./gateway-protocol.generated").DeckIdentityUnlinkParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckIdentityUnlinkResult>;
    };
    threads: {
      list(params: import("./gateway-protocol.generated").DeckThreadsListParams, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").DeckThreadsListResult>;
    };
    auth: {
      overview(params: Record<string, unknown>, options?: { timeoutMs?: number }): Promise<unknown>;
      probe(params: Record<string, unknown>, options?: { timeoutMs?: number }): Promise<unknown>;
    };
  };
}

export function createGatewayClient(request: GatewayRequestFn): GatewayClient {
  const call = <M extends GatewayMethodName>(method: M) =>
    (params: GatewayMethodMap[M]["params"], options?: { timeoutMs?: number }) =>
      request(method, params, options);

  return {
    deck: {
      routing: {
        list: call("deck.routing.list"),
        add: call("deck.routing.add"),
        remove: call("deck.routing.remove"),
        validate: call("deck.routing.validate"),
        simulate: call("deck.routing.simulate"),
      },
      agents: {
        detail: call("deck.agents.detail"),
        skills: {
          get: call("deck.agents.skills.get"),
          set: call("deck.agents.skills.set"),
        },
        subagents: {
          get: call("deck.agents.subagents.get"),
          set: call("deck.agents.subagents.set"),
        },
        eventStreams: {
          get: call("deck.agents.eventStreams.get"),
          set: call("deck.agents.eventStreams.set"),
        },
        toolPolicy: {
          preview: call("deck.agents.toolPolicy.preview"),
        },
        systemPrompt: {
          preview: call("deck.agents.systemPrompt.preview"),
        },
      },
      subagents: {
        list: call("deck.subagents.list"),
        kill: call("deck.subagents.kill"),
        lineage: call("deck.subagents.lineage"),
        steer: call("deck.subagents.steer"),
      },
      identity: {
        list: call("deck.identity.list"),
        link: call("deck.identity.link"),
        unlink: call("deck.identity.unlink"),
      },
      threads: {
        list: call("deck.threads.list"),
      },
      auth: {
        overview: call("deck.auth.overview"),
        probe: call("deck.auth.probe"),
      },
    },
  };
}

