// Auto-generated by scripts/protocol-gen-ts.ts — DO NOT EDIT

export const GENERATED_SCHEMA_VERSION = "3";

export type TranscriptBlock =
  | {
      type: "text";
      text: string;
    }
  | {
      type: "thinking";
      text: string;
    }
  | {
      type: "tool_use";
      id: string;
      name: string;
      input: Record<string, unknown>;
    }
  | {
      type: "tool_result";
      toolUseId: string;
      content: string;
      isError?: boolean;
    }
  | {
      type: "image";
      data: string;
      mimeType: string;
      fileName?: string;
    }
  | {
      type: "file";
      data: string;
      mimeType: string;
      fileName: string;
      size?: number;
    };

export type TranscriptMessage = {
  id?: string;
  role: "user" | "assistant" | "system";
  content: (
    | {
        type: "text";
        text: string;
      }
    | {
        type: "thinking";
        text: string;
      }
    | {
        type: "tool_use";
        id: string;
        name: string;
        input: Record<string, unknown>;
      }
    | {
        type: "tool_result";
        toolUseId: string;
        content: string;
        isError?: boolean;
      }
    | {
        type: "image";
        data: string;
        mimeType: string;
        fileName?: string;
      }
    | {
        type: "file";
        data: string;
        mimeType: string;
        fileName: string;
        size?: number;
      }
  )[];
  timestamp: number;
};

export interface ChatHistoryParams {
  sessionKey: string;
  limit?: number;
  maxChars?: number;
}

export type ChatHistoryResult = {
  sessionKey: string;
  sessionId: string;
  messages: {
    id?: string;
    role: "user" | "assistant" | "system";
    content: (
      | {
          type: "text";
          text: string;
        }
      | {
          type: "thinking";
          text: string;
        }
      | {
          type: "tool_use";
          id: string;
          name: string;
          input: Record<string, unknown>;
        }
      | {
          type: "tool_result";
          toolUseId: string;
          content: string;
          isError?: boolean;
        }
      | {
          type: "image";
          data: string;
          mimeType: string;
          fileName?: string;
        }
      | {
          type: "file";
          data: string;
          mimeType: string;
          fileName: string;
          size?: number;
        }
    )[];
    timestamp: number;
  }[];
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
};

export interface ChatAbortParams {
  sessionKey: string;
  runId?: string;
}

export interface ChatAbortResult {
  ok: boolean;
  aborted: boolean;
  runIds: string[];
}

export interface ChatSendParams {
  sessionKey: string;
  message: string;
  thinking?: string;
  deliver?: boolean;
  originatingChannel?: string;
  originatingTo?: string;
  originatingAccountId?: string;
  originatingThreadId?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  systemInputProvenance?: {
    kind: string;
    originSessionId?: string;
    sourceSessionKey?: string;
    sourceChannel?: string;
    sourceTool?: string;
  };
  systemProvenanceReceipt?: string;
  idempotencyKey: string;
}

export interface ChatSendResult {
  ok?: boolean;
  aborted?: boolean;
  runIds?: string[];
  runId?: string;
  status?: string;
}

export type ConfigGetParams = Record<string, never>;

export interface ConfigGetResult {
  path: string;
  exists: boolean;
  raw: string;
  parsed: unknown;
  sourceConfig: unknown;
  resolved: unknown;
  valid: boolean;
  runtimeConfig: unknown;
  config: unknown;
  hash?: string;
  issues: unknown[];
  warnings: unknown[];
  legacyIssues: unknown[];
}

export type ConfigSchemaParams = Record<string, never>;

export interface ConfigSchemaResult {
  schema: unknown;
  uiHints: Record<
    string,
    {
      label?: string;
      help?: string;
      tags?: string[];
      group?: string;
      order?: number;
      advanced?: boolean;
      sensitive?: boolean;
      placeholder?: string;
      itemTemplate?: unknown;
    }
  >;
  version: string;
  generatedAt: string;
}

export interface ConfigSchemaLookupParams {
  path: string;
}

export interface ConfigSchemaLookupResult {
  path: string;
  schema: unknown;
  hint?: {
    label?: string;
    help?: string;
    tags?: string[];
    group?: string;
    order?: number;
    advanced?: boolean;
    sensitive?: boolean;
    placeholder?: string;
    itemTemplate?: unknown;
  };
  hintPath?: string;
  children: {
    key: string;
    path: string;
    type?: string;
    required: boolean;
    hasChildren: boolean;
    hint?: {
      label?: string;
      help?: string;
      tags?: string[];
      group?: string;
      order?: number;
      advanced?: boolean;
      sensitive?: boolean;
      placeholder?: string;
      itemTemplate?: unknown;
    };
    hintPath?: string;
  }[];
}

export interface ConfigApplyParams {
  raw: string;
  baseHash?: string;
  sessionKey?: string;
  deliveryContext?: {
    channel?: string;
    to?: string;
    accountId?: string;
    threadId?: string;
  };
  note?: string;
  restartDelayMs?: number;
}

export interface ConfigApplyResult {
  ok: boolean;
  noop?: boolean;
  path: string;
  config: unknown;
  restart?: unknown;
  sentinel?: unknown;
}

export interface ConfigPatchParams {
  raw: string;
  baseHash?: string;
  sessionKey?: string;
  deliveryContext?: {
    channel?: string;
    to?: string;
    accountId?: string;
    threadId?: string;
  };
  note?: string;
  restartDelayMs?: number;
}

export interface ConfigPatchResult {
  ok: boolean;
  noop?: boolean;
  path: string;
  config: unknown;
  restart?: unknown;
  sentinel?: unknown;
}

export interface ConfigSetParams {
  raw: string;
  baseHash?: string;
}

export interface ConfigSetResult {
  ok: boolean;
  noop?: boolean;
  path: string;
  config: unknown;
  restart?: unknown;
  sentinel?: unknown;
}

export interface ChannelsStatusParams {
  probe?: boolean;
  timeoutMs?: number;
}

export type ChannelsStatusResult = {
  ts: number;
  channelOrder: string[];
  channelLabels: Record<string, string>;
  channelDetailLabels?: Record<string, string>;
  channelSystemImages?: Record<string, string>;
  channelMeta?: {
    id: string;
    label: string;
    detailLabel: string;
    systemImage?: string;
    pluginId?: string;
    pluginOrigin?: string;
    pluginNpmSpec?: string;
    pluginLocalPath?: string;
    pluginDefaultInstallChoice?: "npm" | "local";
    pluginConfigPath?: string;
  }[];
  channels: Record<string, unknown>;
  channelAccounts: Record<
    string,
    {
      accountId: string;
      name?: string;
      enabled?: boolean;
      configured?: boolean;
      linked?: boolean;
      running?: boolean;
      connected?: boolean;
      reconnectAttempts?: number;
      lastConnectedAt?: number;
      lastError?: string;
      healthState?: string;
      lastStartAt?: number;
      lastStopAt?: number;
      lastInboundAt?: number;
      lastOutboundAt?: number;
      busy?: boolean;
      activeRuns?: number;
      lastRunActivityAt?: number;
      lastProbeAt?: number;
      mode?: string;
      dmPolicy?: string;
      allowFrom?: string[];
      tokenSource?: string;
      botTokenSource?: string;
      appTokenSource?: string;
      baseUrl?: string;
      allowUnmentionedGroups?: boolean;
      cliPath?: string;
      dbPath?: string;
      port?: number;
      probe?: unknown;
      audit?: unknown;
      application?: unknown;
    }[]
  >;
  channelDefaultAccountId: Record<string, string>;
};

export interface ChannelsLogoutParams {
  channel: string;
  accountId?: string;
}

export interface ChannelsLogoutResult {
  channel: string;
  accountId: string;
  cleared: boolean;
}

export interface DoctorMemoryStatusResult {
  agentId: string;
  provider?: string;
  embedding: {
    ok: boolean;
    error?: string;
  };
}

export interface HealthResult {
  ok: true;
  ts: number;
  durationMs: number;
  channels: Record<string, unknown>;
  channelOrder: string[];
  channelLabels: Record<string, string>;
  heartbeatSeconds: number;
  defaultAgentId: string;
  agents: unknown[];
  sessions: {
    path: string;
    count: number;
    recent: unknown[];
  };
}

export interface StatusResult {
  runtimeVersion?: string;
  linkChannel?: {
    id: string;
    label: string;
    linked: boolean;
    authAgeMs: number;
  };
  heartbeat: {
    defaultAgentId: string;
    agents: unknown[];
  };
  channelSummary: string[];
  queuedSystemEvents: string[];
  sessions: {
    paths: string[];
    count: number;
    defaults: {
      model: string;
      contextTokens: number;
    };
    recent: unknown[];
    byAgent: unknown[];
  };
}

export interface UsageStatusResult {
  updatedAt: number;
  providers: {
    provider: string;
    displayName: string;
    windows: {
      label: string;
      usedPercent: number;
      resetAt?: number;
    }[];
    plan?: string;
    error?: string;
  }[];
}

export interface UsageCostResult {
  updatedAt: number;
  days: number;
  daily: {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
    totalTokens: number;
    totalCost: number;
    inputCost: number;
    outputCost: number;
    cacheReadCost: number;
    cacheWriteCost: number;
    missingCostEntries: number;
    date: string;
  }[];
  totals: {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
    totalTokens: number;
    totalCost: number;
    inputCost: number;
    outputCost: number;
    cacheReadCost: number;
    cacheWriteCost: number;
    missingCostEntries: number;
  };
}

export interface ModelsCatalogProvidersResult {
  providers: {
    id: string;
    displayName: string;
    modelCount: number;
    defaultBaseUrl: string;
    authType: string;
    api: string;
    models: {
      id: string;
      name: string;
      contextWindow: number;
      reasoning: boolean;
      maxTokens: number;
    }[];
  }[];
}

export interface SkillsStatusParams {
  agentId?: string;
}

export interface SkillsStatusResult {
  workspaceDir: string;
  managedSkillsDir: string;
  skills: {
    name: string;
    description: string;
    source: string;
    bundled: boolean;
    filePath: string;
    baseDir: string;
    skillKey: string;
    primaryEnv?: string;
    emoji?: string;
    homepage?: string;
    always: boolean;
    disabled: boolean;
    blockedByAllowlist: boolean;
    eligible: boolean;
    requirements: {
      bins: string[];
      anyBins: string[];
      env: string[];
      config: string[];
      os: string[];
    };
    missing: {
      bins: string[];
      anyBins: string[];
      env: string[];
      config: string[];
      os: string[];
    };
    configChecks: {
      path: string;
      satisfied: boolean;
    }[];
    install: {
      id: string;
      kind: string;
      label: string;
      bins: string[];
    }[];
  }[];
}

export type SkillsBinsParams = Record<string, never>;

export interface SkillsBinsResult {
  bins: string[];
}

export type SkillsInstallParams =
  | {
      name: string;
      installId: string;
      dangerouslyForceUnsafeInstall?: boolean;
      timeoutMs?: number;
    }
  | {
      source: "clawhub";
      slug: string;
      version?: string;
      force?: boolean;
      timeoutMs?: number;
    };

export interface SkillsInstallResult {
  ok: boolean;
  message: string;
  stdout: string;
  stderr: string;
  code: number;
  slug?: string;
  version?: string;
  targetDir?: string;
  warnings?: string[];
}

export type SkillsUpdateParams =
  | {
      skillKey: string;
      enabled?: boolean;
      apiKey?: string;
      env?: Record<string, string>;
    }
  | {
      source: "clawhub";
      slug?: string;
      all?: boolean;
    };

export interface SkillsUpdateResult {
  ok: boolean;
  skillKey: string;
  config: unknown;
}

export interface SkillsSearchParams {
  query?: string;
  limit?: number;
}

export interface SkillsSearchResult {
  results: {
    score: number;
    slug: string;
    displayName: string;
    summary?: string;
    version?: string;
    updatedAt?: number;
  }[];
}

export interface SkillsDetailParams {
  slug: string;
}

export type SkillsDetailResult = {
  skill: {
    slug: string;
    displayName: string;
    summary?: string;
    tags?: Record<string, string>;
    createdAt: number;
    updatedAt: number;
  } | null;
  latestVersion?: {
    version: string;
    createdAt: number;
    changelog?: string;
  } | null;
  metadata?: {
    os?: string[] | null;
    systems?: string[] | null;
  } | null;
  owner?: {
    handle?: string;
    displayName?: string;
    image?: string;
  } | null;
};

export type CronListParams = {
  includeDisabled?: boolean;
  limit?: number;
  offset?: number;
  query?: string;
  enabled?: "all" | "enabled" | "disabled";
  sortBy?: "nextRunAtMs" | "updatedAtMs" | "name";
  sortDir?: "asc" | "desc";
};

export type CronListResult = {
  jobs: {
    id: string;
    agentId?: string;
    sessionKey?: string;
    name: string;
    description?: string;
    enabled: boolean;
    deleteAfterRun?: boolean;
    createdAtMs: number;
    updatedAtMs: number;
    schedule:
      | {
          kind: "at";
          at: string;
        }
      | {
          kind: "every";
          everyMs: number;
          anchorMs?: number;
        }
      | {
          kind: "cron";
          expr: string;
          tz?: string;
          staggerMs?: number;
        };
    sessionTarget: string;
    wakeMode: "next-heartbeat" | "now";
    payload:
      | {
          kind: "systemEvent";
          text: string;
        }
      | {
          kind: "agentTurn";
          message: string;
          model?: string;
          fallbacks?: string[];
          thinking?: string;
          timeoutSeconds?: number;
          allowUnsafeExternalContent?: boolean;
          lightContext?: boolean;
          toolsAllow?: string[];
        };
    delivery?:
      | {
          mode: "none";
          channel?: string;
          accountId?: string;
          bestEffort?: boolean;
          failureDestination?: {
            channel?: string;
            to?: string;
            accountId?: string;
            mode?: "announce" | "webhook";
          };
          to?: string;
        }
      | {
          mode: "announce";
          channel?: string;
          accountId?: string;
          bestEffort?: boolean;
          failureDestination?: {
            channel?: string;
            to?: string;
            accountId?: string;
            mode?: "announce" | "webhook";
          };
          to?: string;
        }
      | {
          mode: "webhook";
          channel?: string;
          accountId?: string;
          bestEffort?: boolean;
          failureDestination?: {
            channel?: string;
            to?: string;
            accountId?: string;
            mode?: "announce" | "webhook";
          };
          to: string;
        };
    failureAlert?:
      | false
      | {
          after?: number;
          channel?: string;
          to?: string;
          cooldownMs?: number;
          mode?: "announce" | "webhook";
          accountId?: string;
        };
    state: {
      nextRunAtMs?: number;
      runningAtMs?: number;
      lastRunAtMs?: number;
      lastRunStatus?: "ok" | "error" | "skipped";
      lastStatus?: "ok" | "error" | "skipped";
      lastError?: string;
      lastErrorReason?:
        | "auth"
        | "format"
        | "rate_limit"
        | "billing"
        | "timeout"
        | "model_not_found"
        | "unknown";
      lastDurationMs?: number;
      consecutiveErrors?: number;
      lastDelivered?: boolean;
      lastDeliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
      lastDeliveryError?: string;
      lastFailureAlertAtMs?: number;
    };
  }[];
  total: number;
  offset: number;
  limit: number;
  hasMore: boolean;
  nextOffset: number;
};

export type CronStatusParams = Record<string, never>;

export interface CronStatusResult {
  enabled: boolean;
  storePath: string;
  jobs: number;
  nextWakeAtMs: number;
}

export type CronAddParams = {
  name: string;
  agentId?: string;
  sessionKey?: string;
  description?: string;
  enabled?: boolean;
  deleteAfterRun?: boolean;
  schedule:
    | {
        kind: "at";
        at: string;
      }
    | {
        kind: "every";
        everyMs: number;
        anchorMs?: number;
      }
    | {
        kind: "cron";
        expr: string;
        tz?: string;
        staggerMs?: number;
      };
  sessionTarget: string;
  wakeMode: "next-heartbeat" | "now";
  payload:
    | {
        kind: "systemEvent";
        text: string;
      }
    | {
        kind: "agentTurn";
        message: string;
        model?: string;
        fallbacks?: string[];
        thinking?: string;
        timeoutSeconds?: number;
        allowUnsafeExternalContent?: boolean;
        lightContext?: boolean;
        toolsAllow?: string[];
      };
  delivery?:
    | {
        mode: "none";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "announce";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "webhook";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to: string;
      };
  failureAlert?:
    | false
    | {
        after?: number;
        channel?: string;
        to?: string;
        cooldownMs?: number;
        mode?: "announce" | "webhook";
        accountId?: string;
      };
};

export type CronAddResult = {
  id: string;
  agentId?: string;
  sessionKey?: string;
  name: string;
  description?: string;
  enabled: boolean;
  deleteAfterRun?: boolean;
  createdAtMs: number;
  updatedAtMs: number;
  schedule:
    | {
        kind: "at";
        at: string;
      }
    | {
        kind: "every";
        everyMs: number;
        anchorMs?: number;
      }
    | {
        kind: "cron";
        expr: string;
        tz?: string;
        staggerMs?: number;
      };
  sessionTarget: string;
  wakeMode: "next-heartbeat" | "now";
  payload:
    | {
        kind: "systemEvent";
        text: string;
      }
    | {
        kind: "agentTurn";
        message: string;
        model?: string;
        fallbacks?: string[];
        thinking?: string;
        timeoutSeconds?: number;
        allowUnsafeExternalContent?: boolean;
        lightContext?: boolean;
        toolsAllow?: string[];
      };
  delivery?:
    | {
        mode: "none";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "announce";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "webhook";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to: string;
      };
  failureAlert?:
    | false
    | {
        after?: number;
        channel?: string;
        to?: string;
        cooldownMs?: number;
        mode?: "announce" | "webhook";
        accountId?: string;
      };
  state: {
    nextRunAtMs?: number;
    runningAtMs?: number;
    lastRunAtMs?: number;
    lastRunStatus?: "ok" | "error" | "skipped";
    lastStatus?: "ok" | "error" | "skipped";
    lastError?: string;
    lastErrorReason?:
      | "auth"
      | "format"
      | "rate_limit"
      | "billing"
      | "timeout"
      | "model_not_found"
      | "unknown";
    lastDurationMs?: number;
    consecutiveErrors?: number;
    lastDelivered?: boolean;
    lastDeliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
    lastDeliveryError?: string;
    lastFailureAlertAtMs?: number;
  };
};

export type CronUpdateParams =
  | {
      id: string;
      patch: {
        name?: string;
        agentId?: string;
        sessionKey?: string;
        description?: string;
        enabled?: boolean;
        deleteAfterRun?: boolean;
        schedule?:
          | {
              kind: "at";
              at: string;
            }
          | {
              kind: "every";
              everyMs: number;
              anchorMs?: number;
            }
          | {
              kind: "cron";
              expr: string;
              tz?: string;
              staggerMs?: number;
            };
        sessionTarget?: string;
        wakeMode?: "next-heartbeat" | "now";
        payload?:
          | {
              kind: "systemEvent";
              text?: string;
            }
          | {
              kind: "agentTurn";
              message?: string;
              model?: string;
              fallbacks?: string[];
              thinking?: string;
              timeoutSeconds?: number;
              allowUnsafeExternalContent?: boolean;
              lightContext?: boolean;
              toolsAllow?: string[] | null;
            };
        delivery?: {
          mode?: "none" | "announce" | "webhook";
          channel?: string;
          accountId?: string;
          bestEffort?: boolean;
          failureDestination?: {
            channel?: string;
            to?: string;
            accountId?: string;
            mode?: "announce" | "webhook";
          };
          to?: string;
        };
        failureAlert?:
          | false
          | {
              after?: number;
              channel?: string;
              to?: string;
              cooldownMs?: number;
              mode?: "announce" | "webhook";
              accountId?: string;
            };
        state?: {
          nextRunAtMs?: number;
          runningAtMs?: number;
          lastRunAtMs?: number;
          lastRunStatus?: "ok" | "error" | "skipped";
          lastStatus?: "ok" | "error" | "skipped";
          lastError?: string;
          lastErrorReason?:
            | "auth"
            | "format"
            | "rate_limit"
            | "billing"
            | "timeout"
            | "model_not_found"
            | "unknown";
          lastDurationMs?: number;
          consecutiveErrors?: number;
          lastDelivered?: boolean;
          lastDeliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
          lastDeliveryError?: string;
          lastFailureAlertAtMs?: number;
        };
      };
    }
  | {
      jobId: string;
      patch: {
        name?: string;
        agentId?: string;
        sessionKey?: string;
        description?: string;
        enabled?: boolean;
        deleteAfterRun?: boolean;
        schedule?:
          | {
              kind: "at";
              at: string;
            }
          | {
              kind: "every";
              everyMs: number;
              anchorMs?: number;
            }
          | {
              kind: "cron";
              expr: string;
              tz?: string;
              staggerMs?: number;
            };
        sessionTarget?: string;
        wakeMode?: "next-heartbeat" | "now";
        payload?:
          | {
              kind: "systemEvent";
              text?: string;
            }
          | {
              kind: "agentTurn";
              message?: string;
              model?: string;
              fallbacks?: string[];
              thinking?: string;
              timeoutSeconds?: number;
              allowUnsafeExternalContent?: boolean;
              lightContext?: boolean;
              toolsAllow?: string[] | null;
            };
        delivery?: {
          mode?: "none" | "announce" | "webhook";
          channel?: string;
          accountId?: string;
          bestEffort?: boolean;
          failureDestination?: {
            channel?: string;
            to?: string;
            accountId?: string;
            mode?: "announce" | "webhook";
          };
          to?: string;
        };
        failureAlert?:
          | false
          | {
              after?: number;
              channel?: string;
              to?: string;
              cooldownMs?: number;
              mode?: "announce" | "webhook";
              accountId?: string;
            };
        state?: {
          nextRunAtMs?: number;
          runningAtMs?: number;
          lastRunAtMs?: number;
          lastRunStatus?: "ok" | "error" | "skipped";
          lastStatus?: "ok" | "error" | "skipped";
          lastError?: string;
          lastErrorReason?:
            | "auth"
            | "format"
            | "rate_limit"
            | "billing"
            | "timeout"
            | "model_not_found"
            | "unknown";
          lastDurationMs?: number;
          consecutiveErrors?: number;
          lastDelivered?: boolean;
          lastDeliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
          lastDeliveryError?: string;
          lastFailureAlertAtMs?: number;
        };
      };
    };

export type CronUpdateResult = {
  id: string;
  agentId?: string;
  sessionKey?: string;
  name: string;
  description?: string;
  enabled: boolean;
  deleteAfterRun?: boolean;
  createdAtMs: number;
  updatedAtMs: number;
  schedule:
    | {
        kind: "at";
        at: string;
      }
    | {
        kind: "every";
        everyMs: number;
        anchorMs?: number;
      }
    | {
        kind: "cron";
        expr: string;
        tz?: string;
        staggerMs?: number;
      };
  sessionTarget: string;
  wakeMode: "next-heartbeat" | "now";
  payload:
    | {
        kind: "systemEvent";
        text: string;
      }
    | {
        kind: "agentTurn";
        message: string;
        model?: string;
        fallbacks?: string[];
        thinking?: string;
        timeoutSeconds?: number;
        allowUnsafeExternalContent?: boolean;
        lightContext?: boolean;
        toolsAllow?: string[];
      };
  delivery?:
    | {
        mode: "none";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "announce";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "webhook";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to: string;
      };
  failureAlert?:
    | false
    | {
        after?: number;
        channel?: string;
        to?: string;
        cooldownMs?: number;
        mode?: "announce" | "webhook";
        accountId?: string;
      };
  state: {
    nextRunAtMs?: number;
    runningAtMs?: number;
    lastRunAtMs?: number;
    lastRunStatus?: "ok" | "error" | "skipped";
    lastStatus?: "ok" | "error" | "skipped";
    lastError?: string;
    lastErrorReason?:
      | "auth"
      | "format"
      | "rate_limit"
      | "billing"
      | "timeout"
      | "model_not_found"
      | "unknown";
    lastDurationMs?: number;
    consecutiveErrors?: number;
    lastDelivered?: boolean;
    lastDeliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
    lastDeliveryError?: string;
    lastFailureAlertAtMs?: number;
  };
};

export type CronRemoveParams =
  | {
      id: string;
    }
  | {
      jobId: string;
    };

export interface CronRemoveResult {
  ok: boolean;
  removed: boolean;
}

export type CronRunParams =
  | {
      id: string;
      mode?: "due" | "force";
    }
  | {
      jobId: string;
      mode?: "due" | "force";
    };

export type CronRunResult = {
  ok: boolean;
  enqueued?: boolean;
  runId?: string;
  ran?: boolean;
  reason?: "already-running" | "not-due";
};

export type CronRunsParams = {
  scope?: "job" | "all";
  id?: string;
  jobId?: string;
  limit?: number;
  offset?: number;
  statuses?: ("ok" | "error" | "skipped")[];
  status?: "all" | "ok" | "error" | "skipped";
  deliveryStatuses?: ("delivered" | "not-delivered" | "unknown" | "not-requested")[];
  deliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
  query?: string;
  sortDir?: "asc" | "desc";
};

export type CronRunsResult = {
  entries: {
    ts: number;
    jobId: string;
    action: "finished";
    status?: "ok" | "error" | "skipped";
    error?: string;
    summary?: string;
    delivered?: boolean;
    deliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
    deliveryError?: string;
    sessionId?: string;
    sessionKey?: string;
    runAtMs?: number;
    durationMs?: number;
    nextRunAtMs?: number;
    model?: string;
    provider?: string;
    usage?: {
      input_tokens?: number;
      output_tokens?: number;
      total_tokens?: number;
      cache_read_tokens?: number;
      cache_write_tokens?: number;
    };
    jobName?: string;
  }[];
  total: number;
  offset: number;
  limit: number;
  hasMore: boolean;
  nextOffset: number;
};

export type ExecApprovalsGetParams = Record<string, never>;

export interface ExecApprovalsGetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export interface ExecApprovalsSetParams {
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
  baseHash?: string;
}

export interface ExecApprovalsSetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export interface ExecApprovalsNodeGetParams {
  nodeId: string;
}

export interface ExecApprovalsNodeGetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export interface ExecApprovalsNodeSetParams {
  nodeId: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
  baseHash?: string;
}

export interface ExecApprovalsNodeSetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export type ExecApprovalRequestParams = {
  id?: string;
  command?: string;
  commandArgv?: string[];
  systemRunPlan?: {
    argv: string[];
    cwd: string;
    commandText: string;
    commandPreview?: string;
    agentId: string;
    sessionKey: string;
    mutableFileOperand?: {
      argvIndex: number;
      path: string;
      sha256: string;
    } | null;
  };
  env?: Record<string, string>;
  cwd?: string;
  nodeId?: string;
  host?: string;
  security?: string;
  ask?: string;
  agentId?: string;
  resolvedPath?: string;
  sessionKey?: string;
  turnSourceChannel?: string;
  turnSourceTo?: string;
  turnSourceAccountId?: string;
  turnSourceThreadId?: string;
  timeoutMs?: number;
  twoPhase?: boolean;
};

export interface ExecApprovalRequestResult {
  id: string;
  status?: string;
  decision?: string;
  createdAtMs?: number;
  expiresAtMs?: number;
}

export interface ExecApprovalResolveParams {
  id: string;
  decision: string;
}

export interface ExecApprovalResolveResult {
  ok: true;
}

export interface ExecApprovalWaitDecisionParams {
  id: string;
}

export interface ExecApprovalWaitDecisionResult {
  id: string;
  decision?: string;
  createdAtMs?: number;
  expiresAtMs?: number;
}

export interface DoctorMemoryDreamDiaryResult {
  agentId: string;
  found: boolean;
  path: string;
  content?: string;
  updatedAtMs?: number;
}

export interface DoctorMemoryBackfillDreamDiaryResult {
  agentId: string;
  action: string;
  path?: string;
  found?: boolean;
  scannedFiles?: number;
  written?: number;
  replaced?: number;
  removedEntries?: number;
  removedShortTermEntries?: number;
  changed?: boolean;
  archiveDir?: string;
  archivedDreamsDiary?: boolean;
  archivedSessionCorpus?: boolean;
  archivedSessionIngestion?: boolean;
  warnings?: string[];
  dedupedEntries?: number;
  keptEntries?: number;
}

export interface DoctorMemoryResetDreamDiaryResult {
  agentId: string;
  action: string;
  path?: string;
  found?: boolean;
  scannedFiles?: number;
  written?: number;
  replaced?: number;
  removedEntries?: number;
  removedShortTermEntries?: number;
  changed?: boolean;
  archiveDir?: string;
  archivedDreamsDiary?: boolean;
  archivedSessionCorpus?: boolean;
  archivedSessionIngestion?: boolean;
  warnings?: string[];
  dedupedEntries?: number;
  keptEntries?: number;
}

export interface DoctorMemoryResetGroundedShortTermResult {
  agentId: string;
  action: string;
  path?: string;
  found?: boolean;
  scannedFiles?: number;
  written?: number;
  replaced?: number;
  removedEntries?: number;
  removedShortTermEntries?: number;
  changed?: boolean;
  archiveDir?: string;
  archivedDreamsDiary?: boolean;
  archivedSessionCorpus?: boolean;
  archivedSessionIngestion?: boolean;
  warnings?: string[];
  dedupedEntries?: number;
  keptEntries?: number;
}

export interface DoctorMemoryRepairDreamingArtifactsResult {
  agentId: string;
  action: string;
  path?: string;
  found?: boolean;
  scannedFiles?: number;
  written?: number;
  replaced?: number;
  removedEntries?: number;
  removedShortTermEntries?: number;
  changed?: boolean;
  archiveDir?: string;
  archivedDreamsDiary?: boolean;
  archivedSessionCorpus?: boolean;
  archivedSessionIngestion?: boolean;
  warnings?: string[];
  dedupedEntries?: number;
  keptEntries?: number;
}

export interface DoctorMemoryDedupeDreamDiaryResult {
  agentId: string;
  action: string;
  path?: string;
  found?: boolean;
  scannedFiles?: number;
  written?: number;
  replaced?: number;
  removedEntries?: number;
  removedShortTermEntries?: number;
  changed?: boolean;
  archiveDir?: string;
  archivedDreamsDiary?: boolean;
  archivedSessionCorpus?: boolean;
  archivedSessionIngestion?: boolean;
  warnings?: string[];
  dedupedEntries?: number;
  keptEntries?: number;
}

export interface PluginApprovalRequestParams {
  pluginId?: string;
  title: string;
  description: string;
  severity?: string;
  toolName?: string;
  toolCallId?: string;
  agentId?: string;
  sessionKey?: string;
  turnSourceChannel?: string;
  turnSourceTo?: string;
  turnSourceAccountId?: string;
  turnSourceThreadId?: string;
  timeoutMs?: number;
  twoPhase?: boolean;
}

export interface PluginApprovalResolveParams {
  id: string;
  decision: string;
}

export interface SessionsListParams {
  limit?: number;
  activeMinutes?: number;
  includeGlobal?: boolean;
  includeUnknown?: boolean;
  includeDerivedTitles?: boolean;
  includeLastMessage?: boolean;
  label?: string;
  spawnedBy?: string;
  agentId?: string;
  search?: string;
}

export type SessionsListResult = {
  ts: number;
  path: string;
  count: number;
  defaults: {
    modelProvider: string;
    model: string;
    contextTokens: number;
  };
  sessions: {
    key: string;
    spawnedBy?: string;
    kind: "direct" | "group" | "global" | "unknown";
    label?: string;
    displayName?: string;
    derivedTitle?: string;
    lastMessagePreview?: string;
    channel?: string;
    subject?: string;
    groupChannel?: string;
    space?: string;
    chatType?: string;
    origin?: unknown;
    updatedAt: number;
    sessionId?: string;
    systemSent?: boolean;
    abortedLastRun?: boolean;
    thinkingLevel?: string;
    fastMode?: boolean;
    verboseLevel?: string;
    reasoningLevel?: string;
    elevatedLevel?: string;
    sendPolicy?: "allow" | "deny";
    inputTokens?: number;
    outputTokens?: number;
    totalTokens?: number;
    totalTokensFresh?: boolean;
    estimatedCostUsd?: number;
    status?: "running" | "done" | "failed" | "killed" | "timeout";
    startedAt?: number;
    endedAt?: number;
    runtimeMs?: number;
    parentSessionKey?: string;
    childSessions?: string[];
    responseUsage?: "on" | "off" | "tokens" | "full";
    modelProvider?: string;
    model?: string;
    contextTokens?: number;
    deliveryContext?: {
      channel?: string;
      to?: string;
      accountId?: string;
      threadId?: string;
    };
    lastChannel?: string;
    lastTo?: string;
    lastAccountId?: string;
    compactionCount?: number;
  }[];
};

export interface SessionsSubscribeResult {
  subscribed: boolean;
}

export interface SessionsUnsubscribeResult {
  subscribed: boolean;
}

export interface SessionsMessagesSubscribeParams {
  key: string;
}

export interface SessionsMessagesSubscribeResult {
  subscribed: boolean;
  key: string;
}

export interface SessionsMessagesUnsubscribeParams {
  key: string;
}

export interface SessionsMessagesUnsubscribeResult {
  subscribed: boolean;
  key: string;
}

export interface SessionsPreviewParams {
  keys: string[];
  limit?: number;
  maxChars?: number;
}

export type SessionsPreviewResult = {
  ts: number;
  previews: {
    key: string;
    status: "ok" | "empty" | "missing" | "error";
    items: {
      role: "user" | "assistant" | "tool" | "system" | "other";
      text: string;
    }[];
  }[];
};

export interface SessionsGetParams {
  key?: string;
  sessionKey?: string;
  limit?: number;
}

export interface SessionsGetResult {
  messages: unknown[];
}

export interface SessionsCreateParams {
  key?: string;
  agentId?: string;
  label?: string;
  model?: string;
  parentSessionKey?: string;
  task?: string;
  message?: string;
}

export interface SessionsCreateResult {
  ok: boolean;
  key: string;
  sessionId: string;
  entry: Record<string, unknown>;
  runStarted: boolean;
  runId?: string;
  status?: string;
  messageSeq?: number;
  interruptedActiveRun?: boolean;
  runError?: unknown;
}

export interface SessionsSendParams {
  key: string;
  message: string;
  thinking?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  idempotencyKey?: string;
}

export type SessionsSendResult = {
  runId?: string;
  status: "started" | "in_flight";
  messageSeq?: number;
  interruptedActiveRun?: boolean;
};

export interface SessionsSteerParams {
  key: string;
  message: string;
  thinking?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  idempotencyKey?: string;
}

export type SessionsSteerResult = {
  runId?: string;
  status: "started" | "in_flight";
  messageSeq?: number;
  interruptedActiveRun?: boolean;
};

export interface SessionsAbortParams {
  key: string;
  runId?: string;
}

export type SessionsAbortResult = {
  ok: boolean;
  abortedRunId?: string;
  status: "aborted" | "no-active-run";
};

export type SessionsPatchParams = {
  key: string;
  label?: string;
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
  traceLevel?: string;
  reasoningLevel?: string;
  responseUsage?: "off" | "tokens" | "full" | "on" | null;
  elevatedLevel?: string;
  execHost?: string;
  execSecurity?: string;
  execAsk?: string;
  execNode?: string;
  model?: string;
  spawnedBy?: string;
  spawnedWorkspaceDir?: string;
  spawnDepth?: number;
  subagentRole?: "orchestrator" | "leaf" | null;
  subagentControlScope?: "children" | "none" | null;
  sendPolicy?: "allow" | "deny" | null;
  groupActivation?: "mention" | "always" | null;
};

export interface SessionsPatchResult {
  ok: true;
  path: string;
  key: string;
  entry: Record<string, unknown>;
  resolved?: {
    modelProvider?: string;
    model?: string;
  };
}

export type SessionsResetParams = {
  key: string;
  reason?: "new" | "reset";
};

export interface SessionsResetResult {
  ok: boolean;
  key: string;
  entry: Record<string, unknown>;
}

export interface SessionsClearParams {
  key: string;
}

export interface SessionsClearResult {
  ok: boolean;
  key: string;
  entry: Record<string, unknown>;
}

export interface SessionsDeleteParams {
  key: string;
  deleteTranscript?: boolean;
  emitLifecycleHooks?: boolean;
}

export interface SessionsDeleteResult {
  ok: boolean;
  key: string;
  deleted: boolean;
  archived: string[];
}

export interface SessionsCompactParams {
  key: string;
  maxLines?: number;
}

export interface SessionsCompactResult {
  ok: boolean;
  key: string;
  compacted: boolean;
  archived?: string[];
  kept?: number;
  reason?: string;
}

export interface SessionsCompactionListParams {
  key: string;
}

export type SessionsCompactionListResult = {
  ok: true;
  key: string;
  checkpoints: {
    checkpointId: string;
    sessionKey: string;
    sessionId: string;
    createdAt: number;
    reason: "manual" | "auto-threshold" | "overflow-retry" | "timeout-retry";
    tokensBefore?: number;
    tokensAfter?: number;
    summary?: string;
    firstKeptEntryId?: string;
    preCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
    postCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
  }[];
};

export interface SessionsCompactionGetParams {
  key: string;
  checkpointId: string;
}

export type SessionsCompactionGetResult = {
  ok: true;
  key: string;
  checkpoint: {
    checkpointId: string;
    sessionKey: string;
    sessionId: string;
    createdAt: number;
    reason: "manual" | "auto-threshold" | "overflow-retry" | "timeout-retry";
    tokensBefore?: number;
    tokensAfter?: number;
    summary?: string;
    firstKeptEntryId?: string;
    preCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
    postCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
  };
};

export interface SessionsCompactionBranchParams {
  key: string;
  checkpointId: string;
}

export type SessionsCompactionBranchResult = {
  ok: true;
  sourceKey: string;
  key: string;
  sessionId: string;
  checkpoint: {
    checkpointId: string;
    sessionKey: string;
    sessionId: string;
    createdAt: number;
    reason: "manual" | "auto-threshold" | "overflow-retry" | "timeout-retry";
    tokensBefore?: number;
    tokensAfter?: number;
    summary?: string;
    firstKeptEntryId?: string;
    preCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
    postCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
  };
  entry: {
    sessionId: string;
    updatedAt: number;
  };
};

export interface SessionsCompactionRestoreParams {
  key: string;
  checkpointId: string;
}

export type SessionsCompactionRestoreResult = {
  ok: true;
  key: string;
  sessionId: string;
  checkpoint: {
    checkpointId: string;
    sessionKey: string;
    sessionId: string;
    createdAt: number;
    reason: "manual" | "auto-threshold" | "overflow-retry" | "timeout-retry";
    tokensBefore?: number;
    tokensAfter?: number;
    summary?: string;
    firstKeptEntryId?: string;
    preCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
    postCompaction: {
      sessionId: string;
      sessionFile?: string;
      leafId?: string;
      entryId?: string;
    };
  };
  entry: {
    sessionId: string;
    updatedAt: number;
  };
};

export type SessionsUsageParams = {
  key?: string;
  startDate?: string;
  endDate?: string;
  mode?: "utc" | "gateway" | "specific";
  utcOffset?: string;
  limit?: number;
  includeContextWeight?: boolean;
};

export interface SessionsUsageResult {
  updatedAt: number;
  startDate: string;
  endDate: string;
  sessions: {
    key: string;
    label?: string;
    sessionId?: string;
    updatedAt?: number;
    agentId?: string;
    channel?: string;
    chatType?: string;
    origin?: unknown;
    modelOverride?: string;
    providerOverride?: string;
    modelProvider?: string;
    model?: string;
    usage: unknown;
    contextWeight?: unknown;
  }[];
  totals: unknown;
  aggregates: unknown;
}

export type SessionsUsageTimeseriesParams = {
  key?: string;
  startDate?: string;
  endDate?: string;
  mode?: "utc" | "gateway" | "specific";
  utcOffset?: string;
  limit?: number;
  includeContextWeight?: boolean;
};

export type SessionsUsageTimeseriesResult = unknown;

export type SessionsUsageLogsParams = {
  key?: string;
  startDate?: string;
  endDate?: string;
  mode?: "utc" | "gateway" | "specific";
  utcOffset?: string;
  limit?: number;
  includeContextWeight?: boolean;
};

export interface SessionsUsageLogsResult {
  logs: unknown[];
}

export interface AgentIdentityGetParams {
  agentId?: string;
  sessionKey?: string;
}

export interface AgentIdentityGetResult {
  agentId: string;
  name?: string;
  avatar?: string;
  emoji?: string;
}

export interface AgentWaitParams {
  runId: string;
  timeoutMs?: number;
}

export interface AgentWaitResult {
  runId: string;
  status: string;
  startedAt?: number;
  endedAt?: number;
  error?: string;
}

export type AgentsListParams = Record<string, never>;

export type AgentsListResult = {
  defaultId: string;
  mainKey: string;
  scope: "per-sender" | "global";
  agents: {
    id: string;
    name?: string;
    identity?: {
      name?: string;
      theme?: string;
      emoji?: string;
      avatar?: string;
      avatarUrl?: string;
    };
    workspace?: string;
    model?: {
      primary?: string;
      fallbacks?: string[];
    };
  }[];
};

export interface AgentsCreateParams {
  name: string;
  workspace: string;
  model?: string;
  emoji?: string;
  avatar?: string;
}

export interface AgentsCreateResult {
  ok: true;
  agentId: string;
  name: string;
  workspace: string;
  model?: string;
}

export interface AgentsUpdateParams {
  agentId: string;
  name?: string;
  workspace?: string;
  model?: string;
  emoji?: string;
  avatar?: string;
}

export interface AgentsUpdateResult {
  ok: true;
  agentId: string;
}

export interface AgentsDeleteParams {
  agentId: string;
  deleteFiles?: boolean;
}

export interface AgentsDeleteResult {
  ok: true;
  agentId: string;
  removedBindings: number;
}

export interface AgentsFilesListParams {
  agentId: string;
}

export interface AgentsFilesListResult {
  agentId: string;
  workspace: string;
  files: {
    name: string;
    path: string;
    missing: boolean;
    size?: number;
    updatedAtMs?: number;
    content?: string;
  }[];
}

export interface AgentsFilesGetParams {
  agentId: string;
  name: string;
}

export interface AgentsFilesGetResult {
  agentId: string;
  workspace: string;
  file: {
    name: string;
    path: string;
    missing: boolean;
    size?: number;
    updatedAtMs?: number;
    content?: string;
  };
}

export interface AgentsFilesSetParams {
  agentId: string;
  name: string;
  content: string;
}

export interface AgentsFilesSetResult {
  ok: true;
  agentId: string;
  workspace: string;
  file: {
    name: string;
    path: string;
    missing: boolean;
    size?: number;
    updatedAtMs?: number;
    content?: string;
  };
}

export type ModelsListParams = Record<string, never>;

export interface ModelsListResult {
  models: {
    id: string;
    name: string;
    provider: string;
    alias?: string;
    contextWindow?: number;
    reasoning?: boolean;
  }[];
}

export type ModelsConfiguredParams = Record<string, never>;

export interface ModelsConfiguredResult {
  models: {
    id: string;
    name: string;
    provider: string;
    contextWindow?: number;
    reasoning?: boolean;
    input?: string[];
    cost?: {
      input: number;
      output: number;
      cacheRead: number;
      cacheWrite: number;
    };
    maxTokens?: number;
    authStatus: string;
  }[];
}

export interface DeckCommandsDiscoverParams {
  agentId?: string;
}

export type DeckCommandsDiscoverResult = {
  commands: {
    name: string;
    source: "builtin" | "skill" | "plugin";
    description: string;
    args?: string;
    argChoices?: string[];
    category?: string;
    skillName?: string;
    pluginId?: string;
  }[];
  version: string;
};

export interface DeckRoutingListParams {
  agentId?: string;
  channel?: string;
  accountId?: string;
}

export interface DeckRoutingListResult {
  bindings: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  }[];
  defaultAgentId: string;
  dmScope: string;
  configHash: string;
}

export type DeckRoutingAddParams = {
  agentId: string;
  match: {
    channel: string;
    accountId?: string;
    peer?: {
      kind: "direct" | "group" | "channel";
      id: string;
    };
    guildId?: string;
    roles?: string[];
    teamId?: string;
  };
  comment?: string;
  position?: number;
  baseHash: string;
};

export interface DeckRoutingAddResult {
  ok: boolean;
  binding: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  };
  configHash: string;
  warnings: {
    type: string;
    bindingId: string;
    agentId: string;
    detail: string;
  }[];
}

export interface DeckRoutingRemoveParams {
  id: string;
  baseHash: string;
}

export interface DeckRoutingRemoveResult {
  ok: boolean;
  removed: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  };
  configHash: string;
  impact: string;
}

export type DeckRoutingValidateParams = {
  agentId: string;
  match: {
    channel: string;
    accountId?: string;
    peer?: {
      kind: "direct" | "group" | "channel";
      id: string;
    };
    guildId?: string;
    roles?: string[];
    teamId?: string;
  };
};

export interface DeckRoutingValidateResult {
  ok: boolean;
  tier: string;
  conflicts: {
    type: string;
    bindingId: string;
    agentId: string;
    detail: string;
  }[];
}

export type DeckRoutingSimulateParams = {
  channel: string;
  accountId?: string;
  peer?: {
    kind: "direct" | "group" | "channel";
    id: string;
  };
  guildId?: string;
  teamId?: string;
  memberRoleIds?: string[];
};

export interface DeckRoutingSimulateResult {
  agentId: string;
  matchedBy: string;
  sessionKey: string;
  tiers: {
    tier: string;
    matched: boolean;
    checked: boolean;
  }[];
}

export interface DeckAgentsDetailParams {
  agentId: string;
}

export type DeckAgentsDetailResult = {
  id: string;
  name?: string;
  workspace: string;
  model?: string;
  reasoningDefault?: "on" | "off" | "stream";
  fastModeDefault?: boolean;
  isDefault: boolean;
  bindingCount: number;
  sessionCount: number;
  activeSubagentCount: number;
  skillMode: string;
  effectiveSkills: string[];
  totalAvailableSkills: number;
  subagents: {
    allowAgents: string[];
    model?: string;
    effectiveMaxSpawnDepth: number;
    effectiveMaxChildrenPerAgent: number;
  };
  sandbox?: unknown;
  identityExists: boolean;
  fallbackModels?: string[];
};

export interface DeckAgentsSkillsGetParams {
  agentId: string;
}

export interface DeckAgentsSkillsGetResult {
  agentId: string;
  mode: string;
  skills: string[];
  available: {
    key: string;
    name: string;
    eligible: boolean;
    assigned: boolean;
  }[];
  configHash: string;
}

export type DeckAgentsSkillsSetParams = {
  agentId: string;
  mode: "all" | "whitelist";
  skills: string[];
  baseHash: string;
};

export interface DeckAgentsSkillsSetResult {
  ok: boolean;
  agentId: string;
  mode: string;
  skills: string[];
  configHash: string;
}

export interface DeckAgentsSubagentsGetParams {
  agentId: string;
}

export interface DeckAgentsSubagentsGetResult {
  agentId: string;
  allowAgents: string[];
  allowAny: boolean;
  model?: string;
  effectiveMaxSpawnDepth: number;
  effectiveMaxChildrenPerAgent: number;
  effectiveThinking?: unknown;
  allowedAgents: {
    id: string;
    name?: string;
  }[];
  allAgents: {
    id: string;
    name?: string;
  }[];
  configHash: string;
}

export interface DeckAgentsSubagentsSetParams {
  agentId: string;
  allowAgents: string[];
  model?: string;
  baseHash: string;
}

export interface DeckAgentsSubagentsSetResult {
  ok: boolean;
  agentId: string;
  allowAgents: string[];
  model?: string;
  configHash: string;
}

export interface DeckAgentsEventStreamsGetParams {
  agentId: string;
}

export interface DeckAgentsEventStreamsGetResult {
  agentId: string;
  eventStreams: string[];
  isDefault: boolean;
  configHash: string;
}

export interface DeckAgentsEventStreamsSetParams {
  agentId: string;
  eventStreams: string[];
  baseHash: string;
}

export interface DeckAgentsEventStreamsSetResult {
  ok: boolean;
  agentId: string;
  eventStreams: string[];
  configHash: string;
}

export interface DeckAgentsToolPolicyPreviewParams {
  agentId: string;
  context?: {
    channel?: string;
    chatType?: string;
  };
}

export interface DeckAgentsToolPolicyPreviewResult {
  layers: {
    label: string;
    ruleCount: number;
    effect: string;
  }[];
  tools: {
    name: string;
    allowed: boolean;
    decisiveLayer: string;
    trace: {
      layer: string;
      decision: string;
    }[];
  }[];
  configHash: string;
}

export interface DeckAgentsSystemPromptPreviewParams {
  agentId: string;
  context?: {
    channel?: string;
    chatType?: string;
  };
}

export interface DeckAgentsSystemPromptPreviewResult {
  layers: {
    label: string;
    source: string;
    charCount: number;
    fileCount: number;
  }[];
  bootstrapFiles: {
    name: string;
    exists: boolean;
    charCount: number;
  }[];
  totalChars: number;
  configHash: string;
}

export type DeckSubagentsListParams = {
  status?: "active" | "completed" | "failed" | "timeout" | "all";
  agentId?: string;
  requesterAgentId?: string;
  limit?: number;
  offset?: number;
};

export interface DeckSubagentsListResult {
  runs: {
    runId: string;
    childSessionKey: string;
    childAgentId: string;
    childAgentName?: string;
    requesterSessionKey: string;
    requesterAgentId: string;
    requesterAgentName?: string;
    task?: string;
    label?: string;
    model?: string;
    spawnMode: string;
    depth: number;
    createdAt: number;
    startedAt?: number;
    endedAt?: number;
    durationMs?: number;
    status: string;
    outcome?: unknown;
  }[];
  total: number;
}

export interface DeckSubagentsKillParams {
  runId: string;
}

export interface DeckSubagentsKillResult {
  ok: boolean;
  runId: string;
  childSessionKey: string;
}

export interface DeckSubagentsLineageParams {
  runId?: string;
  sessionKey?: string;
}

export interface DeckSubagentsLineageResult {
  root: {
    sessionKey: string;
    agentId: string;
    agentName?: string;
  };
  nodes: {
    runId: string;
    sessionKey: string;
    agentId: string;
    agentName?: string;
    task?: string;
    depth: number;
    parentRunId: string;
    status: string;
    durationMs?: number;
  }[];
}

export interface DeckSubagentsSteerParams {
  runId: string;
  instruction: string;
}

export interface DeckSubagentsSteerResult {
  success: boolean;
  dedupKey?: string;
  deduped?: boolean;
  newRunId?: string;
}

export type DeckIdentityListParams = Record<string, never>;

export interface DeckIdentityListResult {
  links: {
    canonical: string;
    peers: {
      channel: string;
      peerId: string;
    }[];
  }[];
  configHash: string;
}

export interface DeckIdentityLinkParams {
  canonical: string;
  channel: string;
  peerId: string;
  baseHash: string;
}

export interface DeckIdentityLinkResult {
  ok: boolean;
  configHash: string;
}

export interface DeckIdentityUnlinkParams {
  canonical: string;
  channel: string;
  peerId: string;
  baseHash: string;
}

export interface DeckIdentityUnlinkResult {
  ok: boolean;
  configHash: string;
}

export type DeckPluginsListParams = {
  capability?: "channel" | "all";
};

export type DeckPluginsListResult = {
  scope: string;
  plugins: {
    id: string;
    name: string;
    version?: string;
    origin: string;
    status: string;
    enabled: boolean;
    explicitlyEnabled?: boolean;
    activated?: boolean;
    imported?: boolean;
    activationSource?: string;
    activationReason?: string;
    configPath: string;
    capabilityKinds: string[];
    channelIds: string[];
    providerIds: string[];
    toolNames: string[];
    setupWizardSpec?: {
      steps: (
        | {
            id: string;
            type: "info";
            title: string;
            body: string;
          }
        | {
            id: string;
            type: "radio";
            title: string;
            options: {
              value: string;
              label: string;
              description?: string;
              badge?: string;
            }[];
          }
        | {
            id: string;
            type: "form";
            title: string;
            schema: {};
          }
        | {
            id: string;
            type: "action";
            title: string;
            description?: string;
            action: string;
            params?: Record<string, string>;
            successMessage?: string;
            failureMessage?: string;
          }
      )[];
      onComplete: {
        action: string;
        params?: Record<string, string>;
      };
    };
    diagnostics: {
      level: string;
      message: string;
    }[];
  }[];
};

export type DeckThreadsListParams = {
  agentId?: string;
  channel?: string;
  status?: "active" | "all";
};

export interface DeckThreadsListResult {
  threads: {
    threadId: string;
    channelId: string;
    agentId: string;
    targetSessionKey: string;
    targetKind: string;
    boundAt: number;
    lastActivityAt: number;
    accountId: string;
    boundBy: string;
    label?: string;
  }[];
}

export type DeckAuthOverviewResult = {
  providers: {
    provider: string;
    status: string;
    source: "config" | "auth-profile" | "agent-models" | "env" | "mixed";
    scope: string;
    configPresent: boolean;
    authPresent: boolean;
    editable: boolean;
    auth: {
      type: string;
      source: string;
      profileId?: string;
    } | null;
    oauth?: {
      expiresAt: number;
      remainingMs: number;
      status: string;
    };
    cooldown?: {
      reason: string;
      remainingMs: number;
      until: number;
    };
    usage?: {
      windows: {
        label: string;
        usedPercent: number;
        resetsInMs: number;
      }[];
      plan?: string;
    };
  }[];
};

export interface DeckAuthProbeResult {
  provider: string;
  model?: string;
  profileId?: string;
  label: string;
  source: string;
  mode?: string;
  status: string;
  reasonCode?: string;
  error?: string;
  latencyMs?: number;
}

export interface GatewayDescribeParams {
  filter?: string;
  includeSchemas?: boolean;
}

export interface GatewayDescribeResult {
  protocol: number;
  schemaVersion: string;
  methods: Record<
    string,
    {
      params?: Record<string, unknown>;
      result?: Record<string, unknown>;
      scope: string;
      since?: number;
    }
  >;
  events: Record<
    string,
    {
      payload?: Record<string, unknown>;
      since?: number;
    }
  >;
  untyped: string[];
}

export interface TalkConfigParams {
  includeSecrets?: boolean;
}

export interface TalkConfigResult {
  config: {
    talk?: {
      provider?: string;
      providers?: Record<
        string,
        {
          apiKey?: string;
        }
      >;
      resolved: {
        provider: string;
        config: {
          apiKey?: string;
        };
      };
      interruptOnSpeech?: boolean;
      silenceTimeoutMs?: number;
    };
    session?: {
      mainKey?: string;
    };
    ui?: {
      seamColor?: string;
    };
  };
}

export interface TalkSpeakParams {
  text: string;
  voiceId?: string;
  modelId?: string;
  outputFormat?: string;
  speed?: number;
  rateWpm?: number;
  stability?: number;
  similarity?: number;
  style?: number;
  speakerBoost?: boolean;
  seed?: number;
  normalize?: string;
  language?: string;
  latencyTier?: number;
}

export interface TalkSpeakResult {
  audioBase64: string;
  provider: string;
  outputFormat?: string;
  voiceCompatible?: boolean;
  mimeType?: string;
  fileExtension?: string;
}

export interface TalkModeParams {
  enabled: boolean;
  phase?: string;
}

export interface TalkModeResult {
  enabled: boolean;
  phase: string;
  ts: number;
}

export type WizardStartParams = {
  mode?: "local" | "remote";
  workspace?: string;
};

export type WizardStartResult = {
  sessionId: string;
  done: boolean;
  step?: {
    id: string;
    type: "note" | "select" | "text" | "confirm" | "multiselect" | "progress" | "action";
    title?: string;
    message?: string;
    options?: {
      value: unknown;
      label: string;
      hint?: string;
    }[];
    initialValue?: unknown;
    placeholder?: string;
    sensitive?: boolean;
    executor?: "gateway" | "client";
  };
  status?: "running" | "done" | "cancelled" | "error";
  error?: string;
};

export interface WizardNextParams {
  sessionId: string;
  answer?: {
    stepId: string;
    value?: unknown;
  };
}

export type WizardNextResult = {
  done: boolean;
  step?: {
    id: string;
    type: "note" | "select" | "text" | "confirm" | "multiselect" | "progress" | "action";
    title?: string;
    message?: string;
    options?: {
      value: unknown;
      label: string;
      hint?: string;
    }[];
    initialValue?: unknown;
    placeholder?: string;
    sensitive?: boolean;
    executor?: "gateway" | "client";
  };
  status?: "running" | "done" | "cancelled" | "error";
  error?: string;
};

export interface WizardCancelParams {
  sessionId: string;
}

export type WizardCancelResult = {
  status: "running" | "done" | "cancelled" | "error";
  error?: string;
};

export interface WizardStatusParams {
  sessionId: string;
}

export type WizardStatusResult = {
  status: "running" | "done" | "cancelled" | "error";
  error?: string;
};

export type DevicePairListParams = Record<string, never>;

export interface DevicePairListResult {
  pending: {
    requestId: string;
    deviceId: string;
    publicKey: string;
    displayName?: string;
    platform?: string;
    deviceFamily?: string;
    clientId?: string;
    clientMode?: string;
    role?: string;
    roles?: string[];
    scopes?: string[];
    remoteIp?: string;
    silent?: boolean;
    isRepair?: boolean;
    ts: number;
  }[];
  paired: {
    deviceId: string;
    publicKey: string;
    displayName?: string;
    platform?: string;
    deviceFamily?: string;
    clientId?: string;
    clientMode?: string;
    role?: string;
    roles?: string[];
    scopes?: string[];
    remoteIp?: string;
    createdAtMs: number;
    approvedAtMs: number;
    tokens?: {
      role: string;
      scopes: string[];
      createdAtMs: number;
      rotatedAtMs?: number;
      revokedAtMs?: number;
      lastUsedAtMs?: number;
    }[];
  }[];
}

export interface DevicePairApproveParams {
  requestId: string;
}

export interface DevicePairApproveResult {
  requestId: string;
  device: {
    deviceId: string;
    publicKey: string;
    displayName?: string;
    platform?: string;
    deviceFamily?: string;
    clientId?: string;
    clientMode?: string;
    role?: string;
    roles?: string[];
    scopes?: string[];
    remoteIp?: string;
    createdAtMs: number;
    approvedAtMs: number;
    tokens?: {
      role: string;
      scopes: string[];
      createdAtMs: number;
      rotatedAtMs?: number;
      revokedAtMs?: number;
      lastUsedAtMs?: number;
    }[];
  };
}

export interface DevicePairRejectParams {
  requestId: string;
}

export interface DevicePairRejectResult {
  requestId: string;
  deviceId: string;
}

export interface DevicePairRemoveParams {
  deviceId: string;
}

export interface DevicePairRemoveResult {
  deviceId: string;
}

export interface DeviceTokenRotateParams {
  deviceId: string;
  role: string;
  scopes?: string[];
}

export interface DeviceTokenRotateResult {
  deviceId: string;
  role: string;
  token: string;
  scopes: string[];
  rotatedAtMs: number;
}

export interface DeviceTokenRevokeParams {
  deviceId: string;
  role: string;
}

export interface DeviceTokenRevokeResult {
  deviceId: string;
  role: string;
  revokedAtMs: number;
}

export type NodeListParams = Record<string, never>;

export interface NodeListResult {
  ts: number;
  nodes: {
    nodeId: string;
    displayName?: string;
    platform?: string;
    version?: string;
    coreVersion?: string;
    uiVersion?: string;
    deviceFamily?: string;
    modelIdentifier?: string;
    remoteIp?: string;
    caps: string[];
    commands: string[];
    pathEnv?: string;
    permissions?: Record<string, boolean>;
    connectedAtMs?: number;
    paired: boolean;
    connected: boolean;
  }[];
}

export interface NodeDescribeParams {
  nodeId: string;
}

export interface NodeDescribeResult {
  ts: number;
  nodeId: string;
  displayName?: string;
  platform?: string;
  version?: string;
  coreVersion?: string;
  uiVersion?: string;
  deviceFamily?: string;
  modelIdentifier?: string;
  remoteIp?: string;
  caps: string[];
  commands: string[];
  pathEnv?: string;
  permissions?: Record<string, boolean>;
  connectedAtMs?: number;
  paired: boolean;
  connected: boolean;
}

export type NodePairListParams = Record<string, never>;

export interface NodePairListResult {
  pending: {
    requestId: string;
    nodeId: string;
    displayName?: string;
    platform?: string;
    version?: string;
    coreVersion?: string;
    uiVersion?: string;
    deviceFamily?: string;
    modelIdentifier?: string;
    caps?: string[];
    commands?: string[];
    remoteIp?: string;
    silent?: boolean;
    isRepair?: boolean;
    ts: number;
  }[];
  paired: {
    nodeId: string;
    displayName?: string;
    platform?: string;
    version?: string;
    coreVersion?: string;
    uiVersion?: string;
    deviceFamily?: string;
    modelIdentifier?: string;
    caps?: string[];
    commands?: string[];
    remoteIp?: string;
    token: string;
    bins?: string[];
    createdAtMs: number;
    approvedAtMs: number;
    lastConnectedAtMs?: number;
  }[];
}

export interface NodePairRequestParams {
  nodeId: string;
  displayName?: string;
  platform?: string;
  version?: string;
  coreVersion?: string;
  uiVersion?: string;
  deviceFamily?: string;
  modelIdentifier?: string;
  caps?: string[];
  commands?: string[];
  remoteIp?: string;
  silent?: boolean;
}

export interface NodePairRequestResult {
  status: string;
  request: {
    requestId: string;
    nodeId: string;
    displayName?: string;
    platform?: string;
    version?: string;
    coreVersion?: string;
    uiVersion?: string;
    deviceFamily?: string;
    modelIdentifier?: string;
    caps?: string[];
    commands?: string[];
    remoteIp?: string;
    silent?: boolean;
    isRepair?: boolean;
    ts: number;
  };
  created: boolean;
}

export interface NodePairApproveParams {
  requestId: string;
}

export interface NodePairApproveResult {
  requestId: string;
  node: {
    nodeId: string;
    displayName?: string;
    platform?: string;
    version?: string;
    coreVersion?: string;
    uiVersion?: string;
    deviceFamily?: string;
    modelIdentifier?: string;
    caps?: string[];
    commands?: string[];
    remoteIp?: string;
    token: string;
    bins?: string[];
    createdAtMs: number;
    approvedAtMs: number;
    lastConnectedAtMs?: number;
  };
}

export interface NodePairRejectParams {
  requestId: string;
}

export interface NodePairRejectResult {
  requestId: string;
  nodeId: string;
}

export interface NodePairVerifyParams {
  nodeId: string;
  token: string;
}

export interface NodePairVerifyResult {
  ok: boolean;
  node?: {
    nodeId: string;
    displayName?: string;
    platform?: string;
    version?: string;
    coreVersion?: string;
    uiVersion?: string;
    deviceFamily?: string;
    modelIdentifier?: string;
    caps?: string[];
    commands?: string[];
    remoteIp?: string;
    token: string;
    bins?: string[];
    createdAtMs: number;
    approvedAtMs: number;
    lastConnectedAtMs?: number;
  };
}

export interface NodeRenameParams {
  nodeId: string;
  displayName: string;
}

export interface NodeRenameResult {
  nodeId: string;
  displayName: string;
}

export interface GatewayMethodMap {
  "chat.history": { params: ChatHistoryParams; result: ChatHistoryResult };
  "chat.abort": { params: ChatAbortParams; result: ChatAbortResult };
  "chat.send": { params: ChatSendParams; result: ChatSendResult };
  "config.get": { params: ConfigGetParams; result: ConfigGetResult };
  "config.schema": { params: ConfigSchemaParams; result: ConfigSchemaResult };
  "config.schema.lookup": { params: ConfigSchemaLookupParams; result: ConfigSchemaLookupResult };
  "config.apply": { params: ConfigApplyParams; result: ConfigApplyResult };
  "config.patch": { params: ConfigPatchParams; result: ConfigPatchResult };
  "config.set": { params: ConfigSetParams; result: ConfigSetResult };
  "channels.status": { params: ChannelsStatusParams; result: ChannelsStatusResult };
  "channels.logout": { params: ChannelsLogoutParams; result: ChannelsLogoutResult };
  "doctor.memory.status": { params: Record<string, unknown>; result: DoctorMemoryStatusResult };
  health: { params: Record<string, unknown>; result: HealthResult };
  status: { params: Record<string, unknown>; result: StatusResult };
  "usage.status": { params: Record<string, unknown>; result: UsageStatusResult };
  "usage.cost": { params: Record<string, unknown>; result: UsageCostResult };
  "models.catalog.providers": {
    params: Record<string, unknown>;
    result: ModelsCatalogProvidersResult;
  };
  "skills.status": { params: SkillsStatusParams; result: SkillsStatusResult };
  "skills.bins": { params: SkillsBinsParams; result: SkillsBinsResult };
  "skills.install": { params: SkillsInstallParams; result: SkillsInstallResult };
  "skills.update": { params: SkillsUpdateParams; result: SkillsUpdateResult };
  "skills.search": { params: SkillsSearchParams; result: SkillsSearchResult };
  "skills.detail": { params: SkillsDetailParams; result: SkillsDetailResult };
  "cron.list": { params: CronListParams; result: CronListResult };
  "cron.status": { params: CronStatusParams; result: CronStatusResult };
  "cron.add": { params: CronAddParams; result: CronAddResult };
  "cron.update": { params: CronUpdateParams; result: CronUpdateResult };
  "cron.remove": { params: CronRemoveParams; result: CronRemoveResult };
  "cron.run": { params: CronRunParams; result: CronRunResult };
  "cron.runs": { params: CronRunsParams; result: CronRunsResult };
  "exec.approvals.get": { params: ExecApprovalsGetParams; result: ExecApprovalsGetResult };
  "exec.approvals.set": { params: ExecApprovalsSetParams; result: ExecApprovalsSetResult };
  "exec.approvals.node.get": {
    params: ExecApprovalsNodeGetParams;
    result: ExecApprovalsNodeGetResult;
  };
  "exec.approvals.node.set": {
    params: ExecApprovalsNodeSetParams;
    result: ExecApprovalsNodeSetResult;
  };
  "exec.approval.request": { params: ExecApprovalRequestParams; result: ExecApprovalRequestResult };
  "exec.approval.resolve": { params: ExecApprovalResolveParams; result: ExecApprovalResolveResult };
  "exec.approval.waitDecision": {
    params: ExecApprovalWaitDecisionParams;
    result: ExecApprovalWaitDecisionResult;
  };
  "doctor.memory.dreamDiary": {
    params: Record<string, unknown>;
    result: DoctorMemoryDreamDiaryResult;
  };
  "doctor.memory.backfillDreamDiary": {
    params: Record<string, unknown>;
    result: DoctorMemoryBackfillDreamDiaryResult;
  };
  "doctor.memory.resetDreamDiary": {
    params: Record<string, unknown>;
    result: DoctorMemoryResetDreamDiaryResult;
  };
  "doctor.memory.resetGroundedShortTerm": {
    params: Record<string, unknown>;
    result: DoctorMemoryResetGroundedShortTermResult;
  };
  "doctor.memory.repairDreamingArtifacts": {
    params: Record<string, unknown>;
    result: DoctorMemoryRepairDreamingArtifactsResult;
  };
  "doctor.memory.dedupeDreamDiary": {
    params: Record<string, unknown>;
    result: DoctorMemoryDedupeDreamDiaryResult;
  };
  "plugin.approval.request": { params: PluginApprovalRequestParams; result: unknown };
  "plugin.approval.resolve": { params: PluginApprovalResolveParams; result: unknown };
  "sessions.list": { params: SessionsListParams; result: SessionsListResult };
  "sessions.subscribe": { params: Record<string, unknown>; result: SessionsSubscribeResult };
  "sessions.unsubscribe": { params: Record<string, unknown>; result: SessionsUnsubscribeResult };
  "sessions.messages.subscribe": {
    params: SessionsMessagesSubscribeParams;
    result: SessionsMessagesSubscribeResult;
  };
  "sessions.messages.unsubscribe": {
    params: SessionsMessagesUnsubscribeParams;
    result: SessionsMessagesUnsubscribeResult;
  };
  "sessions.preview": { params: SessionsPreviewParams; result: SessionsPreviewResult };
  "sessions.get": { params: SessionsGetParams; result: SessionsGetResult };
  "sessions.create": { params: SessionsCreateParams; result: SessionsCreateResult };
  "sessions.send": { params: SessionsSendParams; result: SessionsSendResult };
  "sessions.steer": { params: SessionsSteerParams; result: SessionsSteerResult };
  "sessions.abort": { params: SessionsAbortParams; result: SessionsAbortResult };
  "sessions.patch": { params: SessionsPatchParams; result: SessionsPatchResult };
  "sessions.reset": { params: SessionsResetParams; result: SessionsResetResult };
  "sessions.clear": { params: SessionsClearParams; result: SessionsClearResult };
  "sessions.delete": { params: SessionsDeleteParams; result: SessionsDeleteResult };
  "sessions.compact": { params: SessionsCompactParams; result: SessionsCompactResult };
  "sessions.compaction.list": {
    params: SessionsCompactionListParams;
    result: SessionsCompactionListResult;
  };
  "sessions.compaction.get": {
    params: SessionsCompactionGetParams;
    result: SessionsCompactionGetResult;
  };
  "sessions.compaction.branch": {
    params: SessionsCompactionBranchParams;
    result: SessionsCompactionBranchResult;
  };
  "sessions.compaction.restore": {
    params: SessionsCompactionRestoreParams;
    result: SessionsCompactionRestoreResult;
  };
  "sessions.usage": { params: SessionsUsageParams; result: SessionsUsageResult };
  "sessions.usage.timeseries": {
    params: SessionsUsageTimeseriesParams;
    result: SessionsUsageTimeseriesResult;
  };
  "sessions.usage.logs": { params: SessionsUsageLogsParams; result: SessionsUsageLogsResult };
  "agent.identity.get": { params: AgentIdentityGetParams; result: AgentIdentityGetResult };
  "agent.wait": { params: AgentWaitParams; result: AgentWaitResult };
  "agents.list": { params: AgentsListParams; result: AgentsListResult };
  "agents.create": { params: AgentsCreateParams; result: AgentsCreateResult };
  "agents.update": { params: AgentsUpdateParams; result: AgentsUpdateResult };
  "agents.delete": { params: AgentsDeleteParams; result: AgentsDeleteResult };
  "agents.files.list": { params: AgentsFilesListParams; result: AgentsFilesListResult };
  "agents.files.get": { params: AgentsFilesGetParams; result: AgentsFilesGetResult };
  "agents.files.set": { params: AgentsFilesSetParams; result: AgentsFilesSetResult };
  "models.list": { params: ModelsListParams; result: ModelsListResult };
  "models.configured": { params: ModelsConfiguredParams; result: ModelsConfiguredResult };
  "deck.commands.discover": {
    params: DeckCommandsDiscoverParams;
    result: DeckCommandsDiscoverResult;
  };
  "deck.routing.list": { params: DeckRoutingListParams; result: DeckRoutingListResult };
  "deck.routing.add": { params: DeckRoutingAddParams; result: DeckRoutingAddResult };
  "deck.routing.remove": { params: DeckRoutingRemoveParams; result: DeckRoutingRemoveResult };
  "deck.routing.validate": { params: DeckRoutingValidateParams; result: DeckRoutingValidateResult };
  "deck.routing.simulate": { params: DeckRoutingSimulateParams; result: DeckRoutingSimulateResult };
  "deck.agents.detail": { params: DeckAgentsDetailParams; result: DeckAgentsDetailResult };
  "deck.agents.skills.get": {
    params: DeckAgentsSkillsGetParams;
    result: DeckAgentsSkillsGetResult;
  };
  "deck.agents.skills.set": {
    params: DeckAgentsSkillsSetParams;
    result: DeckAgentsSkillsSetResult;
  };
  "deck.agents.subagents.get": {
    params: DeckAgentsSubagentsGetParams;
    result: DeckAgentsSubagentsGetResult;
  };
  "deck.agents.subagents.set": {
    params: DeckAgentsSubagentsSetParams;
    result: DeckAgentsSubagentsSetResult;
  };
  "deck.agents.eventStreams.get": {
    params: DeckAgentsEventStreamsGetParams;
    result: DeckAgentsEventStreamsGetResult;
  };
  "deck.agents.eventStreams.set": {
    params: DeckAgentsEventStreamsSetParams;
    result: DeckAgentsEventStreamsSetResult;
  };
  "deck.agents.toolPolicy.preview": {
    params: DeckAgentsToolPolicyPreviewParams;
    result: DeckAgentsToolPolicyPreviewResult;
  };
  "deck.agents.systemPrompt.preview": {
    params: DeckAgentsSystemPromptPreviewParams;
    result: DeckAgentsSystemPromptPreviewResult;
  };
  "deck.subagents.list": { params: DeckSubagentsListParams; result: DeckSubagentsListResult };
  "deck.subagents.kill": { params: DeckSubagentsKillParams; result: DeckSubagentsKillResult };
  "deck.subagents.lineage": {
    params: DeckSubagentsLineageParams;
    result: DeckSubagentsLineageResult;
  };
  "deck.subagents.steer": { params: DeckSubagentsSteerParams; result: DeckSubagentsSteerResult };
  "deck.identity.list": { params: DeckIdentityListParams; result: DeckIdentityListResult };
  "deck.identity.link": { params: DeckIdentityLinkParams; result: DeckIdentityLinkResult };
  "deck.identity.unlink": { params: DeckIdentityUnlinkParams; result: DeckIdentityUnlinkResult };
  "deck.plugins.list": { params: DeckPluginsListParams; result: DeckPluginsListResult };
  "deck.threads.list": { params: DeckThreadsListParams; result: DeckThreadsListResult };
  "deck.auth.overview": { params: Record<string, unknown>; result: DeckAuthOverviewResult };
  "deck.auth.probe": { params: Record<string, unknown>; result: DeckAuthProbeResult };
  "gateway.describe": { params: GatewayDescribeParams; result: GatewayDescribeResult };
  "talk.config": { params: TalkConfigParams; result: TalkConfigResult };
  "talk.speak": { params: TalkSpeakParams; result: TalkSpeakResult };
  "talk.mode": { params: TalkModeParams; result: TalkModeResult };
  "wizard.start": { params: WizardStartParams; result: WizardStartResult };
  "wizard.next": { params: WizardNextParams; result: WizardNextResult };
  "wizard.cancel": { params: WizardCancelParams; result: WizardCancelResult };
  "wizard.status": { params: WizardStatusParams; result: WizardStatusResult };
  "device.pair.list": { params: DevicePairListParams; result: DevicePairListResult };
  "device.pair.approve": { params: DevicePairApproveParams; result: DevicePairApproveResult };
  "device.pair.reject": { params: DevicePairRejectParams; result: DevicePairRejectResult };
  "device.pair.remove": { params: DevicePairRemoveParams; result: DevicePairRemoveResult };
  "device.token.rotate": { params: DeviceTokenRotateParams; result: DeviceTokenRotateResult };
  "device.token.revoke": { params: DeviceTokenRevokeParams; result: DeviceTokenRevokeResult };
  "node.list": { params: NodeListParams; result: NodeListResult };
  "node.describe": { params: NodeDescribeParams; result: NodeDescribeResult };
  "node.pair.list": { params: NodePairListParams; result: NodePairListResult };
  "node.pair.request": { params: NodePairRequestParams; result: NodePairRequestResult };
  "node.pair.approve": { params: NodePairApproveParams; result: NodePairApproveResult };
  "node.pair.reject": { params: NodePairRejectParams; result: NodePairRejectResult };
  "node.pair.verify": { params: NodePairVerifyParams; result: NodePairVerifyResult };
  "node.rename": { params: NodeRenameParams; result: NodeRenameResult };
}

export type GatewayMethodName = keyof GatewayMethodMap;

export type ChatEventPayload = {
  runId: string;
  sessionKey: string;
  seq: number;
  state: "delta" | "final" | "aborted" | "error";
  message?: {
    id?: string;
    role: "user" | "assistant" | "system";
    content: (
      | {
          type: "text";
          text: string;
        }
      | {
          type: "thinking";
          text: string;
        }
      | {
          type: "tool_use";
          id: string;
          name: string;
          input: Record<string, unknown>;
        }
      | {
          type: "tool_result";
          toolUseId: string;
          content: string;
          isError?: boolean;
        }
      | {
          type: "image";
          data: string;
          mimeType: string;
          fileName?: string;
        }
      | {
          type: "file";
          data: string;
          mimeType: string;
          fileName: string;
          size?: number;
        }
    )[];
    timestamp: number;
  };
  errorMessage?: string;
  errorKind?: "refusal" | "timeout" | "rate_limit" | "context_length" | "unknown";
  usage?: unknown;
  stopReason?: string;
  mediaUrl?: string;
  mediaUrls?: string[];
  mediaType?: string;
};

export interface AgentEventPayload {
  runId: string;
  seq: number;
  stream: string;
  ts: number;
  data: Record<string, unknown>;
}

export type SessionMessageEventPayload = {
  sessionKey: string;
  message: {
    id?: string;
    role: "user" | "assistant" | "system";
    content: (
      | {
          type: "text";
          text: string;
        }
      | {
          type: "thinking";
          text: string;
        }
      | {
          type: "tool_use";
          id: string;
          name: string;
          input: Record<string, unknown>;
        }
      | {
          type: "tool_result";
          toolUseId: string;
          content: string;
          isError?: boolean;
        }
      | {
          type: "image";
          data: string;
          mimeType: string;
          fileName?: string;
        }
      | {
          type: "file";
          data: string;
          mimeType: string;
          fileName: string;
          size?: number;
        }
    )[];
    timestamp: number;
  };
  messageId?: string;
  messageSeq?: number;
  updatedAt?: number;
  sessionId?: string;
  kind?: "direct" | "group" | "global" | "unknown";
  channel?: string;
  label?: string;
  displayName?: string;
  deliveryContext?: {
    channel?: string;
    to?: string;
    accountId?: string;
    threadId?: string;
  };
  parentSessionKey?: string;
  childSessions?: string[];
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
  systemSent?: boolean;
  abortedLastRun?: boolean;
  lastChannel?: string;
  lastTo?: string;
  lastAccountId?: string;
  totalTokens?: number;
  totalTokensFresh?: boolean;
  contextTokens?: number;
  estimatedCostUsd?: number;
  modelProvider?: string;
  model?: string;
  status?: "running" | "done" | "failed" | "killed" | "timeout";
  startedAt?: number;
  endedAt?: number;
  runtimeMs?: number;
};

export interface SessionToolEventPayload {
  runId: string;
  seq: number;
  stream: "tool";
  ts: number;
  sessionKey: string;
  data: {
    phase: string;
    name?: string;
    toolCallId?: string;
    args?: Record<string, unknown>;
    result?: string;
    partialResult?: string;
    isError?: boolean;
    error?: string;
  };
}

export type SessionsChangedEventPayload = {
  sessionKey: string;
  phase?: string;
  ts: number;
  runId?: string;
  messageId?: string;
  messageSeq?: number;
  reason?: string;
  parentSessionKey?: unknown;
  label?: unknown;
  displayName?: unknown;
  updatedAt?: number;
  sessionId?: string;
  kind?: "direct" | "group" | "global" | "unknown";
  channel?: string;
  deliveryContext?: {
    channel?: string;
    to?: string;
    accountId?: string;
    threadId?: string;
  };
  childSessions?: string[];
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
  systemSent?: boolean;
  abortedLastRun?: boolean;
  lastChannel?: string;
  lastTo?: string;
  lastAccountId?: string;
  totalTokens?: number;
  totalTokensFresh?: boolean;
  contextTokens?: number;
  estimatedCostUsd?: number;
  modelProvider?: string;
  model?: string;
  status?: "running" | "done" | "failed" | "killed" | "timeout";
  startedAt?: number;
  endedAt?: number;
  runtimeMs?: number;
};

export interface GatewayEventPayloadMap {
  chat: ChatEventPayload;
  agent: AgentEventPayload;
  "session.message": SessionMessageEventPayload;
  "session.tool": SessionToolEventPayload;
  "sessions.changed": SessionsChangedEventPayload;
}

export type GatewayTypedEventName = keyof GatewayEventPayloadMap;
