// Auto-generated by scripts/protocol-gen-ts.ts — DO NOT EDIT

export const GENERATED_SCHEMA_VERSION = "3";

export interface ChatHistoryParams {
  sessionKey: string;
  limit?: number;
}

export interface ChatHistoryResult {
  sessionKey: string;
  sessionId: string;
  messages: {
    id?: string;
    role?: string;
    content?: unknown;
    timestamp?: number;
  }[];
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
}

export interface ChatAbortParams {
  sessionKey: string;
  runId?: string;
}

export interface ChatAbortResult {
  ok: boolean;
  aborted: boolean;
  runIds: string[];
}

export interface ChatSendParams {
  sessionKey: string;
  message: string;
  thinking?: string;
  deliver?: boolean;
  attachments?: unknown[];
  timeoutMs?: number;
  systemInputProvenance?: {
    kind: string;
    originSessionId?: string;
    sourceSessionKey?: string;
    sourceChannel?: string;
    sourceTool?: string;
  };
  systemProvenanceReceipt?: string;
  idempotencyKey: string;
}

export interface ChatSendResult {
  ok?: boolean;
  aborted?: boolean;
  runIds?: string[];
  runId?: string;
  status?: string;
}

export interface SessionsListParams {
  limit?: number;
  activeMinutes?: number;
  includeGlobal?: boolean;
  includeUnknown?: boolean;
  includeDerivedTitles?: boolean;
  includeLastMessage?: boolean;
  label?: string;
  spawnedBy?: string;
  agentId?: string;
  search?: string;
}

export type SessionsListResult = {
  ts: number;
  path: string;
  count: number;
  defaults: {
    modelProvider: string | null;
    model: string | null;
    contextTokens: number | null;
  };
  sessions: {
    key: string;
    spawnedBy?: string;
    kind: "direct" | "group" | "global" | "unknown";
    label?: string;
    displayName?: string;
    derivedTitle?: string;
    lastMessagePreview?: string;
    channel?: string;
    subject?: string;
    groupChannel?: string;
    space?: string;
    chatType?: string;
    origin?: unknown;
    updatedAt: number | null;
    sessionId?: string;
    systemSent?: boolean;
    abortedLastRun?: boolean;
    thinkingLevel?: string;
    fastMode?: boolean;
    verboseLevel?: string;
    reasoningLevel?: string;
    elevatedLevel?: string;
    sendPolicy?: "allow" | "deny";
    inputTokens?: number;
    outputTokens?: number;
    totalTokens?: number;
    totalTokensFresh?: boolean;
    estimatedCostUsd?: number;
    status?: "running" | "done" | "failed" | "killed" | "timeout";
    startedAt?: number;
    endedAt?: number;
    runtimeMs?: number;
    parentSessionKey?: string;
    childSessions?: string[];
    responseUsage?: "on" | "off" | "tokens" | "full";
    modelProvider?: string;
    model?: string;
    contextTokens?: number;
    deliveryContext?: {
      channel?: string;
      to?: string;
      accountId?: string;
      threadId?: string | number;
    };
    lastChannel?: string;
    lastTo?: string;
    lastAccountId?: string;
    compactionCount?: number;
  }[];
};

export interface SessionsSubscribeResult {
  subscribed: boolean;
}

export interface SessionsUnsubscribeResult {
  subscribed: boolean;
}

export interface SessionsMessagesSubscribeParams {
  key: string;
}

export interface SessionsMessagesSubscribeResult {
  subscribed: boolean;
  key: string;
}

export interface SessionsMessagesUnsubscribeParams {
  key: string;
}

export interface SessionsMessagesUnsubscribeResult {
  subscribed: boolean;
  key: string;
}

export interface SessionsPreviewParams {
  keys: string[];
  limit?: number;
  maxChars?: number;
}

export type SessionsPreviewResult = {
  ts: number;
  previews: {
    key: string;
    status: "ok" | "empty" | "missing" | "error";
    items: {
      role: "user" | "assistant" | "tool" | "system" | "other";
      text: string;
    }[];
  }[];
};

export interface SessionsCreateParams {
  key?: string;
  agentId?: string;
  label?: string;
  model?: string;
  parentSessionKey?: string;
  task?: string;
  message?: string;
}

export interface SessionsCreateResult {
  ok: boolean;
  key: string;
  sessionId: string;
  entry: Record<string, unknown>;
  runStarted: boolean;
  runId?: string;
  status?: string;
  messageSeq?: number;
  interruptedActiveRun?: boolean;
  runError?: unknown;
}

export interface SessionsSendParams {
  key: string;
  message: string;
  thinking?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  idempotencyKey?: string;
}

export type SessionsSendResult = {
  runId?: string;
  status: "started" | "in_flight";
  messageSeq?: number;
  interruptedActiveRun?: boolean;
};

export interface SessionsSteerParams {
  key: string;
  message: string;
  thinking?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  idempotencyKey?: string;
}

export type SessionsSteerResult = {
  runId?: string;
  status: "started" | "in_flight";
  messageSeq?: number;
  interruptedActiveRun?: boolean;
};

export interface SessionsAbortParams {
  key: string;
  runId?: string;
}

export type SessionsAbortResult = {
  ok: boolean;
  abortedRunId?: string | null;
  status: "aborted" | "no-active-run";
};

export type SessionsPatchParams = {
  key: string;
  label?: string | null;
  thinkingLevel?: string | null;
  fastMode?: boolean | null;
  verboseLevel?: string | null;
  reasoningLevel?: string | null;
  responseUsage?: "off" | "tokens" | "full" | "on" | null;
  elevatedLevel?: string | null;
  execHost?: string | null;
  execSecurity?: string | null;
  execAsk?: string | null;
  execNode?: string | null;
  model?: string | null;
  spawnedBy?: string | null;
  spawnedWorkspaceDir?: string | null;
  spawnDepth?: number | null;
  subagentRole?: "orchestrator" | "leaf" | null;
  subagentControlScope?: "children" | "none" | null;
  sendPolicy?: "allow" | "deny" | null;
  groupActivation?: "mention" | "always" | null;
};

export interface SessionsPatchResult {
  ok: true;
  path: string;
  key: string;
  entry: Record<string, unknown>;
  resolved?: {
    modelProvider?: string;
    model?: string;
  };
}

export type SessionsResetParams = {
  key: string;
  reason?: "new" | "reset";
};

export interface SessionsResetResult {
  ok: boolean;
  key: string;
  entry: Record<string, unknown>;
}

export interface SessionsClearParams {
  key: string;
}

export interface SessionsClearResult {
  ok: boolean;
  key: string;
  entry: Record<string, unknown>;
}

export interface SessionsDeleteParams {
  key: string;
  deleteTranscript?: boolean;
  emitLifecycleHooks?: boolean;
}

export interface SessionsDeleteResult {
  ok: boolean;
  key: string;
  deleted: boolean;
  archived: string[];
}

export interface SessionsCompactParams {
  key: string;
  maxLines?: number;
}

export interface SessionsCompactResult {
  ok: boolean;
  key: string;
  compacted: boolean;
  archived?: string[];
  kept?: number;
  reason?: string;
}

export type SessionsUsageParams = {
  key?: string;
  startDate?: string;
  endDate?: string;
  mode?: "utc" | "gateway" | "specific";
  utcOffset?: string;
  limit?: number;
  includeContextWeight?: boolean;
};

export type SessionsUsageResult = {
  updatedAt: number;
  startDate: string;
  endDate: string;
  sessions: {
    key: string;
    label?: string;
    sessionId?: string;
    updatedAt?: number;
    agentId?: string;
    channel?: string;
    chatType?: string;
    origin?: {
      label?: string;
      provider?: string;
      surface?: string;
      chatType?: string;
      from?: string;
      to?: string;
      accountId?: string;
      threadId?: string | number;
    };
    modelOverride?: string;
    providerOverride?: string;
    modelProvider?: string;
    model?: string;
    usage: {
      input: number;
      output: number;
      cacheRead: number;
      cacheWrite: number;
      totalTokens: number;
      totalCost: number;
      inputCost: number;
      outputCost: number;
      cacheReadCost: number;
      cacheWriteCost: number;
      missingCostEntries: number;
      sessionId?: string;
      sessionFile?: string;
      firstActivity?: number;
      lastActivity?: number;
      durationMs?: number;
      activityDates?: string[];
      dailyBreakdown?: {
        date: string;
        tokens: number;
        cost: number;
      }[];
      dailyMessageCounts?: {
        date: string;
        total: number;
        user: number;
        assistant: number;
        toolCalls: number;
        toolResults: number;
        errors: number;
      }[];
      dailyLatency?: {
        date: string;
        count: number;
        avgMs: number;
        p95Ms: number;
        minMs: number;
        maxMs: number;
      }[];
      dailyModelUsage?: {
        date: string;
        provider?: string;
        model?: string;
        tokens: number;
        cost: number;
        count: number;
      }[];
      messageCounts?: {
        total: number;
        user: number;
        assistant: number;
        toolCalls: number;
        toolResults: number;
        errors: number;
      };
      toolUsage?: {
        totalCalls: number;
        uniqueTools: number;
        tools: {
          name: string;
          count: number;
        }[];
      };
      modelUsage?: {
        provider?: string;
        model?: string;
        count: number;
        totals: {
          input: number;
          output: number;
          cacheRead: number;
          cacheWrite: number;
          totalTokens: number;
          totalCost: number;
          inputCost: number;
          outputCost: number;
          cacheReadCost: number;
          cacheWriteCost: number;
          missingCostEntries: number;
        };
      }[];
      latency?: {
        count: number;
        avgMs: number;
        p95Ms: number;
        minMs: number;
        maxMs: number;
      };
    } | null;
    contextWeight?: {
      source: "run" | "estimate";
      generatedAt: number;
      sessionId?: string;
      sessionKey?: string;
      provider?: string;
      model?: string;
      workspaceDir?: string;
      bootstrapMaxChars?: number;
      bootstrapTotalMaxChars?: number;
      bootstrapTruncation?: {
        warningMode?: "off" | "once" | "always";
        warningShown?: boolean;
        promptWarningSignature?: string;
        warningSignaturesSeen?: string[];
        truncatedFiles?: number;
        nearLimitFiles?: number;
        totalNearLimit?: boolean;
      };
      sandbox?: {
        mode?: string;
        sandboxed?: boolean;
      };
      systemPrompt: {
        chars: number;
        projectContextChars: number;
        nonProjectContextChars: number;
      };
      injectedWorkspaceFiles: {
        name: string;
        path: string;
        missing: boolean;
        rawChars: number;
        injectedChars: number;
        truncated: boolean;
      }[];
      skills: {
        promptChars: number;
        entries: {
          name: string;
          blockChars: number;
        }[];
      };
      tools: {
        listChars: number;
        schemaChars: number;
        entries: {
          name: string;
          summaryChars: number;
          schemaChars: number;
          propertiesCount?: number | null;
        }[];
      };
    } | null;
  }[];
  totals: {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
    totalTokens: number;
    totalCost: number;
    inputCost: number;
    outputCost: number;
    cacheReadCost: number;
    cacheWriteCost: number;
    missingCostEntries: number;
  };
  aggregates: {
    messages: {
      total: number;
      user: number;
      assistant: number;
      toolCalls: number;
      toolResults: number;
      errors: number;
    };
    tools: {
      totalCalls: number;
      uniqueTools: number;
      tools: {
        name: string;
        count: number;
      }[];
    };
    byModel: {
      provider?: string;
      model?: string;
      count: number;
      totals: {
        input: number;
        output: number;
        cacheRead: number;
        cacheWrite: number;
        totalTokens: number;
        totalCost: number;
        inputCost: number;
        outputCost: number;
        cacheReadCost: number;
        cacheWriteCost: number;
        missingCostEntries: number;
      };
    }[];
    byProvider: {
      provider?: string;
      model?: string;
      count: number;
      totals: {
        input: number;
        output: number;
        cacheRead: number;
        cacheWrite: number;
        totalTokens: number;
        totalCost: number;
        inputCost: number;
        outputCost: number;
        cacheReadCost: number;
        cacheWriteCost: number;
        missingCostEntries: number;
      };
    }[];
    byAgent: {
      agentId: string;
      totals: {
        input: number;
        output: number;
        cacheRead: number;
        cacheWrite: number;
        totalTokens: number;
        totalCost: number;
        inputCost: number;
        outputCost: number;
        cacheReadCost: number;
        cacheWriteCost: number;
        missingCostEntries: number;
      };
    }[];
    byChannel: {
      channel: string;
      totals: {
        input: number;
        output: number;
        cacheRead: number;
        cacheWrite: number;
        totalTokens: number;
        totalCost: number;
        inputCost: number;
        outputCost: number;
        cacheReadCost: number;
        cacheWriteCost: number;
        missingCostEntries: number;
      };
    }[];
    latency?: {
      count: number;
      avgMs: number;
      p95Ms: number;
      minMs: number;
      maxMs: number;
    };
    dailyLatency?: {
      date: string;
      count: number;
      avgMs: number;
      p95Ms: number;
      minMs: number;
      maxMs: number;
    }[];
    modelDaily?: {
      date: string;
      provider?: string;
      model?: string;
      tokens: number;
      cost: number;
      count: number;
    }[];
    daily: {
      date: string;
      tokens: number;
      cost: number;
      messages: number;
      toolCalls: number;
      errors: number;
    }[];
  };
};

export type SkillsInstallParams =
  | {
      name: string;
      installId: string;
      timeoutMs?: number;
    }
  | {
      source: "clawhub";
      slug: string;
      version?: string;
      force?: boolean;
      timeoutMs?: number;
    };

export type SkillsInstallResult = {
  ok: boolean;
  message: string;
  stdout: string;
  stderr: string;
  code: number | null;
  slug?: string;
  version?: string;
  targetDir?: string;
  warnings?: string[];
};

export interface DeckCommandsDiscoverParams {
  agentId?: string;
}

export type DeckCommandsDiscoverResult = {
  commands: {
    name: string;
    source: "builtin" | "skill" | "plugin";
    description: string;
    args?: string;
    argChoices?: string[];
    category?: string;
    skillName?: string;
    pluginId?: string;
  }[];
  version: string;
};

export interface DeckRoutingListParams {
  agentId?: string;
  channel?: string;
  accountId?: string;
}

export interface DeckRoutingListResult {
  bindings: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  }[];
  defaultAgentId: string;
  dmScope: string;
  configHash: string;
}

export type DeckRoutingAddParams = {
  agentId: string;
  match: {
    channel: string;
    accountId?: string;
    peer?: {
      kind: "direct" | "group" | "channel";
      id: string;
    };
    guildId?: string;
    roles?: string[];
    teamId?: string;
  };
  comment?: string;
  position?: number;
  baseHash: string;
};

export interface DeckRoutingAddResult {
  ok: boolean;
  binding: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  };
  configHash: string;
  warnings: {
    type: string;
    bindingId: string;
    agentId: string;
    detail: string;
  }[];
}

export interface DeckRoutingRemoveParams {
  id: string;
  baseHash: string;
}

export interface DeckRoutingRemoveResult {
  ok: boolean;
  removed: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  };
  configHash: string;
  impact: string;
}

export type DeckRoutingValidateParams = {
  agentId: string;
  match: {
    channel: string;
    accountId?: string;
    peer?: {
      kind: "direct" | "group" | "channel";
      id: string;
    };
    guildId?: string;
    roles?: string[];
    teamId?: string;
  };
};

export interface DeckRoutingValidateResult {
  ok: boolean;
  tier: string;
  conflicts: {
    type: string;
    bindingId: string;
    agentId: string;
    detail: string;
  }[];
}

export type DeckRoutingSimulateParams = {
  channel: string;
  accountId?: string;
  peer?: {
    kind: "direct" | "group" | "channel";
    id: string;
  };
  guildId?: string;
  teamId?: string;
  memberRoleIds?: string[];
};

export interface DeckRoutingSimulateResult {
  agentId: string;
  matchedBy: string;
  sessionKey: string;
  tiers: {
    tier: string;
    matched: boolean;
    checked: boolean;
  }[];
}

export interface DeckAgentsDetailParams {
  agentId: string;
}

export interface DeckAgentsDetailResult {
  id: string;
  name?: string;
  workspace: string;
  model?: string;
  isDefault: boolean;
  bindingCount: number;
  sessionCount: number;
  activeSubagentCount: number;
  skillMode: string;
  effectiveSkills: string[];
  totalAvailableSkills: number;
  subagents: {
    allowAgents: string[];
    model?: string;
    effectiveMaxSpawnDepth: number;
    effectiveMaxChildrenPerAgent: number;
  };
  sandbox?: unknown;
  identityExists: boolean;
  fallbackModels?: string[];
}

export interface DeckAgentsSkillsGetParams {
  agentId: string;
}

export interface DeckAgentsSkillsGetResult {
  agentId: string;
  mode: string;
  skills: string[];
  available: {
    key: string;
    name: string;
    eligible: boolean;
    assigned: boolean;
  }[];
  configHash: string;
}

export type DeckAgentsSkillsSetParams = {
  agentId: string;
  mode: "all" | "whitelist";
  skills: string[];
  baseHash: string;
};

export interface DeckAgentsSkillsSetResult {
  ok: boolean;
  agentId: string;
  mode: string;
  skills: string[];
  configHash: string;
}

export interface DeckAgentsSubagentsGetParams {
  agentId: string;
}

export interface DeckAgentsSubagentsGetResult {
  agentId: string;
  allowAgents: string[];
  allowAny: boolean;
  model?: string;
  effectiveMaxSpawnDepth: number;
  effectiveMaxChildrenPerAgent: number;
  effectiveThinking?: unknown;
  allowedAgents: {
    id: string;
    name?: string;
  }[];
  allAgents: {
    id: string;
    name?: string;
  }[];
  configHash: string;
}

export type DeckAgentsSubagentsSetParams = {
  agentId: string;
  allowAgents: string[];
  model?: string | null;
  baseHash: string;
};

export interface DeckAgentsSubagentsSetResult {
  ok: boolean;
  agentId: string;
  allowAgents: string[];
  model?: string;
  configHash: string;
}

export interface DeckAgentsEventStreamsGetParams {
  agentId: string;
}

export interface DeckAgentsEventStreamsGetResult {
  agentId: string;
  eventStreams: string[];
  isDefault: boolean;
  configHash: string;
}

export interface DeckAgentsEventStreamsSetParams {
  agentId: string;
  eventStreams: string[];
  baseHash: string;
}

export interface DeckAgentsEventStreamsSetResult {
  ok: boolean;
  agentId: string;
  eventStreams: string[];
  configHash: string;
}

export interface DeckAgentsToolPolicyPreviewParams {
  agentId: string;
  context?: {
    channel?: string;
    chatType?: string;
  };
}

export interface DeckAgentsToolPolicyPreviewResult {
  layers: {
    label: string;
    ruleCount: number;
    effect: string;
  }[];
  tools: {
    name: string;
    allowed: boolean;
    decisiveLayer: string;
    trace: {
      layer: string;
      decision: string;
    }[];
  }[];
  configHash: string;
}

export interface DeckAgentsSystemPromptPreviewParams {
  agentId: string;
  context?: {
    channel?: string;
    chatType?: string;
  };
}

export interface DeckAgentsSystemPromptPreviewResult {
  layers: {
    label: string;
    source: string;
    charCount: number;
    fileCount: number;
  }[];
  bootstrapFiles: {
    name: string;
    exists: boolean;
    charCount: number;
  }[];
  totalChars: number;
  configHash: string;
}

export type DeckSubagentsListParams = {
  status?: "active" | "completed" | "failed" | "timeout" | "all";
  agentId?: string;
  requesterAgentId?: string;
  limit?: number;
  offset?: number;
};

export interface DeckSubagentsListResult {
  runs: {
    runId: string;
    childSessionKey: string;
    childAgentId: string;
    childAgentName?: string;
    requesterSessionKey: string;
    requesterAgentId: string;
    requesterAgentName?: string;
    task?: string;
    label?: string;
    model?: string;
    spawnMode: string;
    depth: number;
    createdAt: number;
    startedAt?: number;
    endedAt?: number;
    durationMs?: number;
    status: string;
    outcome?: unknown;
  }[];
  total: number;
}

export interface DeckSubagentsKillParams {
  runId: string;
}

export interface DeckSubagentsKillResult {
  ok: boolean;
  runId: string;
  childSessionKey: string;
}

export interface DeckSubagentsLineageParams {
  runId?: string;
  sessionKey?: string;
}

export type DeckSubagentsLineageResult = {
  root: {
    sessionKey: string;
    agentId: string;
    agentName?: string;
  };
  nodes: {
    runId: string;
    sessionKey: string;
    agentId: string;
    agentName?: string;
    task?: string;
    depth: number;
    parentRunId: string | null;
    status: string;
    durationMs?: number;
  }[];
};

export interface DeckSubagentsSteerParams {
  runId: string;
  instruction: string;
}

export interface DeckSubagentsSteerResult {
  success: boolean;
  dedupKey?: string;
  deduped?: boolean;
  newRunId?: string;
}

export type DeckIdentityListParams = Record<string, never>;

export interface DeckIdentityListResult {
  links: {
    canonical: string;
    peers: {
      channel: string;
      peerId: string;
    }[];
  }[];
  configHash: string;
}

export interface DeckIdentityLinkParams {
  canonical: string;
  channel: string;
  peerId: string;
  baseHash: string;
}

export interface DeckIdentityLinkResult {
  ok: boolean;
  configHash: string;
}

export interface DeckIdentityUnlinkParams {
  canonical: string;
  channel: string;
  peerId: string;
  baseHash: string;
}

export interface DeckIdentityUnlinkResult {
  ok: boolean;
  configHash: string;
}

export type DeckThreadsListParams = {
  agentId?: string;
  channel?: string;
  status?: "active" | "all";
};

export interface DeckThreadsListResult {
  threads: {
    threadId: string;
    channelId: string;
    agentId: string;
    targetSessionKey: string;
    targetKind: string;
    boundAt: number;
    lastActivityAt: number;
    accountId: string;
    boundBy: string;
    label?: string;
  }[];
}

export type DeckAuthOverviewResult = {
  providers: {
    provider: string;
    status: string;
    auth: {
      type: string | null;
      source: string;
      profileId?: string;
    } | null;
    oauth?: {
      expiresAt: number;
      remainingMs: number;
      status: string;
    };
    cooldown?: {
      reason: string;
      remainingMs: number;
      until: number;
    };
    usage?: {
      windows: {
        label: string;
        usedPercent: number;
        resetsInMs: number;
      }[];
      plan?: string;
    };
  }[];
};

export interface DeckAuthProbeResult {
  provider: string;
  model?: string;
  profileId?: string;
  label: string;
  source: string;
  mode?: string;
  status: string;
  reasonCode?: string;
  error?: string;
  latencyMs?: number;
}

export interface GatewayMethodMap {
  "chat.history": { params: ChatHistoryParams; result: ChatHistoryResult };
  "chat.abort": { params: ChatAbortParams; result: ChatAbortResult };
  "chat.send": { params: ChatSendParams; result: ChatSendResult };
  "sessions.list": { params: SessionsListParams; result: SessionsListResult };
  "sessions.subscribe": { params: Record<string, unknown>; result: SessionsSubscribeResult };
  "sessions.unsubscribe": { params: Record<string, unknown>; result: SessionsUnsubscribeResult };
  "sessions.messages.subscribe": {
    params: SessionsMessagesSubscribeParams;
    result: SessionsMessagesSubscribeResult;
  };
  "sessions.messages.unsubscribe": {
    params: SessionsMessagesUnsubscribeParams;
    result: SessionsMessagesUnsubscribeResult;
  };
  "sessions.preview": { params: SessionsPreviewParams; result: SessionsPreviewResult };
  "sessions.create": { params: SessionsCreateParams; result: SessionsCreateResult };
  "sessions.send": { params: SessionsSendParams; result: SessionsSendResult };
  "sessions.steer": { params: SessionsSteerParams; result: SessionsSteerResult };
  "sessions.abort": { params: SessionsAbortParams; result: SessionsAbortResult };
  "sessions.patch": { params: SessionsPatchParams; result: SessionsPatchResult };
  "sessions.reset": { params: SessionsResetParams; result: SessionsResetResult };
  "sessions.clear": { params: SessionsClearParams; result: SessionsClearResult };
  "sessions.delete": { params: SessionsDeleteParams; result: SessionsDeleteResult };
  "sessions.compact": { params: SessionsCompactParams; result: SessionsCompactResult };
  "sessions.usage": { params: SessionsUsageParams; result: SessionsUsageResult };
  "skills.install": { params: SkillsInstallParams; result: SkillsInstallResult };
  "deck.commands.discover": {
    params: DeckCommandsDiscoverParams;
    result: DeckCommandsDiscoverResult;
  };
  "deck.routing.list": { params: DeckRoutingListParams; result: DeckRoutingListResult };
  "deck.routing.add": { params: DeckRoutingAddParams; result: DeckRoutingAddResult };
  "deck.routing.remove": { params: DeckRoutingRemoveParams; result: DeckRoutingRemoveResult };
  "deck.routing.validate": { params: DeckRoutingValidateParams; result: DeckRoutingValidateResult };
  "deck.routing.simulate": { params: DeckRoutingSimulateParams; result: DeckRoutingSimulateResult };
  "deck.agents.detail": { params: DeckAgentsDetailParams; result: DeckAgentsDetailResult };
  "deck.agents.skills.get": {
    params: DeckAgentsSkillsGetParams;
    result: DeckAgentsSkillsGetResult;
  };
  "deck.agents.skills.set": {
    params: DeckAgentsSkillsSetParams;
    result: DeckAgentsSkillsSetResult;
  };
  "deck.agents.subagents.get": {
    params: DeckAgentsSubagentsGetParams;
    result: DeckAgentsSubagentsGetResult;
  };
  "deck.agents.subagents.set": {
    params: DeckAgentsSubagentsSetParams;
    result: DeckAgentsSubagentsSetResult;
  };
  "deck.agents.eventStreams.get": {
    params: DeckAgentsEventStreamsGetParams;
    result: DeckAgentsEventStreamsGetResult;
  };
  "deck.agents.eventStreams.set": {
    params: DeckAgentsEventStreamsSetParams;
    result: DeckAgentsEventStreamsSetResult;
  };
  "deck.agents.toolPolicy.preview": {
    params: DeckAgentsToolPolicyPreviewParams;
    result: DeckAgentsToolPolicyPreviewResult;
  };
  "deck.agents.systemPrompt.preview": {
    params: DeckAgentsSystemPromptPreviewParams;
    result: DeckAgentsSystemPromptPreviewResult;
  };
  "deck.subagents.list": { params: DeckSubagentsListParams; result: DeckSubagentsListResult };
  "deck.subagents.kill": { params: DeckSubagentsKillParams; result: DeckSubagentsKillResult };
  "deck.subagents.lineage": {
    params: DeckSubagentsLineageParams;
    result: DeckSubagentsLineageResult;
  };
  "deck.subagents.steer": { params: DeckSubagentsSteerParams; result: DeckSubagentsSteerResult };
  "deck.identity.list": { params: DeckIdentityListParams; result: DeckIdentityListResult };
  "deck.identity.link": { params: DeckIdentityLinkParams; result: DeckIdentityLinkResult };
  "deck.identity.unlink": { params: DeckIdentityUnlinkParams; result: DeckIdentityUnlinkResult };
  "deck.threads.list": { params: DeckThreadsListParams; result: DeckThreadsListResult };
  "deck.auth.overview": { params: Record<string, unknown>; result: DeckAuthOverviewResult };
  "deck.auth.probe": { params: Record<string, unknown>; result: DeckAuthProbeResult };
}

export type GatewayMethodName = keyof GatewayMethodMap;
