// Auto-generated by scripts/protocol-gen-ts.ts — DO NOT EDIT

export const GENERATED_SCHEMA_VERSION = "3";

export type TranscriptBlock =
  | {
      type: "text";
      text: string;
    }
  | {
      type: "thinking";
      text: string;
    }
  | {
      type: "tool_use";
      id: string;
      name: string;
      input: Record<string, unknown>;
    }
  | {
      type: "tool_result";
      toolUseId: string;
      content: string;
      isError?: boolean;
    }
  | {
      type: "image";
      data: string;
      mimeType: string;
      fileName?: string;
    }
  | {
      type: "file";
      data: string;
      mimeType: string;
      fileName: string;
      size?: number;
    };

export type TranscriptMessage = {
  id?: string;
  role: "user" | "assistant" | "system";
  content: (
    | {
        type: "text";
        text: string;
      }
    | {
        type: "thinking";
        text: string;
      }
    | {
        type: "tool_use";
        id: string;
        name: string;
        input: Record<string, unknown>;
      }
    | {
        type: "tool_result";
        toolUseId: string;
        content: string;
        isError?: boolean;
      }
    | {
        type: "image";
        data: string;
        mimeType: string;
        fileName?: string;
      }
    | {
        type: "file";
        data: string;
        mimeType: string;
        fileName: string;
        size?: number;
      }
  )[];
  timestamp: number;
};

export interface ChatHistoryParams {
  sessionKey: string;
  limit?: number;
  maxChars?: number;
}

export type ChatHistoryResult = {
  sessionKey: string;
  sessionId: string;
  messages: {
    id?: string;
    role: "user" | "assistant" | "system";
    content: (
      | {
          type: "text";
          text: string;
        }
      | {
          type: "thinking";
          text: string;
        }
      | {
          type: "tool_use";
          id: string;
          name: string;
          input: Record<string, unknown>;
        }
      | {
          type: "tool_result";
          toolUseId: string;
          content: string;
          isError?: boolean;
        }
      | {
          type: "image";
          data: string;
          mimeType: string;
          fileName?: string;
        }
      | {
          type: "file";
          data: string;
          mimeType: string;
          fileName: string;
          size?: number;
        }
    )[];
    timestamp: number;
  }[];
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
};

export interface ChatAbortParams {
  sessionKey: string;
  runId?: string;
}

export interface ChatAbortResult {
  ok: boolean;
  aborted: boolean;
  runIds: string[];
}

export interface ChatSendParams {
  sessionKey: string;
  message: string;
  thinking?: string;
  deliver?: boolean;
  originatingChannel?: string;
  originatingTo?: string;
  originatingAccountId?: string;
  originatingThreadId?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  systemInputProvenance?: {
    kind: string;
    originSessionId?: string;
    sourceSessionKey?: string;
    sourceChannel?: string;
    sourceTool?: string;
  };
  systemProvenanceReceipt?: string;
  idempotencyKey: string;
}

export interface ChatSendResult {
  ok?: boolean;
  aborted?: boolean;
  runIds?: string[];
  runId?: string;
  status?: string;
}

export type ConfigGetParams = Record<string, never>;

export interface ConfigGetResult {
  path: string;
  exists: boolean;
  raw: string;
  parsed: unknown;
  sourceConfig: unknown;
  resolved: unknown;
  valid: boolean;
  runtimeConfig: unknown;
  config: unknown;
  hash?: string;
  issues: unknown[];
  warnings: unknown[];
  legacyIssues: unknown[];
}

export type ConfigSchemaParams = Record<string, never>;

export interface ConfigSchemaResult {
  schema: unknown;
  uiHints: Record<
    string,
    {
      label?: string;
      help?: string;
      tags?: string[];
      group?: string;
      order?: number;
      advanced?: boolean;
      sensitive?: boolean;
      placeholder?: string;
      itemTemplate?: unknown;
    }
  >;
  version: string;
  generatedAt: string;
}

export interface ConfigSchemaLookupParams {
  path: string;
}

export interface ConfigSchemaLookupResult {
  path: string;
  schema: unknown;
  hint?: {
    label?: string;
    help?: string;
    tags?: string[];
    group?: string;
    order?: number;
    advanced?: boolean;
    sensitive?: boolean;
    placeholder?: string;
    itemTemplate?: unknown;
  };
  hintPath?: string;
  children: {
    key: string;
    path: string;
    type?: string;
    required: boolean;
    hasChildren: boolean;
    hint?: {
      label?: string;
      help?: string;
      tags?: string[];
      group?: string;
      order?: number;
      advanced?: boolean;
      sensitive?: boolean;
      placeholder?: string;
      itemTemplate?: unknown;
    };
    hintPath?: string;
  }[];
}

export interface ConfigApplyParams {
  raw: string;
  baseHash?: string;
  sessionKey?: string;
  note?: string;
  restartDelayMs?: number;
}

export interface ConfigApplyResult {
  ok: boolean;
  noop?: boolean;
  path: string;
  config: unknown;
  restart?: unknown;
  sentinel?: unknown;
}

export interface ConfigPatchParams {
  raw: string;
  baseHash?: string;
  sessionKey?: string;
  note?: string;
  restartDelayMs?: number;
}

export interface ConfigPatchResult {
  ok: boolean;
  noop?: boolean;
  path: string;
  config: unknown;
  restart?: unknown;
  sentinel?: unknown;
}

export interface ConfigSetParams {
  raw: string;
  baseHash?: string;
}

export interface ConfigSetResult {
  ok: boolean;
  noop?: boolean;
  path: string;
  config: unknown;
  restart?: unknown;
  sentinel?: unknown;
}

export interface SkillsStatusParams {
  agentId?: string;
}

export type SkillsBinsParams = Record<string, never>;

export interface SkillsBinsResult {
  bins: string[];
}

export type SkillsInstallParams =
  | {
      name: string;
      installId: string;
      dangerouslyForceUnsafeInstall?: boolean;
      timeoutMs?: number;
    }
  | {
      source: "clawhub";
      slug: string;
      version?: string;
      force?: boolean;
      timeoutMs?: number;
    };

export type SkillsUpdateParams =
  | {
      skillKey: string;
      enabled?: boolean;
      apiKey?: string;
      env?: Record<string, string>;
    }
  | {
      source: "clawhub";
      slug?: string;
      all?: boolean;
    };

export type CronListParams = {
  includeDisabled?: boolean;
  limit?: number;
  offset?: number;
  query?: string;
  enabled?: "all" | "enabled" | "disabled";
  sortBy?: "nextRunAtMs" | "updatedAtMs" | "name";
  sortDir?: "asc" | "desc";
};

export type CronStatusParams = Record<string, never>;

export type CronAddParams = {
  name: string;
  agentId?: string;
  sessionKey?: string;
  description?: string;
  enabled?: boolean;
  deleteAfterRun?: boolean;
  schedule:
    | {
        kind: "at";
        at: string;
      }
    | {
        kind: "every";
        everyMs: number;
        anchorMs?: number;
      }
    | {
        kind: "cron";
        expr: string;
        tz?: string;
        staggerMs?: number;
      };
  sessionTarget: string;
  wakeMode: "next-heartbeat" | "now";
  payload:
    | {
        kind: "systemEvent";
        text: string;
      }
    | {
        kind: "agentTurn";
        message: string;
        model?: string;
        fallbacks?: string[];
        thinking?: string;
        timeoutSeconds?: number;
        allowUnsafeExternalContent?: boolean;
        lightContext?: boolean;
        toolsAllow?: string[];
      };
  delivery?:
    | {
        mode: "none";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "announce";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to?: string;
      }
    | {
        mode: "webhook";
        channel?: string;
        accountId?: string;
        bestEffort?: boolean;
        failureDestination?: {
          channel?: string;
          to?: string;
          accountId?: string;
          mode?: "announce" | "webhook";
        };
        to: string;
      };
  failureAlert?:
    | false
    | {
        after?: number;
        channel?: string;
        to?: string;
        cooldownMs?: number;
        mode?: "announce" | "webhook";
        accountId?: string;
      };
};

export type CronUpdateParams =
  | {
      id: string;
      patch: {
        name?: string;
        agentId?: string;
        sessionKey?: string;
        description?: string;
        enabled?: boolean;
        deleteAfterRun?: boolean;
        schedule?:
          | {
              kind: "at";
              at: string;
            }
          | {
              kind: "every";
              everyMs: number;
              anchorMs?: number;
            }
          | {
              kind: "cron";
              expr: string;
              tz?: string;
              staggerMs?: number;
            };
        sessionTarget?: string;
        wakeMode?: "next-heartbeat" | "now";
        payload?:
          | {
              kind: "systemEvent";
              text?: string;
            }
          | {
              kind: "agentTurn";
              message?: string;
              model?: string;
              fallbacks?: string[];
              thinking?: string;
              timeoutSeconds?: number;
              allowUnsafeExternalContent?: boolean;
              lightContext?: boolean;
              toolsAllow?: string[] | null;
            };
        delivery?: {
          mode?: "none" | "announce" | "webhook";
          channel?: string;
          accountId?: string;
          bestEffort?: boolean;
          failureDestination?: {
            channel?: string;
            to?: string;
            accountId?: string;
            mode?: "announce" | "webhook";
          };
          to?: string;
        };
        failureAlert?:
          | false
          | {
              after?: number;
              channel?: string;
              to?: string;
              cooldownMs?: number;
              mode?: "announce" | "webhook";
              accountId?: string;
            };
        state?: {
          nextRunAtMs?: number;
          runningAtMs?: number;
          lastRunAtMs?: number;
          lastRunStatus?: "ok" | "error" | "skipped";
          lastStatus?: "ok" | "error" | "skipped";
          lastError?: string;
          lastErrorReason?:
            | "auth"
            | "format"
            | "rate_limit"
            | "billing"
            | "timeout"
            | "model_not_found"
            | "unknown";
          lastDurationMs?: number;
          consecutiveErrors?: number;
          lastDelivered?: boolean;
          lastDeliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
          lastDeliveryError?: string;
          lastFailureAlertAtMs?: number;
        };
      };
    }
  | {
      jobId: string;
      patch: {
        name?: string;
        agentId?: string;
        sessionKey?: string;
        description?: string;
        enabled?: boolean;
        deleteAfterRun?: boolean;
        schedule?:
          | {
              kind: "at";
              at: string;
            }
          | {
              kind: "every";
              everyMs: number;
              anchorMs?: number;
            }
          | {
              kind: "cron";
              expr: string;
              tz?: string;
              staggerMs?: number;
            };
        sessionTarget?: string;
        wakeMode?: "next-heartbeat" | "now";
        payload?:
          | {
              kind: "systemEvent";
              text?: string;
            }
          | {
              kind: "agentTurn";
              message?: string;
              model?: string;
              fallbacks?: string[];
              thinking?: string;
              timeoutSeconds?: number;
              allowUnsafeExternalContent?: boolean;
              lightContext?: boolean;
              toolsAllow?: string[] | null;
            };
        delivery?: {
          mode?: "none" | "announce" | "webhook";
          channel?: string;
          accountId?: string;
          bestEffort?: boolean;
          failureDestination?: {
            channel?: string;
            to?: string;
            accountId?: string;
            mode?: "announce" | "webhook";
          };
          to?: string;
        };
        failureAlert?:
          | false
          | {
              after?: number;
              channel?: string;
              to?: string;
              cooldownMs?: number;
              mode?: "announce" | "webhook";
              accountId?: string;
            };
        state?: {
          nextRunAtMs?: number;
          runningAtMs?: number;
          lastRunAtMs?: number;
          lastRunStatus?: "ok" | "error" | "skipped";
          lastStatus?: "ok" | "error" | "skipped";
          lastError?: string;
          lastErrorReason?:
            | "auth"
            | "format"
            | "rate_limit"
            | "billing"
            | "timeout"
            | "model_not_found"
            | "unknown";
          lastDurationMs?: number;
          consecutiveErrors?: number;
          lastDelivered?: boolean;
          lastDeliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
          lastDeliveryError?: string;
          lastFailureAlertAtMs?: number;
        };
      };
    };

export type CronRemoveParams =
  | {
      id: string;
    }
  | {
      jobId: string;
    };

export type CronRunParams =
  | {
      id: string;
      mode?: "due" | "force";
    }
  | {
      jobId: string;
      mode?: "due" | "force";
    };

export type CronRunsParams = {
  scope?: "job" | "all";
  id?: string;
  jobId?: string;
  limit?: number;
  offset?: number;
  statuses?: ("ok" | "error" | "skipped")[];
  status?: "all" | "ok" | "error" | "skipped";
  deliveryStatuses?: ("delivered" | "not-delivered" | "unknown" | "not-requested")[];
  deliveryStatus?: "delivered" | "not-delivered" | "unknown" | "not-requested";
  query?: string;
  sortDir?: "asc" | "desc";
};

export type ExecApprovalsGetParams = Record<string, never>;

export interface ExecApprovalsGetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export interface ExecApprovalsSetParams {
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
  baseHash?: string;
}

export interface ExecApprovalsSetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export interface ExecApprovalsNodeGetParams {
  nodeId: string;
}

export interface ExecApprovalsNodeGetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export interface ExecApprovalsNodeSetParams {
  nodeId: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
  baseHash?: string;
}

export interface ExecApprovalsNodeSetResult {
  path: string;
  exists: boolean;
  hash: string;
  file: {
    version: 1;
    socket?: {
      path?: string;
      token?: string;
    };
    defaults?: {
      security?: string;
      ask?: string;
      askFallback?: string;
      autoAllowSkills?: boolean;
    };
    agents?: Record<
      string,
      {
        security?: string;
        ask?: string;
        askFallback?: string;
        autoAllowSkills?: boolean;
        allowlist?: {
          id?: string;
          pattern: string;
          argPattern?: string;
          lastUsedAt?: number;
          lastUsedCommand?: string;
          lastResolvedPath?: string;
        }[];
      }
    >;
  };
}

export type ExecApprovalRequestParams = {
  id?: string;
  command?: string;
  commandArgv?: string[];
  systemRunPlan?: {
    argv: string[];
    cwd: string;
    commandText: string;
    commandPreview?: string;
    agentId: string;
    sessionKey: string;
    mutableFileOperand?: {
      argvIndex: number;
      path: string;
      sha256: string;
    } | null;
  };
  env?: Record<string, string>;
  cwd?: string;
  nodeId?: string;
  host?: string;
  security?: string;
  ask?: string;
  agentId?: string;
  resolvedPath?: string;
  sessionKey?: string;
  turnSourceChannel?: string;
  turnSourceTo?: string;
  turnSourceAccountId?: string;
  turnSourceThreadId?: string;
  timeoutMs?: number;
  twoPhase?: boolean;
};

export interface ExecApprovalResolveParams {
  id: string;
  decision: string;
}

export interface SessionsListParams {
  limit?: number;
  activeMinutes?: number;
  includeGlobal?: boolean;
  includeUnknown?: boolean;
  includeDerivedTitles?: boolean;
  includeLastMessage?: boolean;
  label?: string;
  spawnedBy?: string;
  agentId?: string;
  search?: string;
}

export type SessionsListResult = {
  ts: number;
  path: string;
  count: number;
  defaults: {
    modelProvider: string;
    model: string;
    contextTokens: number;
  };
  sessions: {
    key: string;
    spawnedBy?: string;
    kind: "direct" | "group" | "global" | "unknown";
    label?: string;
    displayName?: string;
    derivedTitle?: string;
    lastMessagePreview?: string;
    channel?: string;
    subject?: string;
    groupChannel?: string;
    space?: string;
    chatType?: string;
    origin?: unknown;
    updatedAt: number;
    sessionId?: string;
    systemSent?: boolean;
    abortedLastRun?: boolean;
    thinkingLevel?: string;
    fastMode?: boolean;
    verboseLevel?: string;
    reasoningLevel?: string;
    elevatedLevel?: string;
    sendPolicy?: "allow" | "deny";
    inputTokens?: number;
    outputTokens?: number;
    totalTokens?: number;
    totalTokensFresh?: boolean;
    estimatedCostUsd?: number;
    status?: "running" | "done" | "failed" | "killed" | "timeout";
    startedAt?: number;
    endedAt?: number;
    runtimeMs?: number;
    parentSessionKey?: string;
    childSessions?: string[];
    responseUsage?: "on" | "off" | "tokens" | "full";
    modelProvider?: string;
    model?: string;
    contextTokens?: number;
    deliveryContext?: {
      channel?: string;
      to?: string;
      accountId?: string;
      threadId?: string;
    };
    lastChannel?: string;
    lastTo?: string;
    lastAccountId?: string;
    compactionCount?: number;
  }[];
};

export interface SessionsSubscribeResult {
  subscribed: boolean;
}

export interface SessionsUnsubscribeResult {
  subscribed: boolean;
}

export interface SessionsMessagesSubscribeParams {
  key: string;
}

export interface SessionsMessagesSubscribeResult {
  subscribed: boolean;
  key: string;
}

export interface SessionsMessagesUnsubscribeParams {
  key: string;
}

export interface SessionsMessagesUnsubscribeResult {
  subscribed: boolean;
  key: string;
}

export interface SessionsPreviewParams {
  keys: string[];
  limit?: number;
  maxChars?: number;
}

export type SessionsPreviewResult = {
  ts: number;
  previews: {
    key: string;
    status: "ok" | "empty" | "missing" | "error";
    items: {
      role: "user" | "assistant" | "tool" | "system" | "other";
      text: string;
    }[];
  }[];
};

export interface SessionsGetParams {
  key?: string;
  sessionKey?: string;
  limit?: number;
}

export interface SessionsGetResult {
  messages: unknown[];
}

export interface SessionsCreateParams {
  key?: string;
  agentId?: string;
  label?: string;
  model?: string;
  parentSessionKey?: string;
  task?: string;
  message?: string;
}

export interface SessionsCreateResult {
  ok: boolean;
  key: string;
  sessionId: string;
  entry: Record<string, unknown>;
  runStarted: boolean;
  runId?: string;
  status?: string;
  messageSeq?: number;
  interruptedActiveRun?: boolean;
  runError?: unknown;
}

export interface SessionsSendParams {
  key: string;
  message: string;
  thinking?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  idempotencyKey?: string;
}

export type SessionsSendResult = {
  runId?: string;
  status: "started" | "in_flight";
  messageSeq?: number;
  interruptedActiveRun?: boolean;
};

export interface SessionsSteerParams {
  key: string;
  message: string;
  thinking?: string;
  attachments?: unknown[];
  timeoutMs?: number;
  idempotencyKey?: string;
}

export type SessionsSteerResult = {
  runId?: string;
  status: "started" | "in_flight";
  messageSeq?: number;
  interruptedActiveRun?: boolean;
};

export interface SessionsAbortParams {
  key: string;
  runId?: string;
}

export type SessionsAbortResult = {
  ok: boolean;
  abortedRunId?: string;
  status: "aborted" | "no-active-run";
};

export type SessionsPatchParams = {
  key: string;
  label?: string;
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
  reasoningLevel?: string;
  responseUsage?: "off" | "tokens" | "full" | "on" | null;
  elevatedLevel?: string;
  execHost?: string;
  execSecurity?: string;
  execAsk?: string;
  execNode?: string;
  model?: string;
  spawnedBy?: string;
  spawnedWorkspaceDir?: string;
  spawnDepth?: number;
  subagentRole?: "orchestrator" | "leaf" | null;
  subagentControlScope?: "children" | "none" | null;
  sendPolicy?: "allow" | "deny" | null;
  groupActivation?: "mention" | "always" | null;
};

export interface SessionsPatchResult {
  ok: true;
  path: string;
  key: string;
  entry: Record<string, unknown>;
  resolved?: {
    modelProvider?: string;
    model?: string;
  };
}

export type SessionsResetParams = {
  key: string;
  reason?: "new" | "reset";
};

export interface SessionsResetResult {
  ok: boolean;
  key: string;
  entry: Record<string, unknown>;
}

export interface SessionsClearParams {
  key: string;
}

export interface SessionsClearResult {
  ok: boolean;
  key: string;
  entry: Record<string, unknown>;
}

export interface SessionsDeleteParams {
  key: string;
  deleteTranscript?: boolean;
  emitLifecycleHooks?: boolean;
}

export interface SessionsDeleteResult {
  ok: boolean;
  key: string;
  deleted: boolean;
  archived: string[];
}

export interface SessionsCompactParams {
  key: string;
  maxLines?: number;
}

export interface SessionsCompactResult {
  ok: boolean;
  key: string;
  compacted: boolean;
  archived?: string[];
  kept?: number;
  reason?: string;
}

export type SessionsUsageParams = {
  key?: string;
  startDate?: string;
  endDate?: string;
  mode?: "utc" | "gateway" | "specific";
  utcOffset?: string;
  limit?: number;
  includeContextWeight?: boolean;
};

export interface SessionsUsageResult {
  updatedAt: number;
  startDate: string;
  endDate: string;
  sessions: {
    key: string;
    label?: string;
    sessionId?: string;
    updatedAt?: number;
    agentId?: string;
    channel?: string;
    chatType?: string;
    origin?: unknown;
    modelOverride?: string;
    providerOverride?: string;
    modelProvider?: string;
    model?: string;
    usage: unknown;
    contextWeight?: unknown;
  }[];
  totals: unknown;
  aggregates: unknown;
}

export type SessionsUsageTimeseriesParams = {
  key?: string;
  startDate?: string;
  endDate?: string;
  mode?: "utc" | "gateway" | "specific";
  utcOffset?: string;
  limit?: number;
  includeContextWeight?: boolean;
};

export type SessionsUsageTimeseriesResult = unknown;

export type SessionsUsageLogsParams = {
  key?: string;
  startDate?: string;
  endDate?: string;
  mode?: "utc" | "gateway" | "specific";
  utcOffset?: string;
  limit?: number;
  includeContextWeight?: boolean;
};

export interface SessionsUsageLogsResult {
  logs: unknown[];
}

export interface AgentIdentityGetParams {
  agentId?: string;
  sessionKey?: string;
}

export interface AgentIdentityGetResult {
  agentId: string;
  name?: string;
  avatar?: string;
  emoji?: string;
}

export interface AgentWaitParams {
  runId: string;
  timeoutMs?: number;
}

export type AgentsListParams = Record<string, never>;

export type AgentsListResult = {
  defaultId: string;
  mainKey: string;
  scope: "per-sender" | "global";
  agents: {
    id: string;
    name?: string;
    identity?: {
      name?: string;
      theme?: string;
      emoji?: string;
      avatar?: string;
      avatarUrl?: string;
    };
    workspace?: string;
    model?: {
      primary?: string;
      fallbacks?: string[];
    };
  }[];
};

export interface AgentsCreateParams {
  name: string;
  workspace: string;
  emoji?: string;
  avatar?: string;
}

export interface AgentsCreateResult {
  ok: true;
  agentId: string;
  name: string;
  workspace: string;
}

export interface AgentsUpdateParams {
  agentId: string;
  name?: string;
  workspace?: string;
  model?: string;
  avatar?: string;
}

export interface AgentsUpdateResult {
  ok: true;
  agentId: string;
}

export interface AgentsDeleteParams {
  agentId: string;
  deleteFiles?: boolean;
}

export interface AgentsDeleteResult {
  ok: true;
  agentId: string;
  removedBindings: number;
}

export interface AgentsFilesListParams {
  agentId: string;
}

export interface AgentsFilesListResult {
  agentId: string;
  workspace: string;
  files: {
    name: string;
    path: string;
    missing: boolean;
    size?: number;
    updatedAtMs?: number;
    content?: string;
  }[];
}

export interface AgentsFilesGetParams {
  agentId: string;
  name: string;
}

export interface AgentsFilesGetResult {
  agentId: string;
  workspace: string;
  file: {
    name: string;
    path: string;
    missing: boolean;
    size?: number;
    updatedAtMs?: number;
    content?: string;
  };
}

export interface AgentsFilesSetParams {
  agentId: string;
  name: string;
  content: string;
}

export interface AgentsFilesSetResult {
  ok: true;
  agentId: string;
  workspace: string;
  file: {
    name: string;
    path: string;
    missing: boolean;
    size?: number;
    updatedAtMs?: number;
    content?: string;
  };
}

export interface ChannelsStatusParams {
  probe?: boolean;
  timeoutMs?: number;
}

export interface ChannelsStatusResult {
  ts: number;
  channelOrder: string[];
  channelLabels: Record<string, string>;
  channelDetailLabels?: Record<string, string>;
  channelSystemImages?: Record<string, string>;
  channelMeta?: {
    id: string;
    label: string;
    detailLabel: string;
    systemImage?: string;
  }[];
  channels: Record<string, unknown>;
  channelAccounts: Record<
    string,
    {
      accountId: string;
      name?: string;
      enabled?: boolean;
      configured?: boolean;
      linked?: boolean;
      running?: boolean;
      connected?: boolean;
      reconnectAttempts?: number;
      lastConnectedAt?: number;
      lastError?: string;
      healthState?: string;
      lastStartAt?: number;
      lastStopAt?: number;
      lastInboundAt?: number;
      lastOutboundAt?: number;
      busy?: boolean;
      activeRuns?: number;
      lastRunActivityAt?: number;
      lastProbeAt?: number;
      mode?: string;
      dmPolicy?: string;
      allowFrom?: string[];
      tokenSource?: string;
      botTokenSource?: string;
      appTokenSource?: string;
      baseUrl?: string;
      allowUnmentionedGroups?: boolean;
      cliPath?: string;
      dbPath?: string;
      port?: number;
      probe?: unknown;
      audit?: unknown;
      application?: unknown;
    }[]
  >;
  channelDefaultAccountId: Record<string, string>;
}

export interface ChannelsLogoutParams {
  channel: string;
  accountId?: string;
}

export type ModelsListParams = Record<string, never>;

export interface ModelsListResult {
  models: {
    id: string;
    name: string;
    provider: string;
    contextWindow?: number;
    reasoning?: boolean;
  }[];
}

export type ModelsConfiguredParams = Record<string, never>;

export interface ModelsConfiguredResult {
  models: {
    id: string;
    name: string;
    provider: string;
    contextWindow?: number;
    reasoning?: boolean;
    input?: string[];
    cost?: {
      input: number;
      output: number;
      cacheRead: number;
      cacheWrite: number;
    };
    maxTokens?: number;
    authStatus: string;
  }[];
}

export interface LogsTailParams {
  cursor?: number;
  limit?: number;
  maxBytes?: number;
}

export interface LogsTailResult {
  file: string;
  cursor: number;
  size: number;
  lines: string[];
  truncated?: boolean;
  reset?: boolean;
}

export interface DeckCommandsDiscoverParams {
  agentId?: string;
}

export type DeckCommandsDiscoverResult = {
  commands: {
    name: string;
    source: "builtin" | "skill" | "plugin";
    description: string;
    args?: string;
    argChoices?: string[];
    category?: string;
    skillName?: string;
    pluginId?: string;
  }[];
  version: string;
};

export interface DeckRoutingListParams {
  agentId?: string;
  channel?: string;
  accountId?: string;
}

export interface DeckRoutingListResult {
  bindings: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  }[];
  defaultAgentId: string;
  dmScope: string;
  configHash: string;
}

export type DeckRoutingAddParams = {
  agentId: string;
  match: {
    channel: string;
    accountId?: string;
    peer?: {
      kind: "direct" | "group" | "channel";
      id: string;
    };
    guildId?: string;
    roles?: string[];
    teamId?: string;
  };
  comment?: string;
  position?: number;
  baseHash: string;
};

export interface DeckRoutingAddResult {
  ok: boolean;
  binding: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  };
  configHash: string;
  warnings: {
    type: string;
    bindingId: string;
    agentId: string;
    detail: string;
  }[];
}

export interface DeckRoutingRemoveParams {
  id: string;
  baseHash: string;
}

export interface DeckRoutingRemoveResult {
  ok: boolean;
  removed: {
    id: string;
    agentId: string;
    tier: string;
    match: {
      channel: string;
      accountId?: string;
      peer?: {
        kind: string;
        id: string;
      };
      guildId?: string;
      roles?: string[];
      teamId?: string;
    };
    comment?: string;
  };
  configHash: string;
  impact: string;
}

export type DeckRoutingValidateParams = {
  agentId: string;
  match: {
    channel: string;
    accountId?: string;
    peer?: {
      kind: "direct" | "group" | "channel";
      id: string;
    };
    guildId?: string;
    roles?: string[];
    teamId?: string;
  };
};

export interface DeckRoutingValidateResult {
  ok: boolean;
  tier: string;
  conflicts: {
    type: string;
    bindingId: string;
    agentId: string;
    detail: string;
  }[];
}

export type DeckRoutingSimulateParams = {
  channel: string;
  accountId?: string;
  peer?: {
    kind: "direct" | "group" | "channel";
    id: string;
  };
  guildId?: string;
  teamId?: string;
  memberRoleIds?: string[];
};

export interface DeckRoutingSimulateResult {
  agentId: string;
  matchedBy: string;
  sessionKey: string;
  tiers: {
    tier: string;
    matched: boolean;
    checked: boolean;
  }[];
}

export interface DeckAgentsDetailParams {
  agentId: string;
}

export type DeckAgentsDetailResult = {
  id: string;
  name?: string;
  workspace: string;
  model?: string;
  reasoningDefault?: "on" | "off" | "stream";
  fastModeDefault?: boolean;
  isDefault: boolean;
  bindingCount: number;
  sessionCount: number;
  activeSubagentCount: number;
  skillMode: string;
  effectiveSkills: string[];
  totalAvailableSkills: number;
  subagents: {
    allowAgents: string[];
    model?: string;
    effectiveMaxSpawnDepth: number;
    effectiveMaxChildrenPerAgent: number;
  };
  sandbox?: unknown;
  identityExists: boolean;
  fallbackModels?: string[];
};

export interface DeckAgentsSkillsGetParams {
  agentId: string;
}

export interface DeckAgentsSkillsGetResult {
  agentId: string;
  mode: string;
  skills: string[];
  available: {
    key: string;
    name: string;
    eligible: boolean;
    assigned: boolean;
  }[];
  configHash: string;
}

export type DeckAgentsSkillsSetParams = {
  agentId: string;
  mode: "all" | "whitelist";
  skills: string[];
  baseHash: string;
};

export interface DeckAgentsSkillsSetResult {
  ok: boolean;
  agentId: string;
  mode: string;
  skills: string[];
  configHash: string;
}

export interface DeckAgentsSubagentsGetParams {
  agentId: string;
}

export interface DeckAgentsSubagentsGetResult {
  agentId: string;
  allowAgents: string[];
  allowAny: boolean;
  model?: string;
  effectiveMaxSpawnDepth: number;
  effectiveMaxChildrenPerAgent: number;
  effectiveThinking?: unknown;
  allowedAgents: {
    id: string;
    name?: string;
  }[];
  allAgents: {
    id: string;
    name?: string;
  }[];
  configHash: string;
}

export interface DeckAgentsSubagentsSetParams {
  agentId: string;
  allowAgents: string[];
  model?: string;
  baseHash: string;
}

export interface DeckAgentsSubagentsSetResult {
  ok: boolean;
  agentId: string;
  allowAgents: string[];
  model?: string;
  configHash: string;
}

export interface DeckAgentsEventStreamsGetParams {
  agentId: string;
}

export interface DeckAgentsEventStreamsGetResult {
  agentId: string;
  eventStreams: string[];
  isDefault: boolean;
  configHash: string;
}

export interface DeckAgentsEventStreamsSetParams {
  agentId: string;
  eventStreams: string[];
  baseHash: string;
}

export interface DeckAgentsEventStreamsSetResult {
  ok: boolean;
  agentId: string;
  eventStreams: string[];
  configHash: string;
}

export interface DeckAgentsToolPolicyPreviewParams {
  agentId: string;
  context?: {
    channel?: string;
    chatType?: string;
  };
}

export interface DeckAgentsToolPolicyPreviewResult {
  layers: {
    label: string;
    ruleCount: number;
    effect: string;
  }[];
  tools: {
    name: string;
    allowed: boolean;
    decisiveLayer: string;
    trace: {
      layer: string;
      decision: string;
    }[];
  }[];
  configHash: string;
}

export interface DeckAgentsSystemPromptPreviewParams {
  agentId: string;
  context?: {
    channel?: string;
    chatType?: string;
  };
}

export interface DeckAgentsSystemPromptPreviewResult {
  layers: {
    label: string;
    source: string;
    charCount: number;
    fileCount: number;
  }[];
  bootstrapFiles: {
    name: string;
    exists: boolean;
    charCount: number;
  }[];
  totalChars: number;
  configHash: string;
}

export type DeckSubagentsListParams = {
  status?: "active" | "completed" | "failed" | "timeout" | "all";
  agentId?: string;
  requesterAgentId?: string;
  limit?: number;
  offset?: number;
};

export interface DeckSubagentsListResult {
  runs: {
    runId: string;
    childSessionKey: string;
    childAgentId: string;
    childAgentName?: string;
    requesterSessionKey: string;
    requesterAgentId: string;
    requesterAgentName?: string;
    task?: string;
    label?: string;
    model?: string;
    spawnMode: string;
    depth: number;
    createdAt: number;
    startedAt?: number;
    endedAt?: number;
    durationMs?: number;
    status: string;
    outcome?: unknown;
  }[];
  total: number;
}

export interface DeckSubagentsKillParams {
  runId: string;
}

export interface DeckSubagentsKillResult {
  ok: boolean;
  runId: string;
  childSessionKey: string;
}

export interface DeckSubagentsLineageParams {
  runId?: string;
  sessionKey?: string;
}

export interface DeckSubagentsLineageResult {
  root: {
    sessionKey: string;
    agentId: string;
    agentName?: string;
  };
  nodes: {
    runId: string;
    sessionKey: string;
    agentId: string;
    agentName?: string;
    task?: string;
    depth: number;
    parentRunId: string;
    status: string;
    durationMs?: number;
  }[];
}

export interface DeckSubagentsSteerParams {
  runId: string;
  instruction: string;
}

export interface DeckSubagentsSteerResult {
  success: boolean;
  dedupKey?: string;
  deduped?: boolean;
  newRunId?: string;
}

export type DeckIdentityListParams = Record<string, never>;

export interface DeckIdentityListResult {
  links: {
    canonical: string;
    peers: {
      channel: string;
      peerId: string;
    }[];
  }[];
  configHash: string;
}

export interface DeckIdentityLinkParams {
  canonical: string;
  channel: string;
  peerId: string;
  baseHash: string;
}

export interface DeckIdentityLinkResult {
  ok: boolean;
  configHash: string;
}

export interface DeckIdentityUnlinkParams {
  canonical: string;
  channel: string;
  peerId: string;
  baseHash: string;
}

export interface DeckIdentityUnlinkResult {
  ok: boolean;
  configHash: string;
}

export type DeckThreadsListParams = {
  agentId?: string;
  channel?: string;
  status?: "active" | "all";
};

export interface DeckThreadsListResult {
  threads: {
    threadId: string;
    channelId: string;
    agentId: string;
    targetSessionKey: string;
    targetKind: string;
    boundAt: number;
    lastActivityAt: number;
    accountId: string;
    boundBy: string;
    label?: string;
  }[];
}

export type DeckAuthOverviewResult = {
  providers: {
    provider: string;
    status: string;
    auth: {
      type: string;
      source: string;
      profileId?: string;
    } | null;
    oauth?: {
      expiresAt: number;
      remainingMs: number;
      status: string;
    };
    cooldown?: {
      reason: string;
      remainingMs: number;
      until: number;
    };
    usage?: {
      windows: {
        label: string;
        usedPercent: number;
        resetsInMs: number;
      }[];
      plan?: string;
    };
  }[];
};

export interface DeckAuthProbeResult {
  provider: string;
  model?: string;
  profileId?: string;
  label: string;
  source: string;
  mode?: string;
  status: string;
  reasonCode?: string;
  error?: string;
  latencyMs?: number;
}

export interface GatewayDescribeParams {
  filter?: string;
  includeSchemas?: boolean;
}

export interface GatewayDescribeResult {
  protocol: number;
  schemaVersion: string;
  methods: Record<
    string,
    {
      params?: Record<string, unknown>;
      result?: Record<string, unknown>;
      scope: string;
      since?: number;
    }
  >;
  events: Record<
    string,
    {
      payload?: Record<string, unknown>;
      since?: number;
    }
  >;
  untyped: string[];
}

export interface ToolsCatalogParams {
  agentId?: string;
  includePlugins?: boolean;
}

export type ToolsCatalogResult = {
  agentId: string;
  profiles: {
    id: "minimal" | "coding" | "messaging" | "full";
    label: string;
  }[];
  groups: {
    id: string;
    label: string;
    source: "core" | "plugin";
    pluginId?: string;
    tools: {
      id: string;
      label: string;
      description: string;
      source: "core" | "plugin";
      pluginId?: string;
      optional?: boolean;
      defaultProfiles: ("minimal" | "coding" | "messaging" | "full")[];
    }[];
  }[];
};

export interface ToolsEffectiveParams {
  agentId?: string;
  sessionKey: string;
}

export type ToolsEffectiveResult = {
  agentId: string;
  profile: string;
  groups: {
    id: "core" | "plugin" | "channel";
    label: string;
    source: "core" | "plugin" | "channel";
    tools: {
      id: string;
      label: string;
      description: string;
      rawDescription: string;
      source: "core" | "plugin" | "channel";
      pluginId?: string;
      channelId?: string;
    }[];
  }[];
};

export interface GatewayMethodMap {
  "chat.history": { params: ChatHistoryParams; result: ChatHistoryResult };
  "chat.abort": { params: ChatAbortParams; result: ChatAbortResult };
  "chat.send": { params: ChatSendParams; result: ChatSendResult };
  "config.get": { params: ConfigGetParams; result: ConfigGetResult };
  "config.schema": { params: ConfigSchemaParams; result: ConfigSchemaResult };
  "config.schema.lookup": { params: ConfigSchemaLookupParams; result: ConfigSchemaLookupResult };
  "config.apply": { params: ConfigApplyParams; result: ConfigApplyResult };
  "config.patch": { params: ConfigPatchParams; result: ConfigPatchResult };
  "config.set": { params: ConfigSetParams; result: ConfigSetResult };
  "skills.status": { params: SkillsStatusParams; result: unknown };
  "skills.bins": { params: SkillsBinsParams; result: SkillsBinsResult };
  "skills.install": { params: SkillsInstallParams; result: unknown };
  "skills.update": { params: SkillsUpdateParams; result: unknown };
  "cron.list": { params: CronListParams; result: unknown };
  "cron.status": { params: CronStatusParams; result: unknown };
  "cron.add": { params: CronAddParams; result: unknown };
  "cron.update": { params: CronUpdateParams; result: unknown };
  "cron.remove": { params: CronRemoveParams; result: unknown };
  "cron.run": { params: CronRunParams; result: unknown };
  "cron.runs": { params: CronRunsParams; result: unknown };
  "exec.approvals.get": { params: ExecApprovalsGetParams; result: ExecApprovalsGetResult };
  "exec.approvals.set": { params: ExecApprovalsSetParams; result: ExecApprovalsSetResult };
  "exec.approvals.node.get": {
    params: ExecApprovalsNodeGetParams;
    result: ExecApprovalsNodeGetResult;
  };
  "exec.approvals.node.set": {
    params: ExecApprovalsNodeSetParams;
    result: ExecApprovalsNodeSetResult;
  };
  "exec.approval.request": { params: ExecApprovalRequestParams; result: unknown };
  "exec.approval.resolve": { params: ExecApprovalResolveParams; result: unknown };
  "sessions.list": { params: SessionsListParams; result: SessionsListResult };
  "sessions.subscribe": { params: Record<string, unknown>; result: SessionsSubscribeResult };
  "sessions.unsubscribe": { params: Record<string, unknown>; result: SessionsUnsubscribeResult };
  "sessions.messages.subscribe": {
    params: SessionsMessagesSubscribeParams;
    result: SessionsMessagesSubscribeResult;
  };
  "sessions.messages.unsubscribe": {
    params: SessionsMessagesUnsubscribeParams;
    result: SessionsMessagesUnsubscribeResult;
  };
  "sessions.preview": { params: SessionsPreviewParams; result: SessionsPreviewResult };
  "sessions.get": { params: SessionsGetParams; result: SessionsGetResult };
  "sessions.create": { params: SessionsCreateParams; result: SessionsCreateResult };
  "sessions.send": { params: SessionsSendParams; result: SessionsSendResult };
  "sessions.steer": { params: SessionsSteerParams; result: SessionsSteerResult };
  "sessions.abort": { params: SessionsAbortParams; result: SessionsAbortResult };
  "sessions.patch": { params: SessionsPatchParams; result: SessionsPatchResult };
  "sessions.reset": { params: SessionsResetParams; result: SessionsResetResult };
  "sessions.clear": { params: SessionsClearParams; result: SessionsClearResult };
  "sessions.delete": { params: SessionsDeleteParams; result: SessionsDeleteResult };
  "sessions.compact": { params: SessionsCompactParams; result: SessionsCompactResult };
  "sessions.usage": { params: SessionsUsageParams; result: SessionsUsageResult };
  "sessions.usage.timeseries": {
    params: SessionsUsageTimeseriesParams;
    result: SessionsUsageTimeseriesResult;
  };
  "sessions.usage.logs": { params: SessionsUsageLogsParams; result: SessionsUsageLogsResult };
  "agent.identity.get": { params: AgentIdentityGetParams; result: AgentIdentityGetResult };
  "agent.wait": { params: AgentWaitParams; result: unknown };
  "agents.list": { params: AgentsListParams; result: AgentsListResult };
  "agents.create": { params: AgentsCreateParams; result: AgentsCreateResult };
  "agents.update": { params: AgentsUpdateParams; result: AgentsUpdateResult };
  "agents.delete": { params: AgentsDeleteParams; result: AgentsDeleteResult };
  "agents.files.list": { params: AgentsFilesListParams; result: AgentsFilesListResult };
  "agents.files.get": { params: AgentsFilesGetParams; result: AgentsFilesGetResult };
  "agents.files.set": { params: AgentsFilesSetParams; result: AgentsFilesSetResult };
  "channels.status": { params: ChannelsStatusParams; result: ChannelsStatusResult };
  "channels.logout": { params: ChannelsLogoutParams; result: unknown };
  "models.list": { params: ModelsListParams; result: ModelsListResult };
  "models.configured": { params: ModelsConfiguredParams; result: ModelsConfiguredResult };
  "logs.tail": { params: LogsTailParams; result: LogsTailResult };
  "deck.commands.discover": {
    params: DeckCommandsDiscoverParams;
    result: DeckCommandsDiscoverResult;
  };
  "deck.routing.list": { params: DeckRoutingListParams; result: DeckRoutingListResult };
  "deck.routing.add": { params: DeckRoutingAddParams; result: DeckRoutingAddResult };
  "deck.routing.remove": { params: DeckRoutingRemoveParams; result: DeckRoutingRemoveResult };
  "deck.routing.validate": { params: DeckRoutingValidateParams; result: DeckRoutingValidateResult };
  "deck.routing.simulate": { params: DeckRoutingSimulateParams; result: DeckRoutingSimulateResult };
  "deck.agents.detail": { params: DeckAgentsDetailParams; result: DeckAgentsDetailResult };
  "deck.agents.skills.get": {
    params: DeckAgentsSkillsGetParams;
    result: DeckAgentsSkillsGetResult;
  };
  "deck.agents.skills.set": {
    params: DeckAgentsSkillsSetParams;
    result: DeckAgentsSkillsSetResult;
  };
  "deck.agents.subagents.get": {
    params: DeckAgentsSubagentsGetParams;
    result: DeckAgentsSubagentsGetResult;
  };
  "deck.agents.subagents.set": {
    params: DeckAgentsSubagentsSetParams;
    result: DeckAgentsSubagentsSetResult;
  };
  "deck.agents.eventStreams.get": {
    params: DeckAgentsEventStreamsGetParams;
    result: DeckAgentsEventStreamsGetResult;
  };
  "deck.agents.eventStreams.set": {
    params: DeckAgentsEventStreamsSetParams;
    result: DeckAgentsEventStreamsSetResult;
  };
  "deck.agents.toolPolicy.preview": {
    params: DeckAgentsToolPolicyPreviewParams;
    result: DeckAgentsToolPolicyPreviewResult;
  };
  "deck.agents.systemPrompt.preview": {
    params: DeckAgentsSystemPromptPreviewParams;
    result: DeckAgentsSystemPromptPreviewResult;
  };
  "deck.subagents.list": { params: DeckSubagentsListParams; result: DeckSubagentsListResult };
  "deck.subagents.kill": { params: DeckSubagentsKillParams; result: DeckSubagentsKillResult };
  "deck.subagents.lineage": {
    params: DeckSubagentsLineageParams;
    result: DeckSubagentsLineageResult;
  };
  "deck.subagents.steer": { params: DeckSubagentsSteerParams; result: DeckSubagentsSteerResult };
  "deck.identity.list": { params: DeckIdentityListParams; result: DeckIdentityListResult };
  "deck.identity.link": { params: DeckIdentityLinkParams; result: DeckIdentityLinkResult };
  "deck.identity.unlink": { params: DeckIdentityUnlinkParams; result: DeckIdentityUnlinkResult };
  "deck.threads.list": { params: DeckThreadsListParams; result: DeckThreadsListResult };
  "deck.auth.overview": { params: Record<string, unknown>; result: DeckAuthOverviewResult };
  "deck.auth.probe": { params: Record<string, unknown>; result: DeckAuthProbeResult };
  "gateway.describe": { params: GatewayDescribeParams; result: GatewayDescribeResult };
  "tools.catalog": { params: ToolsCatalogParams; result: ToolsCatalogResult };
  "tools.effective": { params: ToolsEffectiveParams; result: ToolsEffectiveResult };
}

export type GatewayMethodName = keyof GatewayMethodMap;

export type ChatEventPayload = {
  runId: string;
  sessionKey: string;
  seq: number;
  state: "delta" | "final" | "aborted" | "error";
  message?: {
    id?: string;
    role: "user" | "assistant" | "system";
    content: (
      | {
          type: "text";
          text: string;
        }
      | {
          type: "thinking";
          text: string;
        }
      | {
          type: "tool_use";
          id: string;
          name: string;
          input: Record<string, unknown>;
        }
      | {
          type: "tool_result";
          toolUseId: string;
          content: string;
          isError?: boolean;
        }
      | {
          type: "image";
          data: string;
          mimeType: string;
          fileName?: string;
        }
      | {
          type: "file";
          data: string;
          mimeType: string;
          fileName: string;
          size?: number;
        }
    )[];
    timestamp: number;
  };
  errorMessage?: string;
  usage?: unknown;
  stopReason?: string;
  mediaUrl?: string;
  mediaUrls?: string[];
  mediaType?: string;
};

export interface AgentEventPayload {
  runId: string;
  seq: number;
  stream: string;
  ts: number;
  data: Record<string, unknown>;
}

export type SessionMessageEventPayload = {
  sessionKey: string;
  message: {
    id?: string;
    role: "user" | "assistant" | "system";
    content: (
      | {
          type: "text";
          text: string;
        }
      | {
          type: "thinking";
          text: string;
        }
      | {
          type: "tool_use";
          id: string;
          name: string;
          input: Record<string, unknown>;
        }
      | {
          type: "tool_result";
          toolUseId: string;
          content: string;
          isError?: boolean;
        }
      | {
          type: "image";
          data: string;
          mimeType: string;
          fileName?: string;
        }
      | {
          type: "file";
          data: string;
          mimeType: string;
          fileName: string;
          size?: number;
        }
    )[];
    timestamp: number;
  };
  messageId?: string;
  messageSeq?: number;
  updatedAt?: number;
  sessionId?: string;
  kind?: "direct" | "group" | "global" | "unknown";
  channel?: string;
  label?: string;
  displayName?: string;
  deliveryContext?: {
    channel?: string;
    to?: string;
    accountId?: string;
    threadId?: string;
  };
  parentSessionKey?: string;
  childSessions?: string[];
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
  systemSent?: boolean;
  abortedLastRun?: boolean;
  lastChannel?: string;
  lastTo?: string;
  lastAccountId?: string;
  totalTokens?: number;
  totalTokensFresh?: boolean;
  contextTokens?: number;
  estimatedCostUsd?: number;
  modelProvider?: string;
  model?: string;
  status?: "running" | "done" | "failed" | "killed" | "timeout";
  startedAt?: number;
  endedAt?: number;
  runtimeMs?: number;
};

export interface SessionToolEventPayload {
  runId: string;
  seq: number;
  stream: "tool";
  ts: number;
  sessionKey: string;
  data: {
    phase: string;
    name?: string;
    toolCallId?: string;
    args?: Record<string, unknown>;
    result?: string;
    partialResult?: string;
    isError?: boolean;
    error?: string;
  };
}

export type SessionsChangedEventPayload = {
  sessionKey: string;
  phase?: string;
  ts: number;
  runId?: string;
  messageId?: string;
  messageSeq?: number;
  reason?: string;
  parentSessionKey?: unknown;
  label?: unknown;
  displayName?: unknown;
  updatedAt?: number;
  sessionId?: string;
  kind?: "direct" | "group" | "global" | "unknown";
  channel?: string;
  deliveryContext?: {
    channel?: string;
    to?: string;
    accountId?: string;
    threadId?: string;
  };
  childSessions?: string[];
  thinkingLevel?: string;
  fastMode?: boolean;
  verboseLevel?: string;
  systemSent?: boolean;
  abortedLastRun?: boolean;
  lastChannel?: string;
  lastTo?: string;
  lastAccountId?: string;
  totalTokens?: number;
  totalTokensFresh?: boolean;
  contextTokens?: number;
  estimatedCostUsd?: number;
  modelProvider?: string;
  model?: string;
  status?: "running" | "done" | "failed" | "killed" | "timeout";
  startedAt?: number;
  endedAt?: number;
  runtimeMs?: number;
};

export interface GatewayEventPayloadMap {
  chat: ChatEventPayload;
  agent: AgentEventPayload;
  "session.message": SessionMessageEventPayload;
  "session.tool": SessionToolEventPayload;
  "sessions.changed": SessionsChangedEventPayload;
}

export type GatewayTypedEventName = keyof GatewayEventPayloadMap;
