/**
 * POST /api/skills/install — Install a skill.
 *
 * Gateway contract: skills.install { name, installId, timeoutMs? }
 * installId is generated by the frontend (crypto.randomUUID()).
 */
import { type NextRequest } from "next/server";
import { gatewayRequest } from "@/lib/api-helpers";
import { withAuth } from "@/lib/with-auth";

export const POST = withAuth(async (request: NextRequest) => {
  const body = (await request.json()) as { name: string; installId: string; timeoutMs?: number };
  return gatewayRequest("skills.install", body);
});
