// Auto-generated by scripts/gen-method-modules.ts - DO NOT EDIT
import type { GatewayMethodMetadataModule } from "../method-registry.js";
import { gatewayMethodMetadataModule as agentMetadataModule } from "./agent.method-defs.js";
import { gatewayMethodMetadataModule as agentsMetadataModule } from "./agents.method-defs.js";
import { gatewayMethodMetadataModule as chatMetadataModule } from "./chat.method-defs.js";
import { gatewayMethodMetadataModule as commandsMetadataModule } from "./commands.method-defs.js";
import { gatewayMethodMetadataModule as configMetadataModule } from "./config.method-defs.js";
import { gatewayMethodMetadataModule as controlPlaneMetadataModule } from "./control-plane.method-defs.js";
import { gatewayMethodMetadataModule as deckAuthMetadataModule } from "./deck-auth.method-defs.js";
import { gatewayMethodMetadataModule as deckPostAgentsMetadataModule } from "./deck-post-agents.method-defs.js";
import { gatewayMethodMetadataModule as deckMetadataModule } from "./deck.method-defs.js";
import { gatewayMethodMetadataModule as deckAgentsDetailMetadataModule } from "./deck/agents-detail.method-defs.js";
import { gatewayMethodMetadataModule as deckAgentsEventStreamsMetadataModule } from "./deck/agents-event-streams.method-defs.js";
import { gatewayMethodMetadataModule as deckAgentsPreviewSystemPromptMetadataModule } from "./deck/agents-preview-system-prompt.method-defs.js";
import { gatewayMethodMetadataModule as deckAgentsPreviewToolPolicyMetadataModule } from "./deck/agents-preview-tool-policy.method-defs.js";
import { gatewayMethodMetadataModule as deckAgentsSkillsMetadataModule } from "./deck/agents-skills.method-defs.js";
import { gatewayMethodMetadataModule as deckAgentsSubagentsConfigMetadataModule } from "./deck/agents-subagents-config.method-defs.js";
import { gatewayMethodMetadataModule as deckRoutingAddMetadataModule } from "./deck/routing-add.method-defs.js";
import { gatewayMethodMetadataModule as deckRoutingListMetadataModule } from "./deck/routing-list.method-defs.js";
import { gatewayMethodMetadataModule as deckRoutingRemoveMetadataModule } from "./deck/routing-remove.method-defs.js";
import { gatewayMethodMetadataModule as deckRoutingSimulateMetadataModule } from "./deck/routing-simulate.method-defs.js";
import { gatewayMethodMetadataModule as deckRoutingValidateMetadataModule } from "./deck/routing-validate.method-defs.js";
import { gatewayMethodMetadataModule as describeMetadataModule } from "./describe.method-defs.js";
import { gatewayMethodMetadataModule as deviceMetadataModule } from "./device.method-defs.js";
import { gatewayMethodMetadataModule as eventsMetadataModule } from "./events.method-defs.js";
import { gatewayMethodMetadataModule as gatewayBatchMetadataModule } from "./gateway-batch.method-defs.js";
import { gatewayMethodMetadataModule as logsMetadataModule } from "./logs.method-defs.js";
import { gatewayMethodMetadataModule as modelsCatalogProvidersMetadataModule } from "./models-catalog-providers.method-defs.js";
import { gatewayMethodMetadataModule as modelsConfiguredMetadataModule } from "./models-configured.method-defs.js";
import { gatewayMethodMetadataModule as modelsListMetadataModule } from "./models-list.method-defs.js";
import { gatewayMethodMetadataModule as nodeMetadataModule } from "./node.method-defs.js";
import { gatewayMethodMetadataModule as nodesPendingMetadataModule } from "./nodes-pending.method-defs.js";
import { gatewayMethodMetadataModule as sessionsMetadataModule } from "./sessions.method-defs.js";
import { gatewayMethodMetadataModule as skillsMetadataModule } from "./skills.method-defs.js";
import { gatewayMethodMetadataModule as talkMetadataModule } from "./talk.method-defs.js";
import { gatewayMethodMetadataModule as toolsCatalogMetadataModule } from "./tools-catalog.method-defs.js";
import { gatewayMethodMetadataModule as toolsEffectiveMetadataModule } from "./tools-effective.method-defs.js";
import { gatewayMethodMetadataModule as wizardMetadataModule } from "./wizard.method-defs.js";

export const gatewayMethodMetadataModules: readonly GatewayMethodMetadataModule[] = [
  agentMetadataModule,
  agentsMetadataModule,
  chatMetadataModule,
  commandsMetadataModule,
  configMetadataModule,
  controlPlaneMetadataModule,
  deckAuthMetadataModule,
  deckPostAgentsMetadataModule,
  deckMetadataModule,
  deckAgentsDetailMetadataModule,
  deckAgentsEventStreamsMetadataModule,
  deckAgentsPreviewSystemPromptMetadataModule,
  deckAgentsPreviewToolPolicyMetadataModule,
  deckAgentsSkillsMetadataModule,
  deckAgentsSubagentsConfigMetadataModule,
  deckRoutingAddMetadataModule,
  deckRoutingListMetadataModule,
  deckRoutingRemoveMetadataModule,
  deckRoutingSimulateMetadataModule,
  deckRoutingValidateMetadataModule,
  describeMetadataModule,
  deviceMetadataModule,
  eventsMetadataModule,
  gatewayBatchMetadataModule,
  logsMetadataModule,
  modelsCatalogProvidersMetadataModule,
  modelsConfiguredMetadataModule,
  modelsListMetadataModule,
  nodeMetadataModule,
  nodesPendingMetadataModule,
  sessionsMetadataModule,
  skillsMetadataModule,
  talkMetadataModule,
  toolsCatalogMetadataModule,
  toolsEffectiveMetadataModule,
  wizardMetadataModule,
];
