// Auto-generated by scripts/gen-method-modules.ts - DO NOT EDIT
import type { GatewayMethodModule } from "../method-registry.js";
import { gatewayMethodModule as agentModule } from "./agent.module.js";
import { gatewayMethodModule as agentsModule } from "./agents.module.js";
import { gatewayMethodModule as channelsModule } from "./channels.module.js";
import { gatewayMethodModule as chatModule } from "./chat.module.js";
import { gatewayMethodModule as commandsModule } from "./commands.module.js";
import { gatewayMethodModule as configModule } from "./config.module.js";
import { gatewayMethodModule as connectModule } from "./connect.module.js";
import { gatewayMethodModule as cronModule } from "./cron.module.js";
import { gatewayMethodModule as deckAuthModule } from "./deck-auth.module.js";
import { gatewayMethodModule as deckPostAgentsModule } from "./deck-post-agents.module.js";
import { gatewayMethodModule as deckModule } from "./deck.module.js";
import { gatewayMethodModule as deckAgentsDetailModule } from "./deck/agents-detail.module.js";
import { gatewayMethodModule as deckAgentsEventStreamsModule } from "./deck/agents-event-streams.module.js";
import { gatewayMethodModule as deckAgentsModelPolicyModule } from "./deck/agents-model-policy.module.js";
import { gatewayMethodModule as deckAgentsPreviewSystemPromptModule } from "./deck/agents-preview-system-prompt.module.js";
import { gatewayMethodModule as deckAgentsPreviewToolPolicyModule } from "./deck/agents-preview-tool-policy.module.js";
import { gatewayMethodModule as deckAgentsSkillsModule } from "./deck/agents-skills.module.js";
import { gatewayMethodModule as deckAgentsSubagentsConfigModule } from "./deck/agents-subagents-config.module.js";
import { gatewayMethodModule as deckRoutingAddModule } from "./deck/routing-add.module.js";
import { gatewayMethodModule as deckRoutingListModule } from "./deck/routing-list.module.js";
import { gatewayMethodModule as deckRoutingRemoveModule } from "./deck/routing-remove.module.js";
import { gatewayMethodModule as deckRoutingSimulateModule } from "./deck/routing-simulate.module.js";
import { gatewayMethodModule as deckRoutingValidateModule } from "./deck/routing-validate.module.js";
import { gatewayMethodModule as describeModule } from "./describe.module.js";
import { gatewayMethodModule as deviceModule } from "./device.module.js";
import { gatewayMethodModule as doctorModule } from "./doctor.module.js";
import { gatewayMethodModule as eventsModule } from "./events.module.js";
import { gatewayMethodModule as execApprovalsModule } from "./exec-approvals.module.js";
import { gatewayMethodModule as gatewayBatchModule } from "./gateway-batch.module.js";
import { gatewayMethodModule as healthModule } from "./health.module.js";
import { gatewayMethodModule as logsModule } from "./logs.module.js";
import { gatewayMethodModule as modelsCatalogProvidersModule } from "./models-catalog-providers.module.js";
import { gatewayMethodModule as modelsConfiguredModule } from "./models-configured.module.js";
import { gatewayMethodModule as modelsModule } from "./models.module.js";
import { gatewayMethodModule as nodesPendingModule } from "./nodes-pending.module.js";
import { gatewayMethodModule as nodesModule } from "./nodes.module.js";
import { gatewayMethodModule as pushModule } from "./push.module.js";
import { gatewayMethodModule as sendModule } from "./send.module.js";
import { gatewayMethodModule as sessionsModule } from "./sessions.module.js";
import { gatewayMethodModule as skillsModule } from "./skills.module.js";
import { gatewayMethodModule as systemModule } from "./system.module.js";
import { gatewayMethodModule as talkModule } from "./talk.module.js";
import { gatewayMethodModule as toolsCatalogModule } from "./tools-catalog.module.js";
import { gatewayMethodModule as toolsEffectiveModule } from "./tools-effective.module.js";
import { gatewayMethodModule as ttsModule } from "./tts.module.js";
import { gatewayMethodModule as updateModule } from "./update.module.js";
import { gatewayMethodModule as usageModule } from "./usage.module.js";
import { gatewayMethodModule as voicewakeModule } from "./voicewake.module.js";
import { gatewayMethodModule as webModule } from "./web.module.js";
import { gatewayMethodModule as wizardModule } from "./wizard.module.js";

export const gatewayMethodModules: readonly GatewayMethodModule[] = [
  agentModule,
  agentsModule,
  channelsModule,
  chatModule,
  commandsModule,
  configModule,
  connectModule,
  cronModule,
  deckAuthModule,
  deckPostAgentsModule,
  deckModule,
  deckAgentsDetailModule,
  deckAgentsEventStreamsModule,
  deckAgentsModelPolicyModule,
  deckAgentsPreviewSystemPromptModule,
  deckAgentsPreviewToolPolicyModule,
  deckAgentsSkillsModule,
  deckAgentsSubagentsConfigModule,
  deckRoutingAddModule,
  deckRoutingListModule,
  deckRoutingRemoveModule,
  deckRoutingSimulateModule,
  deckRoutingValidateModule,
  describeModule,
  deviceModule,
  doctorModule,
  eventsModule,
  execApprovalsModule,
  gatewayBatchModule,
  healthModule,
  logsModule,
  modelsCatalogProvidersModule,
  modelsConfiguredModule,
  modelsModule,
  nodesPendingModule,
  nodesModule,
  pushModule,
  sendModule,
  sessionsModule,
  skillsModule,
  systemModule,
  talkModule,
  toolsCatalogModule,
  toolsEffectiveModule,
  ttsModule,
  updateModule,
  usageModule,
  voicewakeModule,
  webModule,
  wizardModule,
];
