import type { MethodMetadata } from "../method-registry.js";
import { ADMIN_SCOPE, READ_SCOPE, WRITE_SCOPE } from "../method-scopes.js";
import {
  SessionsAbortParamsSchema,
  SessionsAbortResultSchema,
  SessionsClearParamsSchema,
  SessionsClearResultSchema,
  SessionsCompactParamsSchema,
  SessionsCompactResultSchema,
  SessionsCompactionBranchParamsSchema,
  SessionsCompactionBranchResultSchema,
  SessionsCompactionGetParamsSchema,
  SessionsCompactionGetResultSchema,
  SessionsCompactionListParamsSchema,
  SessionsCompactionListResultSchema,
  SessionsCompactionRestoreParamsSchema,
  SessionsCompactionRestoreResultSchema,
  SessionsCreateParamsSchema,
  SessionsCreateResultSchema,
  SessionsDeleteParamsSchema,
  SessionsDeleteResultSchema,
  SessionsGetParamsSchema,
  SessionsGetResultSchema,
  SessionsListParamsSchema,
  SessionsListResultSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesSubscriptionResultSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPatchResultSchema,
  SessionsPreviewParamsSchema,
  SessionsPreviewResultSchema,
  SessionsResetParamsSchema,
  SessionsResetResultSchema,
  SessionsSendParamsSchema,
  SessionsSendResultSchema,
  SessionsSubscribeResultSchema,
  SessionsUsageLogsResultSchema,
  SessionsUsageParamsSchema,
  SessionsUsageResultSchema,
  SessionsUsageTimeseriesResultSchema,
} from "../protocol/schema/sessions.js";

export const sessionsMethodDefs: Record<string, MethodMetadata> = {
  "sessions.list": {
    params: SessionsListParamsSchema,
    result: SessionsListResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.subscribe": {
    result: SessionsSubscribeResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.unsubscribe": {
    result: SessionsSubscribeResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.messages.subscribe": {
    params: SessionsMessagesSubscribeParamsSchema,
    result: SessionsMessagesSubscriptionResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.messages.unsubscribe": {
    params: SessionsMessagesUnsubscribeParamsSchema,
    result: SessionsMessagesSubscriptionResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.preview": {
    params: SessionsPreviewParamsSchema,
    result: SessionsPreviewResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.get": {
    params: SessionsGetParamsSchema,
    result: SessionsGetResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.create": {
    params: SessionsCreateParamsSchema,
    result: SessionsCreateResultSchema,
    scope: WRITE_SCOPE,
  },
  "sessions.send": {
    params: SessionsSendParamsSchema,
    result: SessionsSendResultSchema,
    scope: WRITE_SCOPE,
  },
  "sessions.steer": {
    params: SessionsSendParamsSchema,
    result: SessionsSendResultSchema,
    scope: WRITE_SCOPE,
  },
  "sessions.abort": {
    params: SessionsAbortParamsSchema,
    result: SessionsAbortResultSchema,
    scope: WRITE_SCOPE,
  },
  "sessions.patch": {
    params: SessionsPatchParamsSchema,
    result: SessionsPatchResultSchema,
    scope: ADMIN_SCOPE,
  },
  "sessions.reset": {
    params: SessionsResetParamsSchema,
    result: SessionsResetResultSchema,
    scope: ADMIN_SCOPE,
  },
  "sessions.clear": {
    params: SessionsClearParamsSchema,
    result: SessionsClearResultSchema,
    scope: ADMIN_SCOPE,
  },
  "sessions.delete": {
    params: SessionsDeleteParamsSchema,
    result: SessionsDeleteResultSchema,
    scope: ADMIN_SCOPE,
  },
  "sessions.compact": {
    params: SessionsCompactParamsSchema,
    result: SessionsCompactResultSchema,
    scope: ADMIN_SCOPE,
  },
  "sessions.compaction.list": {
    params: SessionsCompactionListParamsSchema,
    result: SessionsCompactionListResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.compaction.get": {
    params: SessionsCompactionGetParamsSchema,
    result: SessionsCompactionGetResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.compaction.branch": {
    params: SessionsCompactionBranchParamsSchema,
    result: SessionsCompactionBranchResultSchema,
    scope: WRITE_SCOPE,
  },
  "sessions.compaction.restore": {
    params: SessionsCompactionRestoreParamsSchema,
    result: SessionsCompactionRestoreResultSchema,
    scope: ADMIN_SCOPE,
  },
  "sessions.usage": {
    params: SessionsUsageParamsSchema,
    result: SessionsUsageResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.usage.timeseries": {
    params: SessionsUsageParamsSchema,
    result: SessionsUsageTimeseriesResultSchema,
    scope: READ_SCOPE,
  },
  "sessions.usage.logs": {
    params: SessionsUsageParamsSchema,
    result: SessionsUsageLogsResultSchema,
    scope: READ_SCOPE,
  },
};
