#!/usr/bin/env -S node --import tsx
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { formatGeneratedModule } from "./lib/format-generated-module.mjs";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const serverMethodsDir = resolve(repoRoot, "src/gateway/server-methods");
const runtimeOut = resolve(serverMethodsDir, "_modules.generated.ts");
const metadataOut = resolve(serverMethodsDir, "_method-defs.generated.ts");
const checkMode = process.argv.includes("--check");

type ManifestEntry = {
  importName: string;
  importPath: string;
};

function walkFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir).toSorted((left, right) => left.localeCompare(right))) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      files.push(...walkFiles(fullPath));
    } else if (stat.isFile()) {
      files.push(fullPath);
    }
  }
  return files;
}

function toImportName(filePath: string, suffix: ".module.ts" | ".method-defs.ts"): string {
  const relativePath = relative(serverMethodsDir, filePath).slice(0, -suffix.length);
  const parts = relativePath
    .split(sep)
    .flatMap((part) =>
      part.split(/[^A-Za-z0-9]+/).flatMap((segment) => (segment ? [segment] : [])),
    );
  const [first = "gateway", ...rest] = parts;
  return [
    first.toLowerCase(),
    ...rest.map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`),
    suffix === ".module.ts" ? "Module" : "MetadataModule",
  ].join("");
}

function toImportPath(filePath: string): string {
  const relativePath = relative(serverMethodsDir, filePath).replaceAll(sep, "/");
  return `./${relativePath.replace(/\.ts$/, ".js")}`;
}

function collectEntries(suffix: ".module.ts" | ".method-defs.ts"): ManifestEntry[] {
  return walkFiles(serverMethodsDir)
    .filter((filePath) => filePath.endsWith(suffix))
    .filter((filePath) => !filePath.endsWith(".generated.ts"))
    .map((filePath) => ({
      importName: toImportName(filePath, suffix),
      importPath: toImportPath(filePath),
    }))
    .toSorted((left, right) => left.importPath.localeCompare(right.importPath));
}

function renderRuntimeManifest(entries: readonly ManifestEntry[]): string {
  const lines = [
    "// Auto-generated by scripts/gen-method-modules.ts - DO NOT EDIT",
    'import type { GatewayMethodModule } from "../method-registry.js";',
  ];
  for (const entry of entries) {
    lines.push(`import { gatewayMethodModule as ${entry.importName} } from "${entry.importPath}";`);
  }
  lines.push("");
  lines.push("export const gatewayMethodModules: readonly GatewayMethodModule[] = [");
  for (const entry of entries) {
    lines.push(`  ${entry.importName},`);
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

function renderMetadataManifest(entries: readonly ManifestEntry[]): string {
  const lines = [
    "// Auto-generated by scripts/gen-method-modules.ts - DO NOT EDIT",
    'import type { GatewayMethodMetadataModule } from "../method-registry.js";',
  ];
  for (const entry of entries) {
    lines.push(
      `import { gatewayMethodMetadataModule as ${entry.importName} } from "${entry.importPath}";`,
    );
  }
  lines.push("");
  lines.push(
    "export const gatewayMethodMetadataModules: readonly GatewayMethodMetadataModule[] = [",
  );
  for (const entry of entries) {
    lines.push(`  ${entry.importName},`);
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

function formatGenerated(source: string, outputPath: string, errorLabel: string): string {
  return formatGeneratedModule(source, {
    repoRoot,
    outputPath,
    errorLabel,
  });
}

const generated = [
  {
    outputPath: runtimeOut,
    content: formatGenerated(
      renderRuntimeManifest(collectEntries(".module.ts")),
      runtimeOut,
      "gateway method runtime module manifest",
    ),
  },
  {
    outputPath: metadataOut,
    content: formatGenerated(
      renderMetadataManifest(collectEntries(".method-defs.ts")),
      metadataOut,
      "gateway method metadata module manifest",
    ),
  },
];

let failed = false;
for (const file of generated) {
  if (checkMode) {
    if (!existsSync(file.outputPath)) {
      console.error(`MISSING: ${relative(repoRoot, file.outputPath)}`);
      failed = true;
      continue;
    }
    const actual = readFileSync(file.outputPath, "utf8");
    if (actual !== file.content) {
      console.error(
        `DRIFT: ${relative(repoRoot, file.outputPath)} - run 'pnpm method-modules:gen'`,
      );
      failed = true;
    }
    continue;
  }
  mkdirSync(dirname(file.outputPath), { recursive: true });
  writeFileSync(file.outputPath, file.content);
  console.log(`wrote ${relative(repoRoot, file.outputPath)}`);
}

if (failed) {
  process.exitCode = 1;
} else if (checkMode) {
  console.log("check:method-modules-up-to-date - generated files are up to date");
}
