/**
 * TypeScript codegen for Gateway Protocol SDK.
 *
 * Reads registry metadata (side-effect-free) and emits:
 *   - dashboard/src/types/gateway-protocol.generated.ts (type definitions)
 *   - dashboard/src/types/gateway-client.generated.ts   (typed client + allowlist)
 *
 * Usage:
 *   bun scripts/protocol-gen-ts.ts          # generate
 *   bun scripts/protocol-gen-ts.ts --check  # verify up-to-date
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { TSchema } from "@sinclair/typebox";
import {
  PROTOCOL_VERSION,
  allEventNames,
  allMethodDefs,
  allMethodNames,
} from "../src/gateway/method-registry-data.js";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");
const PROTOCOL_OUT = resolve(ROOT, "dashboard/src/types/gateway-protocol.generated.ts");
const CLIENT_OUT = resolve(ROOT, "dashboard/src/types/gateway-client.generated.ts");
const CHECK_MODE = process.argv.includes("--check");

// ---------------------------------------------------------------------------
// Schema → TypeScript type string conversion
// ---------------------------------------------------------------------------

function schemaToTS(schema: TSchema, indent = 0): string {
  const pad = "  ".repeat(indent);
  // biome-ignore lint: TSchema is a broad type; narrow via runtime checks
  const s = schema as Record<string, unknown>;
  const kind = s.type as string | undefined;

  // Literal values (Type.Literal)
  if ("const" in s) {
    const val = s.const;
    return typeof val === "string" ? `"${val}"` : String(val);
  }

  // Primitives
  if (kind === "string") {
    return "string";
  }
  if (kind === "number" || kind === "integer") {
    return "number";
  }
  if (kind === "boolean") {
    return "boolean";
  }
  if (kind === "null") {
    return "null";
  }

  // Arrays (Type.Array)
  if (kind === "array") {
    const items = s.items as TSchema | undefined;
    if (!items) {
      return "unknown[]";
    }
    const inner = schemaToTS(items, indent);
    // Wrap union types in parens for correct array syntax
    return inner.includes("|") ? `(${inner})[]` : `${inner}[]`;
  }

  // Objects (Type.Object / Type.Record)
  if (kind === "object") {
    // Type.Record() → { patternProperties: { "^(.*)$": valueSchema } }
    const patternProps = s.patternProperties as Record<string, TSchema> | undefined;
    if (patternProps) {
      const valueSchema = Object.values(patternProps)[0];
      return valueSchema
        ? `Record<string, ${schemaToTS(valueSchema, indent)}>`
        : "Record<string, unknown>";
    }

    const props = s.properties as Record<string, TSchema> | undefined;
    // Empty object → empty body
    if (!props || Object.keys(props).length === 0) {
      return "{}";
    }

    const required = new Set((s.required as string[] | undefined) ?? []);
    const lines = Object.entries(props).map(([key, propSchema]) => {
      const opt = required.has(key) ? "" : "?";
      return `${pad}  ${key}${opt}: ${schemaToTS(propSchema, indent + 1)};`;
    });
    return `{\n${lines.join("\n")}\n${pad}}`;
  }

  // Union types (Type.Union → anyOf)
  if ("anyOf" in s) {
    const variants = s.anyOf as TSchema[];
    return variants.map((v) => schemaToTS(v, indent)).join(" | ");
  }

  return "unknown";
}

/** Check if a string is a valid JS identifier (safe to use unquoted as object key). */
function isSafeIdentifier(s: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(s);
}

function quoteKey(key: string): string {
  return isSafeIdentifier(key) ? key : `"${key}"`;
}

/** Convert dot-separated method name to PascalCase interface name. */
function methodToInterfaceName(method: string): string {
  return method
    .split(".")
    .map((seg) =>
      seg
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(""),
    )
    .join("");
}

// ---------------------------------------------------------------------------
// Generate gateway-protocol.generated.ts
// ---------------------------------------------------------------------------

function generateProtocolTypes(): string {
  const lines: string[] = [
    "// Auto-generated by scripts/protocol-gen-ts.ts — DO NOT EDIT",
    "",
    `export const GENERATED_SCHEMA_VERSION = "${PROTOCOL_VERSION}";`,
    "",
  ];

  const methodEntries: string[] = [];

  for (const [method, def] of Object.entries(allMethodDefs)) {
    if (!def.params && !def.result) {
      continue;
    }

    const safeName = methodToInterfaceName(method);

    if (def.params) {
      const body = schemaToTS(def.params);
      if (body === "{}") {
        lines.push(`export type ${safeName}Params = Record<string, never>;`);
      } else {
        lines.push(`export interface ${safeName}Params ${body}`);
      }
      lines.push("");
    }

    if (def.result) {
      const body = schemaToTS(def.result);
      if (body === "{}") {
        lines.push(`export type ${safeName}Result = Record<string, never>;`);
      } else {
        lines.push(`export interface ${safeName}Result ${body}`);
      }
      lines.push("");
    }

    const paramsType = def.params ? `${safeName}Params` : "Record<string, unknown>";
    const resultType = def.result ? `${safeName}Result` : "unknown";
    methodEntries.push(`  "${method}": { params: ${paramsType}; result: ${resultType} };`);
  }

  lines.push("export interface GatewayMethodMap {");
  lines.push(...methodEntries);
  lines.push("}");
  lines.push("");
  lines.push("export type GatewayMethodName = keyof GatewayMethodMap;");
  lines.push("");

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Generate gateway-client.generated.ts
// ---------------------------------------------------------------------------

type MethodTree = Map<string, MethodTree | string>; // leaf value = full method name

/**
 * Build a nested tree from dot-separated method names.
 * Handles collisions where a key is both a leaf method and a namespace prefix
 * (e.g. "agent" as leaf + "agent.wait" as subtree) by keeping the subtree
 * and attaching the leaf as a special "$call" entry.
 */
function buildMethodTree(methods: string[]): MethodTree {
  const root: MethodTree = new Map();
  for (const method of methods) {
    const parts = method.split(".");
    let node = root;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      const existing = node.get(part);
      if (existing === undefined) {
        const subtree: MethodTree = new Map();
        node.set(part, subtree);
        node = subtree;
      } else if (typeof existing === "string") {
        // Collision: key was a leaf, now also needs to be a namespace.
        // Convert to subtree and keep the leaf as "$call".
        const subtree: MethodTree = new Map();
        subtree.set("$call", existing);
        node.set(part, subtree);
        node = subtree;
      } else {
        node = existing;
      }
    }
    const lastPart = parts[parts.length - 1];
    const existingLeaf = node.get(lastPart);
    if (existingLeaf !== undefined && typeof existingLeaf !== "string") {
      // The key is already a subtree — attach leaf as "$call"
      existingLeaf.set("$call", method);
    } else {
      node.set(lastPart, method);
    }
  }
  return root;
}

function renderClientInterface(tree: MethodTree, lines: string[], depth: number) {
  const pad = "  ".repeat(depth);
  for (const [key, value] of tree) {
    const qk = quoteKey(key);
    if (typeof value === "string") {
      const method = value;
      const def = allMethodDefs[method];
      if (def?.params && def?.result) {
        const name = methodToInterfaceName(method);
        lines.push(
          `${pad}${qk}(params: import("./gateway-protocol.generated").${name}Params, options?: { timeoutMs?: number }): Promise<import("./gateway-protocol.generated").${name}Result>;`,
        );
      } else if (def?.params) {
        const name = methodToInterfaceName(method);
        lines.push(
          `${pad}${qk}(params: import("./gateway-protocol.generated").${name}Params, options?: { timeoutMs?: number }): Promise<unknown>;`,
        );
      } else {
        lines.push(
          `${pad}${qk}(params: Record<string, unknown>, options?: { timeoutMs?: number }): Promise<unknown>;`,
        );
      }
    } else {
      lines.push(`${pad}${qk}: {`);
      renderClientInterface(value, lines, depth + 1);
      lines.push(`${pad}};`);
    }
  }
}

function renderClientFactory(tree: MethodTree, lines: string[], depth: number) {
  const pad = "  ".repeat(depth);
  for (const [key, value] of tree) {
    const qk = quoteKey(key);
    if (typeof value === "string") {
      lines.push(`${pad}${qk}: call("${value}"),`);
    } else {
      lines.push(`${pad}${qk}: {`);
      renderClientFactory(value, lines, depth + 1);
      lines.push(`${pad}},`);
    }
  }
}

function generateClient(): string {
  const lines: string[] = [
    "// Auto-generated by scripts/protocol-gen-ts.ts — DO NOT EDIT",
    "",
    'import type { GatewayMethodMap, GatewayMethodName } from "./gateway-protocol.generated";',
    "",
    "export type GatewayRequestFn = <M extends GatewayMethodName>(",
    "  method: M,",
    '  params: GatewayMethodMap[M]["params"],',
    "  options?: { timeoutMs?: number },",
    ') => Promise<GatewayMethodMap[M]["result"]>;',
    "",
  ];

  // Allowlist of ALL known methods (including untyped)
  lines.push("export const GENERATED_METHOD_ALLOWLIST: ReadonlySet<string> = new Set([");
  for (const m of [...allMethodNames].toSorted()) {
    lines.push(`  "${m}",`);
  }
  lines.push("]);");
  lines.push("");

  // Event names
  lines.push("export const GENERATED_EVENT_NAMES: ReadonlySet<string> = new Set([");
  for (const e of [...allEventNames].toSorted()) {
    lines.push(`  "${e}",`);
  }
  lines.push("]);");
  lines.push("");

  // Build typed client interface + factory (only for typed methods)
  const typedMethods = Object.keys(allMethodDefs).filter(
    (m) => allMethodDefs[m].params || allMethodDefs[m].result,
  );
  const tree = buildMethodTree(typedMethods);

  lines.push("export interface GatewayClient {");
  renderClientInterface(tree, lines, 1);
  lines.push("}");
  lines.push("");

  lines.push("export function createGatewayClient(request: GatewayRequestFn): GatewayClient {");
  lines.push("  const call = <M extends GatewayMethodName>(method: M) =>");
  lines.push('    (params: GatewayMethodMap[M]["params"], options?: { timeoutMs?: number }) =>');
  lines.push("      request(method, params, options);");
  lines.push("");
  lines.push("  return {");
  renderClientFactory(tree, lines, 2);
  lines.push("  };");
  lines.push("}");
  lines.push("");

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const protocolContent = generateProtocolTypes();
const clientContent = generateClient();

if (CHECK_MODE) {
  let exitCode = 0;
  for (const [filePath, expected] of [
    [PROTOCOL_OUT, protocolContent],
    [CLIENT_OUT, clientContent],
  ] as const) {
    if (!existsSync(filePath)) {
      console.error(`MISSING: ${filePath}`);
      exitCode = 1;
      continue;
    }
    const actual = readFileSync(filePath, "utf-8");
    if (actual !== expected) {
      console.error(`DRIFT: ${filePath} — run 'pnpm protocol:gen:ts' to regenerate`);
      exitCode = 1;
    }
  }
  if (exitCode === 0) {
    console.log("protocol:gen:check — all files up to date");
  }
  process.exit(exitCode);
} else {
  mkdirSync(dirname(PROTOCOL_OUT), { recursive: true });
  mkdirSync(dirname(CLIENT_OUT), { recursive: true });
  writeFileSync(PROTOCOL_OUT, protocolContent);
  writeFileSync(CLIENT_OUT, clientContent);
  console.log(`wrote ${PROTOCOL_OUT}`);
  console.log(`wrote ${CLIENT_OUT}`);
}
