// Contract-shaped mock data for models prototype.
// Shapes match DeckGo* DTOs in deck-go/contracts/source/deck-api.contract.ts:
//   DeckGoModelsConfigResponse, DeckGoModelAuthProvider,
//   DeckGoModelAuthOverviewResponse, DeckGoCatalogProvider,
//   DeckGoModelCatalogProvidersResponse, DeckGoModelProbeResponse,
//   DeckGoUsageCostResponse, DeckGoUsageProvidersResponse.
//
// `runtimeModels` (list of DeckGoRuntimeConfiguredModel) is what `models.configured`
// returns from the runtime; the panel projects providers + models from that.

window.MOCK = {
  // ── DeckGoModelsConfigResponse ─────────────────────────────────────────
  modelsConfig: {
    raw: JSON.stringify(
      {
        providers: {
          anthropic: {
            default: "claude-opus-4-7",
            fallbacks: ["claude-sonnet-4-6", "claude-haiku-4-5"],
          },
          openai: { default: "gpt-5.4" },
          google: { default: "gemini-2.5-pro" },
        },
        models: {
          "claude-opus-4-7": {
            provider: "anthropic",
            contextWindow: 1_000_000,
            maxTokens: 8192,
            reasoning: true,
          },
          "claude-sonnet-4-6": { provider: "anthropic", contextWindow: 1_000_000, maxTokens: 8192 },
          "claude-haiku-4-5": { provider: "anthropic", contextWindow: 200_000, maxTokens: 8192 },
          "gpt-5.4": {
            provider: "openai",
            contextWindow: 256_000,
            maxTokens: 16384,
            reasoning: true,
          },
          "gpt-5.4-mini": { provider: "openai", contextWindow: 128_000, maxTokens: 8192 },
          "gemini-2.5-pro": { provider: "google", contextWindow: 1_000_000, maxTokens: 8192 },
          "gemini-2.5-flash": { provider: "google", contextWindow: 1_000_000, maxTokens: 8192 },
          "ollama:llama-4": {
            provider: "ollama",
            contextWindow: 32_768,
            maxTokens: 8192,
            local: true,
          },
          "ollama:qwen-3": {
            provider: "ollama",
            contextWindow: 65_536,
            maxTokens: 8192,
            local: true,
          },
        },
      },
      null,
      2,
    ),
    hash: "models-cfg-v019",
  },

  // ── DeckGoRuntimeConfiguredModel projection (runtime view) ─────────────
  runtimeModels: [
    {
      id: "claude-opus-4-7",
      provider: "anthropic",
      family: "claude-4",
      displayName: "Claude Opus 4.7",
      contextWindow: 1_000_000,
      maxTokens: 8192,
      reasoning: true,
      isDefault: true,
      fallback: false,
      lastUsedMs: 1714679800000,
    },
    {
      id: "claude-sonnet-4-6",
      provider: "anthropic",
      family: "claude-4",
      displayName: "Claude Sonnet 4.6",
      contextWindow: 1_000_000,
      maxTokens: 8192,
      reasoning: true,
      isDefault: false,
      fallback: true,
      lastUsedMs: 1714676000000,
    },
    {
      id: "claude-haiku-4-5",
      provider: "anthropic",
      family: "claude-4",
      displayName: "Claude Haiku 4.5",
      contextWindow: 200_000,
      maxTokens: 8192,
      reasoning: false,
      isDefault: false,
      fallback: true,
      lastUsedMs: 1714670000000,
    },
    {
      id: "gpt-5.4",
      provider: "openai",
      family: "gpt-5",
      displayName: "GPT-5.4",
      contextWindow: 256_000,
      maxTokens: 16384,
      reasoning: true,
      isDefault: true,
      fallback: false,
      lastUsedMs: 1714679400000,
    },
    {
      id: "gpt-5.4-mini",
      provider: "openai",
      family: "gpt-5",
      displayName: "GPT-5.4 Mini",
      contextWindow: 128_000,
      maxTokens: 8192,
      reasoning: false,
      isDefault: false,
      fallback: true,
      lastUsedMs: 1714660000000,
    },
    {
      id: "gemini-2.5-pro",
      provider: "google",
      family: "gemini-2.5",
      displayName: "Gemini 2.5 Pro",
      contextWindow: 1_000_000,
      maxTokens: 8192,
      reasoning: true,
      isDefault: true,
      fallback: false,
      lastUsedMs: 1714670000000,
    },
    {
      id: "gemini-2.5-flash",
      provider: "google",
      family: "gemini-2.5",
      displayName: "Gemini 2.5 Flash",
      contextWindow: 1_000_000,
      maxTokens: 8192,
      reasoning: false,
      isDefault: false,
      fallback: true,
      lastUsedMs: 1714650000000,
    },
    {
      id: "ollama:llama-4",
      provider: "ollama",
      family: "llama-4",
      displayName: "Llama 4 (local)",
      contextWindow: 32_768,
      maxTokens: 8192,
      reasoning: false,
      isDefault: true,
      fallback: false,
      local: true,
      lastUsedMs: 1714630000000,
    },
    {
      id: "ollama:qwen-3",
      provider: "ollama",
      family: "qwen-3",
      displayName: "Qwen 3 (local)",
      contextWindow: 65_536,
      maxTokens: 8192,
      reasoning: false,
      isDefault: false,
      fallback: false,
      local: true,
      lastUsedMs: null,
    },
  ],

  // ── DeckGoModelAuthOverviewResponse.providers ──────────────────────────
  authProviders: [
    {
      provider: "anthropic",
      status: "ready",
      source: "env",
      scope: "user",
      configPresent: true,
      authPresent: true,
      editable: true,
      auth: { type: "apiKey", source: "ANTHROPIC_API_KEY env", profileId: null },
      oauth: undefined,
      cooldown: undefined,
      usage: {
        plan: "team",
        windows: [
          { label: "minute", usedPercent: 12, resetsInMs: 24_000 },
          { label: "hour", usedPercent: 38, resetsInMs: 1_540_000 },
          { label: "day", usedPercent: 64, resetsInMs: 26_400_000 },
        ],
      },
    },
    {
      provider: "openai",
      status: "ready",
      source: "config",
      scope: "user",
      configPresent: true,
      authPresent: true,
      editable: true,
      auth: { type: "apiKey", source: "openclaw.json", profileId: "ops" },
      usage: {
        plan: "tier3",
        windows: [
          { label: "minute", usedPercent: 9, resetsInMs: 18_000 },
          { label: "hour", usedPercent: 22, resetsInMs: 1_400_000 },
        ],
      },
    },
    {
      provider: "google",
      status: "cooldown",
      source: "oauth",
      scope: "user",
      configPresent: true,
      authPresent: true,
      editable: true,
      auth: { type: "oauth", source: "google-cloud-sdk", profileId: "primary" },
      oauth: { expiresAt: 1714766400000, remainingMs: 86_400_000, status: "active" },
      cooldown: { reason: "rate-limit", remainingMs: 240_000, until: 1714680240000 },
    },
    {
      provider: "ollama",
      status: "ready",
      source: "local",
      scope: "user",
      configPresent: true,
      authPresent: false,
      editable: true,
      auth: { type: null, source: "http://localhost:11434" },
    },
    {
      provider: "openrouter",
      status: "missing",
      source: "config",
      scope: "user",
      configPresent: false,
      authPresent: false,
      editable: true,
      auth: null,
    },
  ],

  // ── DeckGoModelCatalogProvidersResponse.providers ──────────────────────
  catalogProviders: [
    {
      id: "anthropic",
      displayName: "Anthropic",
      modelCount: 3,
      defaultBaseUrl: "https://api.anthropic.com/v1",
      authType: "apiKey",
      api: "anthropic-messages",
      models: [
        {
          id: "claude-opus-4-7",
          name: "Claude Opus 4.7",
          contextWindow: 1_000_000,
          maxTokens: 8192,
          reasoning: true,
        },
        {
          id: "claude-sonnet-4-6",
          name: "Claude Sonnet 4.6",
          contextWindow: 1_000_000,
          maxTokens: 8192,
          reasoning: true,
        },
        {
          id: "claude-haiku-4-5",
          name: "Claude Haiku 4.5",
          contextWindow: 200_000,
          maxTokens: 8192,
          reasoning: false,
        },
      ],
    },
    {
      id: "openai",
      displayName: "OpenAI",
      modelCount: 4,
      defaultBaseUrl: "https://api.openai.com/v1",
      authType: "apiKey",
      api: "openai-chat",
      models: [
        {
          id: "gpt-5.4",
          name: "GPT-5.4",
          contextWindow: 256_000,
          maxTokens: 16384,
          reasoning: true,
        },
        {
          id: "gpt-5.4-mini",
          name: "GPT-5.4 Mini",
          contextWindow: 128_000,
          maxTokens: 8192,
          reasoning: false,
        },
        {
          id: "o4-mini",
          name: "o4 Mini",
          contextWindow: 200_000,
          maxTokens: 8192,
          reasoning: true,
        },
        {
          id: "gpt-5.4-vision",
          name: "GPT-5.4 Vision",
          contextWindow: 128_000,
          maxTokens: 4096,
          reasoning: false,
        },
      ],
    },
    {
      id: "google",
      displayName: "Google AI",
      modelCount: 2,
      defaultBaseUrl: "https://generativelanguage.googleapis.com/v1",
      authType: "oauth",
      api: "vertex-google",
      models: [
        {
          id: "gemini-2.5-pro",
          name: "Gemini 2.5 Pro",
          contextWindow: 1_000_000,
          maxTokens: 8192,
          reasoning: true,
        },
        {
          id: "gemini-2.5-flash",
          name: "Gemini 2.5 Flash",
          contextWindow: 1_000_000,
          maxTokens: 8192,
          reasoning: false,
        },
      ],
    },
    {
      id: "ollama",
      displayName: "Ollama (local)",
      modelCount: 6,
      defaultBaseUrl: "http://localhost:11434",
      authType: "none",
      api: "openai-compat",
      models: [
        { id: "ollama:llama-4", name: "Llama 4", contextWindow: 32_768, maxTokens: 8192 },
        { id: "ollama:qwen-3", name: "Qwen 3", contextWindow: 65_536, maxTokens: 8192 },
      ],
    },
    {
      id: "openrouter",
      displayName: "OpenRouter",
      modelCount: 312,
      defaultBaseUrl: "https://openrouter.ai/api/v1",
      authType: "apiKey",
      api: "openai-compat",
      models: [],
    },
  ],

  // ── DeckGoModelProbeResponse.payload (per model id) ────────────────────
  probe: {
    "claude-opus-4-7": {
      provider: "anthropic",
      model: "claude-opus-4-7",
      status: "ok",
      latencyMs: 215,
    },
    "claude-sonnet-4-6": {
      provider: "anthropic",
      model: "claude-sonnet-4-6",
      status: "ok",
      latencyMs: 168,
    },
    "claude-haiku-4-5": {
      provider: "anthropic",
      model: "claude-haiku-4-5",
      status: "ok",
      latencyMs: 122,
    },
    "gpt-5.4": { provider: "openai", model: "gpt-5.4", status: "ok", latencyMs: 312 },
    "gpt-5.4-mini": { provider: "openai", model: "gpt-5.4-mini", status: "ok", latencyMs: 188 },
    "gemini-2.5-pro": {
      provider: "google",
      model: "gemini-2.5-pro",
      status: "cooldown",
      reasonCode: "rate-limit",
      error: "rate-limit cooldown 4m",
      latencyMs: 0,
    },
    "gemini-2.5-flash": {
      provider: "google",
      model: "gemini-2.5-flash",
      status: "cooldown",
      reasonCode: "rate-limit",
      error: "rate-limit cooldown 4m",
      latencyMs: 0,
    },
    "ollama:llama-4": { provider: "ollama", model: "ollama:llama-4", status: "ok", latencyMs: 88 },
    "ollama:qwen-3": {
      provider: "ollama",
      model: "ollama:qwen-3",
      status: "unknown",
      error: "no recent probe",
    },
  },

  // ── DeckGoUsageCostResponse + DeckGoUsageProvidersResponse ─────────────
  usage: {
    cost: {
      runtimeId: "main",
      currency: "USD",
      totals: { in: 18.42, out: 26.81 },
      perProvider: {
        anthropic: { in: 12.41, out: 18.62 },
        openai: { in: 4.55, out: 6.92 },
        google: { in: 1.46, out: 1.27 },
        ollama: { in: 0, out: 0 },
      },
      perModel: {
        "claude-opus-4-7": { in: 8.14, out: 12.55, requests: 312 },
        "claude-sonnet-4-6": { in: 3.42, out: 5.12, requests: 244 },
        "claude-haiku-4-5": { in: 0.85, out: 0.95, requests: 168 },
        "gpt-5.4": { in: 3.92, out: 5.88, requests: 198 },
        "gpt-5.4-mini": { in: 0.63, out: 1.04, requests: 145 },
        "gemini-2.5-pro": { in: 1.22, out: 1.05, requests: 80 },
        "gemini-2.5-flash": { in: 0.24, out: 0.22, requests: 31 },
      },
    },
    providers: [
      {
        provider: "anthropic",
        status: "ready",
        quotaPercent: 38,
        requestsPerMin: 24,
        errorRatePercent: 0.4,
      },
      {
        provider: "openai",
        status: "ready",
        quotaPercent: 22,
        requestsPerMin: 12,
        errorRatePercent: 0.2,
      },
      {
        provider: "google",
        status: "cooldown",
        quotaPercent: 86,
        requestsPerMin: 0,
        errorRatePercent: 8.5,
      },
      {
        provider: "ollama",
        status: "ready",
        quotaPercent: 0,
        requestsPerMin: 4,
        errorRatePercent: 0,
      },
      {
        provider: "openrouter",
        status: "missing",
        quotaPercent: 0,
        requestsPerMin: 0,
        errorRatePercent: 0,
      },
    ],
  },

  // ── Pricing per model (provider-published, snapshot) ───────────────────
  pricing: {
    "claude-opus-4-7": { inputPer1MTokens: 15, outputPer1MTokens: 75, source: "anthropic 2026-04" },
    "claude-sonnet-4-6": {
      inputPer1MTokens: 3,
      outputPer1MTokens: 15,
      source: "anthropic 2026-04",
    },
    "claude-haiku-4-5": {
      inputPer1MTokens: 0.8,
      outputPer1MTokens: 4,
      source: "anthropic 2026-04",
    },
    "gpt-5.4": { inputPer1MTokens: 5, outputPer1MTokens: 15, source: "openai 2026-04" },
    "gpt-5.4-mini": { inputPer1MTokens: 0.5, outputPer1MTokens: 1.5, source: "openai 2026-04" },
    "gemini-2.5-pro": { inputPer1MTokens: 1.25, outputPer1MTokens: 5, source: "google 2026-04" },
    "gemini-2.5-flash": {
      inputPer1MTokens: 0.075,
      outputPer1MTokens: 0.3,
      source: "google 2026-04",
    },
    "ollama:llama-4": { inputPer1MTokens: 0, outputPer1MTokens: 0, source: "local" },
    "ollama:qwen-3": { inputPer1MTokens: 0, outputPer1MTokens: 0, source: "local" },
  },

  // ── Audit log entries (BFF projection over config patches) ─────────────
  audit: [
    {
      ts: 1714679800000,
      model: "claude-opus-4-7",
      actor: "ops@deck-go",
      action: "set-default",
      before: "claude-sonnet-4-6",
      after: "claude-opus-4-7",
    },
    {
      ts: 1714670000000,
      model: "gpt-5.4",
      actor: "main@deck-go",
      action: "rotate-key",
      note: "ANTHROPIC_API_KEY → openclaw.json",
    },
    {
      ts: 1714600000000,
      model: "gemini-2.5-pro",
      actor: "ops@deck-go",
      action: "added-fallback",
      chain: ["gemini-2.5-pro", "gemini-2.5-flash"],
    },
    {
      ts: 1714500000000,
      model: "ollama:llama-4",
      actor: "main@deck-go",
      action: "added",
      source: "ollama-local",
    },
  ],
};
