import assert from "node:assert/strict";
import { parseContractSource, renderDeckApiArtifacts } from "./deck-api-codegen.mjs";

const source = `export const DeckGoDefaultRuntimeId = "rt_local";
export type DeckGoStatus = "ok" | "warn" | "over";
export interface DeckGoChild {
  name: string;
}
export interface DeckGoThing {
  id: string;
  enabled?: boolean;
  score?: number | null;
  status?: DeckGoStatus;
  tags: string[];
  children?: Array<DeckGoChild>;
  meta?: Record<string, unknown>;
  labels?: Record<string, string>;
  mode?: "bundled" | "remote";
  openStatus?: string & {};
  statusList?: DeckGoThing["status"][];
}
export type DeckGoThingAlias = DeckGoThing;
export type DeckGoInline = {
  name: string;
  active?: boolean;
};
export type DeckGoFlexible = Record<string, unknown> & {
  ok?: boolean;
  message?: string;
};
`;

const parsed = parseContractSource(source);
assert.deepEqual(
  parsed.declarations.map((declaration) => `${declaration.kind}:${declaration.name}`),
  [
    "const:DeckGoDefaultRuntimeId",
    "type:DeckGoStatus",
    "interface:DeckGoChild",
    "interface:DeckGoThing",
    "type:DeckGoThingAlias",
    "type:DeckGoInline",
    "type:DeckGoFlexible",
  ],
);

const artifacts = renderDeckApiArtifacts(source);

assert.equal(
  artifacts.ts,
  `// AUTO-GENERATED FROM contracts/source/deck-api.contract.ts
// Do not edit this file directly.

${source}`,
);

assert.match(artifacts.go, /const DeckGoDefaultRuntimeId = "rt_local"/);
assert.match(artifacts.go, /type DeckGoStatus string/);
assert.match(artifacts.go, /type DeckGoChild struct {\n\tName string `json:"name"`\n}/);
assert.match(artifacts.go, /\tEnabled bool `json:"enabled,omitempty"`/);
assert.match(artifacts.go, /\tScore float64 `json:"score,omitempty"`/);
assert.match(artifacts.go, /\tStatus DeckGoStatus `json:"status,omitempty"`/);
assert.match(artifacts.go, /\tTags \[\]string `json:"tags"`/);
assert.match(artifacts.go, /\tChildren \[\]DeckGoChild `json:"children,omitempty"`/);
assert.match(artifacts.go, /\tMeta map\[string\]any `json:"meta,omitempty"`/);
assert.match(artifacts.go, /\tLabels map\[string\]string `json:"labels,omitempty"`/);
assert.match(artifacts.go, /\tMode string `json:"mode,omitempty"`/);
assert.match(artifacts.go, /\tOpenStatus string `json:"openStatus,omitempty"`/);
assert.match(artifacts.go, /\tStatusList \[\]string `json:"statusList,omitempty"`/);
assert.match(artifacts.go, /type DeckGoThingAlias = DeckGoThing/);
assert.match(
  artifacts.go,
  /type DeckGoInline struct {\n\tName string `json:"name"`\n\tActive bool `json:"active,omitempty"`\n}/,
);
assert.match(
  artifacts.go,
  /type DeckGoFlexible struct {\n\tOk bool `json:"ok,omitempty"`\n\tMessage string `json:"message,omitempty"`\n}/,
);

console.log("deck-api codegen assertions passed");
