import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { allMethodNames } from "../../../src/gateway/method-registry-data.js";
import {
  CONTRACTS_ROOT,
  DECK_GO_ROOT,
  REPO_ROOT,
  eventDefs,
  eventNames,
  methodDefs,
} from "./protocol-common.js";

type ContractException = {
  exitCriteria?: string;
  id?: string;
  kind?: string;
  method?: string;
  owner?: string;
  reason?: string;
};

type MethodCoverage = {
  documented: boolean;
  hasParamsSchema: boolean;
  hasResultSchema: boolean;
  method: string;
};

type GatewayDescribeCompletenessReport = {
  generatedAt: string;
  authority: string;
  summary: {
    documentedDynamicMethods: number;
    eventPayloadSchemas: number;
    events: number;
    methods: number;
    resultSchemas: number;
    typedMethods: number;
    untypedMethods: number;
  };
  methods: {
    typed: string[];
    untyped: MethodCoverage[];
    withoutResultSchema: MethodCoverage[];
  };
  events: {
    withPayloadSchema: string[];
    withoutPayloadSchema: string[];
  };
  exceptions: {
    missingKnownMethod: ContractException[];
    unused: ContractException[];
  };
  failures: string[];
};

const exceptionSourcePath = resolve(CONTRACTS_ROOT, "source/deck-exceptions.contract.json");
const jsonOutPath = resolve(DECK_GO_ROOT, "docs/gateway-describe-completeness.json");
const markdownOutPath = resolve(DECK_GO_ROOT, "docs/gateway-describe-completeness.md");
const checkMode = process.env.CHECK_MODE === "1" || process.argv.includes("--check");

function repoPath(path: string): string {
  return relative(REPO_ROOT, path).replaceAll("\\", "/");
}

function readExceptionRegistry(): ContractException[] {
  if (!existsSync(exceptionSourcePath)) {
    return [];
  }
  const parsed = JSON.parse(readFileSync(exceptionSourcePath, "utf8")) as {
    exceptions?: ContractException[];
  };
  return parsed.exceptions ?? [];
}

function coverageFor(method: string, exceptionMethods: ReadonlySet<string>): MethodCoverage {
  const def = methodDefs[method];
  return {
    documented: exceptionMethods.has(method),
    hasParamsSchema: Boolean(def?.params),
    hasResultSchema: Boolean(def?.result),
    method,
  };
}

function buildReport(): GatewayDescribeCompletenessReport {
  const knownMethods = [...allMethodNames].toSorted((left, right) => left.localeCompare(right));
  const knownMethodSet = new Set(knownMethods);
  const exceptions = readExceptionRegistry();
  const exceptionMethods = new Set(
    exceptions
      .map((entry) => entry.method)
      .filter((method): method is string => typeof method === "string" && method.length > 0),
  );

  const typed = knownMethods.filter(
    (method) => methodDefs[method]?.params || methodDefs[method]?.result,
  );
  const untyped = knownMethods
    .filter((method) => !methodDefs[method]?.params && !methodDefs[method]?.result)
    .map((method) => coverageFor(method, exceptionMethods));
  const withoutResultSchema = typed
    .filter((method) => !methodDefs[method]?.result)
    .map((method) => coverageFor(method, exceptionMethods));
  const withPayloadSchema = eventNames
    .filter((eventName) => Boolean(eventDefs[eventName]?.payload))
    .toSorted((left, right) => left.localeCompare(right));
  const withoutPayloadSchema = eventNames
    .filter((eventName) => !eventDefs[eventName]?.payload)
    .toSorted((left, right) => left.localeCompare(right));
  const missingKnownMethod = exceptions.filter(
    (entry) => entry.method && !knownMethodSet.has(entry.method),
  );
  const unused = exceptions.filter((entry) => !entry.method);

  const failures = missingKnownMethod.map(
    (entry) => `deck exception references unknown gateway method: ${entry.method}`,
  );

  return {
    generatedAt: "1970-01-01T00:00:00.000Z",
    authority:
      "Generated from src/gateway/method-registry-data.ts and deck-go/contracts/source/deck-exceptions.contract.json. Runtime gateway.describe alignment is verified by focused Gateway tests.",
    summary: {
      documentedDynamicMethods: exceptionMethods.size,
      eventPayloadSchemas: withPayloadSchema.length,
      events: eventNames.length,
      methods: knownMethods.length,
      resultSchemas: knownMethods.filter((method) => Boolean(methodDefs[method]?.result)).length,
      typedMethods: typed.length,
      untypedMethods: untyped.length,
    },
    methods: {
      typed,
      untyped,
      withoutResultSchema,
    },
    events: {
      withPayloadSchema,
      withoutPayloadSchema,
    },
    exceptions: {
      missingKnownMethod,
      unused,
    },
    failures,
  };
}

function renderMarkdown(report: GatewayDescribeCompletenessReport): string {
  const lines = [
    "# Gateway Describe Completeness",
    "",
    "<!-- Generated by deck-go/contracts/scripts/gateway-describe-completeness.ts. Do not edit by hand. -->",
    "",
    `Authority: ${report.authority}`,
    "",
    "## Summary",
    "",
    `- Methods: ${report.summary.methods}`,
    `- Typed methods: ${report.summary.typedMethods}`,
    `- Untyped methods: ${report.summary.untypedMethods}`,
    `- Result schemas: ${report.summary.resultSchemas}`,
    `- Events: ${report.summary.events}`,
    `- Event payload schemas: ${report.summary.eventPayloadSchemas}`,
    `- Documented dynamic methods: ${report.summary.documentedDynamicMethods}`,
    "",
    "## Untyped Methods",
    "",
    "| Method | Documented |",
    "| --- | --- |",
  ];

  for (const entry of report.methods.untyped) {
    lines.push(`| \`${entry.method}\` | ${entry.documented ? "yes" : "no"} |`);
  }
  if (report.methods.untyped.length === 0) {
    lines.push("| n/a | n/a |");
  }

  lines.push(
    "",
    "## Methods Without Result Schema",
    "",
    "| Method | Params Schema | Documented |",
    "| --- | --- | --- |",
  );
  for (const entry of report.methods.withoutResultSchema) {
    lines.push(
      `| \`${entry.method}\` | ${entry.hasParamsSchema ? "yes" : "no"} | ${entry.documented ? "yes" : "no"} |`,
    );
  }
  if (report.methods.withoutResultSchema.length === 0) {
    lines.push("| n/a | n/a | n/a |");
  }

  lines.push("", "## Events Without Payload Schema", "");
  if (report.events.withoutPayloadSchema.length === 0) {
    lines.push("- n/a");
  } else {
    for (const eventName of report.events.withoutPayloadSchema) {
      lines.push(`- \`${eventName}\``);
    }
  }

  lines.push("", "## Failures", "");
  if (report.failures.length === 0) {
    lines.push("- none");
  } else {
    for (const failure of report.failures) {
      lines.push(`- ${failure}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

function writeIfNeeded(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
}

function main(): void {
  const report = buildReport();
  const json = `${JSON.stringify(report, null, 2)}\n`;
  const markdown = renderMarkdown(report);

  if (checkMode) {
    const currentJson = existsSync(jsonOutPath) ? readFileSync(jsonOutPath, "utf8") : "";
    const currentMarkdown = existsSync(markdownOutPath)
      ? readFileSync(markdownOutPath, "utf8")
      : "";
    if (currentJson !== json) {
      console.error(`DRIFT: ${repoPath(jsonOutPath)} is not synchronized`);
      process.exit(1);
    }
    if (currentMarkdown !== markdown) {
      console.error(`DRIFT: ${repoPath(markdownOutPath)} is not synchronized`);
      process.exit(1);
    }
  } else {
    writeIfNeeded(jsonOutPath, json);
    writeIfNeeded(markdownOutPath, markdown);
    console.log(`gateway-describe-completeness: wrote ${repoPath(jsonOutPath)}`);
    console.log(`gateway-describe-completeness: wrote ${repoPath(markdownOutPath)}`);
  }

  if (report.failures.length > 0) {
    console.error(report.failures.map((failure) => `ERROR: ${failure}`).join("\n"));
    process.exit(1);
  }

  if (checkMode) {
    console.log(
      `gateway-describe-completeness: ok (${report.summary.methods} methods, ${report.summary.events} events)`,
    );
  }
}

main();
