import { resolve } from "node:path";
import type { TSchema } from "@sinclair/typebox";
import {
  GO_GATEWAY_OUT_DIR,
  PROTOCOL_VERSION,
  TranscriptBlockSchema,
  TranscriptMessageSchema,
  allowlistMethodNames,
  checkGeneratedFiles,
  formatGo,
  methodDefs,
  methodToPascalName,
  schemaRecord,
  sortedEntries,
  typedMethodNames,
  writeGeneratedFiles,
} from "./protocol-common.js";

function goIdent(name: string): string {
  const parts = name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1));
  const ident = parts.join("");
  if (ident === "") {
    return "Value";
  }
  if (/^[0-9]/.test(ident)) {
    return `N${ident}`;
  }
  return ident;
}

function goString(value: string): string {
  return JSON.stringify(value);
}

function schemaToGoType(schema: TSchema, indent = 0): string {
  const s = schemaRecord(schema);
  const kind = s.type as string | undefined;
  if (typeof s.$ref === "string") {
    const ref = s.$ref.split("/").at(-1)?.replace(/#$/, "") ?? s.$ref;
    return ref ? goIdent(ref) : "any";
  }
  if ("const" in s) {
    const value = s.const;
    if (typeof value === "string") {
      return "string";
    }
    if (typeof value === "number") {
      return "float64";
    }
    if (typeof value === "boolean") {
      return "bool";
    }
    if (value === null) {
      return "null";
    }
    return "any";
  }
  if (kind === "null") {
    return "null";
  }
  if (kind === "string") {
    return "string";
  }
  if (kind === "number") {
    return "float64";
  }
  if (kind === "integer") {
    return "int";
  }
  if (kind === "boolean") {
    return "bool";
  }
  if (kind === "array") {
    const items = s.items as TSchema | undefined;
    if (!items) {
      return "[]any";
    }
    const itemType = schemaToGoType(items, indent);
    return itemType === "any" ? "[]any" : `[]${itemType}`;
  }
  if (kind === "object") {
    const patternProps = s.patternProperties as Record<string, TSchema> | undefined;
    if (patternProps) {
      const valueSchema = Object.values(patternProps)[0];
      return valueSchema ? `map[string]${schemaToGoType(valueSchema, indent)}` : "map[string]any";
    }
    const props = s.properties as Record<string, TSchema> | undefined;
    if (!props || Object.keys(props).length === 0) {
      return "map[string]any";
    }
    const fieldPad = "\t".repeat(indent + 1);
    const closePad = "\t".repeat(indent);
    const required = new Set((s.required as string[] | undefined) ?? []);
    const fields = sortedEntries(props).map(([fieldName, fieldSchema]) => {
      const omitEmpty = required.has(fieldName) ? "" : ",omitempty";
      return `${fieldPad}${goIdent(fieldName)} ${schemaToGoType(fieldSchema, indent + 1)} \`json:"${fieldName}${omitEmpty}"\``;
    });
    return `struct {\n${fields.join("\n")}\n${closePad}}`;
  }
  if ("anyOf" in s) {
    const variants = s.anyOf as TSchema[];
    const variantTypes = variants
      .map((variant) => schemaToGoType(variant, indent))
      .toSorted((a, b) => a.localeCompare(b));
    const uniqueTypes = [...new Set(variantTypes)].filter((goType) => goType !== "null");
    if (uniqueTypes.length === 0) {
      return "any";
    }
    if (uniqueTypes.length === 1) {
      return uniqueTypes[0];
    }
    if (uniqueTypes.every((goType) => goType === "int" || goType === "float64")) {
      return "float64";
    }
    if (uniqueTypes.every((goType) => goType === "string")) {
      return "string";
    }
    if (uniqueTypes.every((goType) => goType === "bool")) {
      return "bool";
    }
    return "any";
  }
  return "any";
}

function goNamedTypeBlock(name: string, schema: TSchema): string {
  const goType = schemaToGoType(schema);
  if (goType.startsWith("struct")) {
    return `type ${name} ${goType}\n`;
  } else {
    return `type ${name} = ${goType}\n`;
  }
}

function goHeader(): string[] {
  return [
    "// Code generated by deck-go/contracts/scripts/protocol-gen-go.ts; DO NOT EDIT.",
    "",
    "package generated",
    "",
  ];
}

function generateTypesFiles() {
  const blocks: string[] = [
    goNamedTypeBlock("TranscriptBlock", TranscriptBlockSchema),
    goNamedTypeBlock("TranscriptMessage", TranscriptMessageSchema),
  ];
  for (const method of typedMethodNames()) {
    const def = methodDefs[method];
    const name = methodToPascalName(method);
    if (def.params) {
      blocks.push(goNamedTypeBlock(`${name}Params`, def.params));
    }
    if (def.result) {
      blocks.push(goNamedTypeBlock(`${name}Result`, def.result));
    }
  }

  const chunks: string[][] = [];
  let current: string[] = [];
  let currentLines = goHeader().length;
  for (const block of blocks) {
    const blockLines = block.split("\n").length;
    if (current.length > 0 && currentLines + blockLines > 1800) {
      chunks.push(current);
      current = [];
      currentLines = goHeader().length;
    }
    current.push(block);
    currentLines += blockLines;
  }
  if (current.length > 0) {
    chunks.push(current);
  }

  return chunks.map((chunk, index) => ({
    path: resolve(GO_GATEWAY_OUT_DIR, index === 0 ? "types.go" : `types_extra_${index + 1}.go`),
    content: formatGo([...goHeader(), ...chunk].join("\n")),
  }));
}

function methodSignature(method: string): {
  name: string;
  paramsType: string;
  resultType: string;
  hasParams: boolean;
  hasResult: boolean;
} {
  const def = methodDefs[method];
  const name = methodToPascalName(method);
  return {
    name,
    paramsType: def.params ? `${name}Params` : "map[string]any",
    resultType: def.result ? `${name}Result` : "any",
    hasParams: Boolean(def.params),
    hasResult: Boolean(def.result),
  };
}

function generateMethods(): string {
  const lines: string[] = [
    ...goHeader(),
    "import (",
    '\t"context"',
    '\t"encoding/json"',
    ")",
    "",
    "type Requester interface {",
    "\tRequest(ctx context.Context, method string, params map[string]any) (any, error)",
    "}",
    "",
    "type Client struct {",
    "\trequester Requester",
    "}",
    "",
    "func NewClient(requester Requester) *Client {",
    "\treturn &Client{requester: requester}",
    "}",
    "",
  ];

  for (const method of typedMethodNames()) {
    const sig = methodSignature(method);
    const paramsArg = sig.hasParams ? `params ${sig.paramsType}` : "params map[string]any";
    lines.push(
      `func (c *Client) ${sig.name}(ctx context.Context, ${paramsArg}) (${sig.resultType}, error) {`,
    );
    if (sig.hasResult) {
      lines.push(`\tvar result ${sig.resultType}`);
    }
    if (sig.hasParams) {
      lines.push("\tparamsMap, err := encodeParams(params)");
      lines.push("\tif err != nil {");
      if (sig.hasResult) {
        lines.push("\t\treturn result, err");
      } else {
        lines.push("\t\treturn nil, err");
      }
      lines.push("\t}");
    } else {
      lines.push("\tparamsMap := params");
      lines.push("\tif paramsMap == nil {");
      lines.push("\t\tparamsMap = map[string]any{}");
      lines.push("\t}");
    }
    lines.push(`\tpayload, err := c.requester.Request(ctx, ${goString(method)}, paramsMap)`);
    lines.push("\tif err != nil {");
    if (sig.hasResult) {
      lines.push("\t\treturn result, err");
    } else {
      lines.push("\t\treturn nil, err");
    }
    lines.push("\t}");
    if (sig.hasResult) {
      lines.push(`\treturn decodeResult[${sig.resultType}](payload)`);
    } else {
      lines.push("\treturn payload, nil");
    }
    lines.push("}");
    lines.push("");
  }

  lines.push("func encodeParams(params any) (map[string]any, error) {");
  lines.push("\traw, err := json.Marshal(params)");
  lines.push("\tif err != nil {");
  lines.push("\t\treturn nil, err");
  lines.push("\t}");
  lines.push("\tresult := map[string]any{}");
  lines.push("\tif err := json.Unmarshal(raw, &result); err != nil {");
  lines.push("\t\treturn nil, err");
  lines.push("\t}");
  lines.push("\treturn result, nil");
  lines.push("}");
  lines.push("");

  lines.push("func decodeResult[T any](payload any) (T, error) {");
  lines.push("\tvar result T");
  lines.push("\traw, err := json.Marshal(payload)");
  lines.push("\tif err != nil {");
  lines.push("\t\treturn result, err");
  lines.push("\t}");
  lines.push("\tif err := json.Unmarshal(raw, &result); err != nil {");
  lines.push("\t\treturn result, err");
  lines.push("\t}");
  lines.push("\treturn result, nil");
  lines.push("}");
  lines.push("");

  return formatGo(lines.join("\n"));
}

function generateAllowlist(): string {
  const lines: string[] = [...goHeader(), "var AllowlistMethodNames = map[string]struct{}{"];
  for (const method of allowlistMethodNames()) {
    lines.push(`\t${goString(method)}: {},`);
  }
  lines.push("}");
  lines.push("");
  lines.push("var TypedMethodNames = map[string]struct{}{");
  for (const method of typedMethodNames()) {
    lines.push(`\t${goString(method)}: {},`);
  }
  lines.push("}");
  lines.push("");
  return formatGo(lines.join("\n"));
}

function generateDoc(): string {
  return formatGo(
    [
      "// Code generated by deck-go/contracts/scripts/protocol-gen-go.ts; DO NOT EDIT.",
      "",
      "// Package generated exposes deck-go Gateway protocol bindings generated",
      "// from the root Gateway method registry.",
      "package generated",
      "",
    ].join("\n"),
  );
}

export function generateGoFiles() {
  return [
    {
      path: resolve(GO_GATEWAY_OUT_DIR, "doc.go"),
      content: generateDoc(),
    },
    {
      path: resolve(GO_GATEWAY_OUT_DIR, "allowlist.go"),
      content: generateAllowlist(),
    },
    {
      path: resolve(GO_GATEWAY_OUT_DIR, "methods.go"),
      content: generateMethods(),
    },
    ...generateTypesFiles(),
  ];
}

const checkMode = process.argv.includes("--check") || process.env.CHECK_MODE === "1";
const files = generateGoFiles();

if (checkMode) {
  const ok = checkGeneratedFiles(files, "make protocol-update");
  process.exit(ok ? 0 : 1);
}

writeGeneratedFiles(files);
console.log(`deck-go Go Gateway protocol artifacts use schema version ${PROTOCOL_VERSION}`);
