import { resolve } from "node:path";
import {
  GO_GATEWAY_OUT_DIR,
  PROTOCOL_VERSION,
  TS_GATEWAY_OUT_DIR,
  TranscriptBlockSchema,
  TranscriptMessageSchema,
  allowlistMethodNames,
  checkGeneratedFiles,
  emitNamedTSType,
  eventDefs,
  eventNames,
  formatTS,
  methodDefs,
  methodToPascalName,
  quoteTSKey,
  sortedEntries,
  typedMethodNames,
  writeGeneratedFiles,
} from "./protocol-common.js";

type MethodTree = Map<string, MethodTree | string>;

function buildMethodTree(methods: string[]): MethodTree {
  const root: MethodTree = new Map();
  for (const method of methods) {
    const parts = method.split(".");
    let node = root;
    for (let index = 0; index < parts.length - 1; index++) {
      const part = parts[index];
      const existing = node.get(part);
      if (existing === undefined) {
        const subtree: MethodTree = new Map();
        node.set(part, subtree);
        node = subtree;
      } else if (typeof existing === "string") {
        const subtree: MethodTree = new Map();
        subtree.set("$call", existing);
        node.set(part, subtree);
        node = subtree;
      } else {
        node = existing;
      }
    }

    const leaf = parts.at(-1);
    if (!leaf) {
      continue;
    }
    const existingLeaf = node.get(leaf);
    if (existingLeaf !== undefined && typeof existingLeaf !== "string") {
      existingLeaf.set("$call", method);
    } else {
      node.set(leaf, method);
    }
  }
  return root;
}

function renderClientInterface(tree: MethodTree, lines: string[], depth: number): void {
  const pad = "  ".repeat(depth);
  for (const [key, value] of [...tree.entries()].toSorted(([a], [b]) => a.localeCompare(b))) {
    if (typeof value === "string") {
      const method = value;
      const paramsType = `GatewayMethodMap[${JSON.stringify(method)}]["params"]`;
      const resultType = `GatewayMethodMap[${JSON.stringify(method)}]["result"]`;
      lines.push(
        `${pad}${quoteTSKey(key)}(params: ${paramsType}, options?: { timeoutMs?: number }): Promise<${resultType}>;`,
      );
    } else {
      lines.push(`${pad}${quoteTSKey(key)}: {`);
      renderClientInterface(value, lines, depth + 1);
      lines.push(`${pad}};`);
    }
  }
}

function renderClientFactory(tree: MethodTree, lines: string[], depth: number): void {
  const pad = "  ".repeat(depth);
  for (const [key, value] of [...tree.entries()].toSorted(([a], [b]) => a.localeCompare(b))) {
    if (typeof value === "string") {
      lines.push(`${pad}${quoteTSKey(key)}: call("${value}"),`);
    } else {
      lines.push(`${pad}${quoteTSKey(key)}: {`);
      renderClientFactory(value, lines, depth + 1);
      lines.push(`${pad}},`);
    }
  }
}

export function generateProtocolTypes(): string {
  const lines: string[] = [
    "// Auto-generated by deck-go/contracts/scripts/protocol-gen-ts.ts — DO NOT EDIT",
    "",
    `export const GENERATED_SCHEMA_VERSION = "${PROTOCOL_VERSION}";`,
    "",
  ];

  emitNamedTSType(lines, "TranscriptBlock", TranscriptBlockSchema);
  emitNamedTSType(lines, "TranscriptMessage", TranscriptMessageSchema);

  const methodEntries: string[] = [];
  for (const method of typedMethodNames()) {
    const def = methodDefs[method];
    const name = methodToPascalName(method);
    if (def.params) {
      emitNamedTSType(lines, `${name}Params`, def.params);
    }
    if (def.result) {
      emitNamedTSType(lines, `${name}Result`, def.result);
    }
    const paramsType = def.params ? `${name}Params` : "Record<string, unknown>";
    const resultType = def.result ? `${name}Result` : "unknown";
    methodEntries.push(`  "${method}": { params: ${paramsType}; result: ${resultType} };`);
  }

  lines.push("export interface GatewayMethodMap {");
  lines.push(...methodEntries);
  lines.push("}");
  lines.push("");
  lines.push("export type GatewayMethodName = keyof GatewayMethodMap;");
  lines.push("");

  const eventEntries: string[] = [];
  for (const [eventName, def] of sortedEntries(eventDefs)) {
    if (!def.payload) {
      continue;
    }
    const name = `${methodToPascalName(eventName)}EventPayload`;
    emitNamedTSType(lines, name, def.payload);
    eventEntries.push(`  "${eventName}": ${name};`);
  }

  lines.push("export interface GatewayEventPayloadMap {");
  lines.push(...eventEntries);
  lines.push("}");
  lines.push("");
  lines.push("export type GatewayTypedEventName = keyof GatewayEventPayloadMap;");
  lines.push("");
  return lines.join("\n") + "\n";
}

export function generateClient(): string {
  const lines: string[] = [
    "// Auto-generated by deck-go/contracts/scripts/protocol-gen-ts.ts — DO NOT EDIT",
    "",
    'import type { GatewayMethodMap, GatewayMethodName } from "./protocol";',
    "",
    "export type GatewayRequestFn = <M extends GatewayMethodName>(",
    "  method: M,",
    '  params: GatewayMethodMap[M]["params"],',
    "  options?: { timeoutMs?: number },",
    ') => Promise<GatewayMethodMap[M]["result"]>;',
    "",
    "export const GENERATED_METHOD_ALLOWLIST: ReadonlySet<string> = new Set([",
  ];

  for (const method of allowlistMethodNames()) {
    lines.push(`  "${method}",`);
  }
  lines.push("]);");
  lines.push("");

  lines.push("export const GENERATED_EVENT_NAMES: ReadonlySet<string> = new Set([");
  for (const eventName of eventNames.toSorted((a, b) => a.localeCompare(b))) {
    lines.push(`  "${eventName}",`);
  }
  lines.push("]);");
  lines.push("");

  lines.push("export const GENERATED_TYPED_EVENT_NAMES: ReadonlySet<string> = new Set([");
  for (const eventName of Object.keys(eventDefs).toSorted((a, b) => a.localeCompare(b))) {
    lines.push(`  "${eventName}",`);
  }
  lines.push("]);");
  lines.push("");

  const tree = buildMethodTree(typedMethodNames());
  lines.push("export interface GatewayClient {");
  renderClientInterface(tree, lines, 1);
  lines.push("}");
  lines.push("");

  lines.push("export function createGatewayClient(request: GatewayRequestFn): GatewayClient {");
  lines.push("  const call = <M extends GatewayMethodName>(method: M) =>");
  lines.push('    (params: GatewayMethodMap[M]["params"], options?: { timeoutMs?: number }) =>');
  lines.push("      request(method, params, options);");
  lines.push("");
  lines.push("  return {");
  renderClientFactory(tree, lines, 2);
  lines.push("  };");
  lines.push("}");
  lines.push("");

  return lines.join("\n") + "\n";
}

export function generateTSFiles() {
  const protocolPath = resolve(TS_GATEWAY_OUT_DIR, "protocol.ts");
  const clientPath = resolve(TS_GATEWAY_OUT_DIR, "client.ts");
  return [
    {
      path: protocolPath,
      content: formatTS(generateProtocolTypes(), protocolPath, "deck-go gateway protocol"),
    },
    {
      path: clientPath,
      content: formatTS(generateClient(), clientPath, "deck-go gateway client"),
    },
  ];
}

const checkMode = process.argv.includes("--check") || process.env.CHECK_MODE === "1";
const files = generateTSFiles();

if (checkMode) {
  const ok = checkGeneratedFiles(files, "make protocol-update");
  process.exit(ok ? 0 : 1);
}

writeGeneratedFiles(files);
console.log(`deck-go TS Gateway protocol artifacts are in ${TS_GATEWAY_OUT_DIR}`);
console.log(`Go artifacts are generated separately in ${GO_GATEWAY_OUT_DIR}`);
